### ISSUE TITLE
Please Mongodb Connect!

### ISSUE THREAD

**Issue by cndtms** [catfan/Medoo#1000]
**Information**
- Version of Medoo:
- Type of Database (MySQL, MSSQL, SQLite...):
- System (Liunx\Windows\Mac):

**Describe the Problem**
A clear and concise description of what the problem is.

**Detail Code**
The detail code you are using causes the problem.

**Expected output**
A clear and concise description of what output you expected.

**Comment by catfan** [comment]
MongoDB is a key-value database, and Medoo is a PDO-based SQL database framework.

It's fundamentally different and impossible to support.

You can check out the list of MongoDB frameworks here: https://docs.mongodb.com/drivers/php-libraries/.
