### ISSUE TITLE
LIKE in WHERE wrong statement with dash (-)

### ISSUE THREAD

**Issue by objectivisto** [catfan/Medoo#1001]
- Medoo: 2.1.2
- MySQL
- Liunx

Medoo’s count() in version 2.1.2 is generating a wrong SQL statement, if we use the LIKE operator in the WHERE clause, and the search term contains a dash. Under these conditions, it is missing the embedding % character at the start and the end of the search term.

This works well:

$searchString = "tomspage”; // no dash in search term
$countAds = $db->count('xyzAd', array('linkManual[~]'=>$searchString));
Correct query generated: SELECT COUNT(*) FROM `xyzAd` WHERE (`linkManual` LIKE '%tomspage%')

This does not work:

$searchString = “toms-page"; // with dash in search term
$countAds = $db->count('xyzAd', array('linkManual[~]'=>$searchString));
Faulty query generated (missing %%): SELECT COUNT(*) FROM `xyzAd` WHERE (`linkManual` LIKE 'toms-page')

In previous versions of Medoo it works well, verified in version 1.7.10.

**Comment by Seevil** [comment]
I also encountered this problem...

**Comment by Seevil** [comment]
xdebug 分析后发现是正则的问题
https://github.com/catfan/Medoo/blob/8d2147808a2795cf58f6da94f82281f6a5433221/src/Medoo.php#L1171

执行到此行 LIKE  数值丢失😫

**Comment by webgoto** [comment]
The behavior is also strange when it contains underscores.

`$database->select('options', 'option_id', ['option_id[~]'=>'a_']);`
↓
SELECT \`option_id\` FROM \`options\` WHERE (\`option_id\` LIKE 'a_')

'a_' is not wrapped in '%'.

-------------------------------------------

It works fine if I escape with '\\'.

`$database->select('options', 'option_id', ['option_id[~]'=>'a\_']);`
↓
SELECT \`option_id\` FROM \`options\` WHERE (\`option_id\` LIKE '%a\_%')


Is this bug?

**Comment by catfan** [comment]
@webgoto `_` is a wildcard character for representing a single character. `a_` will match `aa`, `ab`, `ac`, and more.

So if you just want to match the underscore `_` character, you need to add a slash.

https://www.w3schools.com/sql/sql_wildcards.asp

**Comment by stupidloud** [comment]
I will suggest to use INSTR instead of LIKE
