### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Medoo\array_key_last() 

### ISSUE THREAD

**Issue by RetiredQQ** [catfan/Medoo#1004]
**Information**
- Version of Medoo: 2.1.2 (latest)
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Linux - PHP 7.2

**Describe the Problem**
As I said in the title but when I try version 1.7.1 its works so I downgrade Medoo to the old version.

**Detail Code**
`$db->select("users", ["is_refunded"], ["LIMIT" => 100]);`

**Expected output**
A clear and concise description of what output you expected.
`Fatal error: Uncaught Error: Call to undefined function Medoo\array_key_last() in /var/www/html/Medoo.php:1584`

**Comment by catfan** [comment]
Since v2.0, the minimal requirement is PHP 7.3+.

Just upgrade to PHP 7.3, or PHP 7.4 is recommended.

**Comment by RetiredQQ** [comment]
I just confirm that after upgrading my PHP version to 7.3 the issue is gone.
