### ISSUE TITLE
Multiple OR statements for the same column does not work

### ISSUE THREAD

**Issue by piotrekjeremicz** [catfan/Medoo#1013]
**Information**
- Version of Medoo: 2.1.1
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Linux

**Describe the Problem**
When trying to check two `OR` statements, for the same column, only one is assembled in query.

**Detail Code**
```
$selectedQuery = $this->database->select(
"Names",
[
	'name,
], [
	'OR' => [
		'name[~]' => "$search",
		'name[~]' => "$newSearch",
	],
	'LIMIT' => 15,
	'GROUP' => 'name'
]);
```

The query result:
SELECT `name` FROM `Names` WHERE ((`name` LIKE '%first%')) GROUP BY `name` LIMIT 15

**Expected output**
SELECT `name` FROM `Names` WHERE ((`name` LIKE '%first%') OR (`name` LIKE '%second%')) GROUP BY `name` LIMIT 15

**Comment by catfan** [comment]
Read https://medoo.in/api/where with the `LIKE Condition` section.

```php
$database->select("person", "id", [
	"city[~]" => ["lon", "foo", "bar"]
]);
```
