### ISSUE TITLE
Deprecated "[=]" on query where (2.1.2 => 2.1.3)

### ISSUE THREAD

**Issue by ajmrive** [catfan/Medoo#1021]
**Information**
- Version of Medoo: 2.1.2 OK => 2.1.3 fail
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Linux\Windows\Mac): Linux

**Describe the Problem**
When we migrated from 2.1.2 to 2.1.3 some test fail in a query with a "[=]" conditions. Make sense that 'status[=]' => 0 is the same as 'status' => 0, and [=] is not neccesary but I can not find a changelog with this deprecated issue.

**Detail Code**
$medoo->select(
'rule',
[
     [>]services'  => [service_uuuid => rule]
],
[
service_uuuid
],
[
'date[=]' => 0
]

);

**Expected output**
We expected find an error when run the query or deprecate warning somewhere.

Kind regards

**Comment by catfan** [comment]
Sorry for the delayed response.

It's good to throw errors for the invalid operator.

I updated it on 8ab1206. It supports for `[=]` and simplified the matching (may be easier for extending the operation for the next).
