### ISSUE TITLE
How to implement composite conditions

### ISSUE THREAD

**Issue by xrayffa** [catfan/Medoo#1024]
**Information**
- Version of Medoo:@version 2.1.2
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx\Windows\Mac):Liunx

**Describe the Problem**

I want to list the data with age = 6 or age = null in the user table

**Detail Code**
$res = $db->select('user','id',[
   'sex'=>1,
   'age'=>['OR'=>[6,null] ]
]);

Fatal error: Uncaught TypeError: PDOStatement::bindValue() expects parameter 3 to be int, null given in ...../vendor/catfan/medoo/src/Medoo.php:554

I know it's effective, but it's not the effect I want, like this:
$database->select("person", "id", [
	"content[~]" => ["OR" => ["lon", "on"]]
]);

**Expected output**

**I hope to list the data in the following ways:**

        $res = $db->select('user','id',[
            'sex'=>1,
            'age'=>['OR'=>[6,null] ]
        ]);

or:

        $res = $db->select('user','id',[
            'sex'=>1,
            'age'=>['AND'=>[6,null] ]
        ]);

or:

        $res = $db->select('user','id',[
            'sex'=>1,
            'age'=>[6,null]
        ]);

or:

        $res = $db->select('user','id',[
            'sex'=>1,
            'age[!]'=>[6,null]
        ]);

Similar to this effect:
SELECT id FROM user WHERE (age IS NULL OR  age = 6) AND sex=1 ...........
or:
SELECT id FROM user WHERE (age IS NOT NULL OR age = 6) AND sex=1 ...........

How to realize it?

**Comment by catfan** [comment]
That logic does not make sense if using null with conditions together.

If age is equal to 6, `age is NULL` is always failed.

If age is NULL, `age = 6` is always failed.

And `age is NULL` is always failed if combined with other `AND` conditions.
