### ISSUE TITLE
PHP Notice: Undefined index: time in Medoo.php on line 1088

### ISSUE THREAD

**Issue by artrogue** [catfan/Medoo#1029]
**Information**
- Version of Medoo: 1.7.10
- Version of Php: 7.0.33
- System (Liunx): ubuntu 0.16.04.16

**Describe the Problem**
Php error.log  All :
PHP Notice: Undefined index: time in Medoo.php on line 1088 
PHP Notice: Undefined index: time in Medoo.php on line 1088
PHP Notice: Undefined index: time in Medoo.php on line 1088
....

**Comment by catfan** [comment]
Medoo is in version 2.0+ already. We don't maintain the old version anymore. Please upgrade and describe more detail for the issue if there is a problem.
