### ISSUE TITLE
bug: can not quote the follow sql: "DROP TABLE IF EXISTS <user>;" 

### ISSUE THREAD

**Issue by qt06** [catfan/Medoo#1036]
**Information**
- Medoo version 2.1.4
- php 7.4
- mysql5.7
- windows

**Describe the Problem**
The <>quotation syntax can not used on the sql contains 'exists'. For example:
`DROP TABLE IF EXISTS <user>;`

**Detail Code**
```php
$database = new Medoo([
	....
	"prefix" => "WP_"
]);
$database.query("DROP TABLE IF EXISTS <user>;");
```

**Expected output**
DROP TABLE IF EXISTS "WP_user";

**Comment by catfan** [comment]
This is fixed on 00ea59d.
