### ISSUE TITLE
Medoo Connection Problem.

### ISSUE THREAD

**Issue by dazayuan** [catfan/Medoo#1041]
我是个新手，用Apache2.4.53+PHP8.1+MySql8.0架设了一个网站，用本网下载的medoo2.1.4，没作其他改动，只把mysql信息添加上，但连接不上，求高手帮助，谢谢！
我的代码样式：
.....
     */
    public $errorInfo = null;
       /**
     * Connect the database.*/ 
	 $database = new Medoo([
	         // required
           'type' => 'mysql',
           'database' => 'net',
           'host' => 'localhost',
           'username' => 'h..l',
           'password' => '.....',
     
           // [optional]
           'charset' => 'utf8mb4',
           'port' => 3306
     /*    'prefix' => 'PREFIX_'*/
     ]);
    /* * @param array $options Connection options
     * @return Medoo
     * @throws PDOException
     * @link https://medoo.in/api/new
     * @codeCoverageIgnore
     */

    public function __construct(array $options)
    {
......

**Comment by dazayuan** [comment]
https://github.com/catfan/Medoo/blob/master/src/Medoo.php

**Comment by catfan** [comment]
We don't know anything about the information you provided.

Please read our documentation https://medoo.in/api/new, and check the error message for the connection.
