### ISSUE TITLE
does medoo not support view data with ajax

### ISSUE THREAD

**Issue by N4I-I12uN** [catfan/Medoo#1043]
Ajax :
```
<script type="text/javascript">
	$(document).ready(function(){
	  $.ajax({
	   type: 'POST',
	   url: "template/module/objek/get_provinsi.php",
	   cache: false,
	   success: function(msg){
	  $("#provinsi").html(msg);
	}
});
</script>
```

Select Form :
```
<div class="form-group">
  <label>Letak</label>
	<div class="row">
	 <div class="col-sm-6">
	  <select class="form-control" name="provinsi" id="provinsi">
              <option value=""> ---Pilih Provinsi</option>
          </select>
	 </div>
   </div>
</div>	
```

get_provinsi.php (location file: template/module/objek) :

```
<?php
  $query=$database->select('wk_provinsi','*');
  foreach ($query as $query) {
	echo "<option value=''>Pilih Provinsi - - </option>";
  }
?>
```

data does not appear on the select form
does medoo not support view data with ajax ??

**Comment by catfan** [comment]
Check out this error code:
```php
  foreach ($query as $query) {
	echo "<option value=''>Pilih Provinsi - - </option>";
  }
```

**Comment by N4I-I12uN** [comment]
`<?php

  echo "<option value=''> ++++ PiliH Provinsi ++++ </option>";

  $query=$database->select('wk_provinsi','*');
  foreach ($query as $query) {
  // echo "<option>".$query['provinsi']."</option>";
    echo "<option value='" . $query['id_provinsi'] . "'>" . $query['provinsi'] . "</option>";
  }

?>
`

Not work bro

**Comment by catfan** [comment]
```php
foreach ($query as $query)
```
Cannot write like this.

Please read the PHP documentaion on how to write the correct `foreach` expression.
https://www.php.net/manual/en/control-structures.foreach.php
