### ISSUE TITLE
queryString

### ISSUE THREAD

**Issue by flakka2022** [catfan/Medoo#1053]
**Information**
- Version of Medoo: last
- Version of PHP: 8.1
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx|Windows|Mac): Linux and Windows

**Describe the Problem**
there is no way to get queryString before execute and do that out of testMode ? if its how possible ?
**Detail Code**
The detail code you are using causes the problem.
```php
// Write your PHP code here

```

**Expected output**
return query string out of testMode and before execution .

**Comment by catfan** [comment]
Use `debug()` or `beginDebug()`.

https://medoo.in/api/debug
