### ISSUE TITLE
Medoo tableQuote behave differently based on system

### ISSUE THREAD

**Issue by SilverBull** [catfan/Medoo#1063]
**Information**
- Version of Medoo: 2.1.7
- Version of PHP: 8.1.2 and 8.1.9
- Type of Database: MSSQL and MySQL
- System : Ubuntu 22.04 and Debian 10 

**Describe the Problem**
Trying to select records from a table that starts with an underscore generate different behaviors on Mysql and Mssql.
On mssql the query runs just fine, on mysql on other hand medoo trows a InvalidArgumentException, digging in the code looks like it fails the preg_match `'/^(?![_\d])[\p{N}\p{L}\-_]+$/u'` but shouldn't fails on mssql too?

Obviously the raw query runs just fine with `$datas = $database->query("SELECT id FROM _test")->fetchAll();`

**Detail Code**
The detail code you are using causes the problem.
```php
$datas = $database->select("_test","id");

```

**Expected output**
Either pass on both versions or fails on both versions

**Comment by SilverBull** [comment]
I update the problem, apparently it's not related to database, I tried to replicate the same mssql database and Medoo throw the same error. So it's maybe some php config or don't know. I will edit the title to reflect this update

**Comment by catfan** [comment]
I didn't found the Regex `/^(?![_\d])[\p{N}\p{L}\-_]+$/u` you mentioned on the project. What Medoo version are you using?

**Comment by SilverBull** [comment]
Sorry for the delay in responding, as mentioned in the opening, I am using 2.1.7. In the meantime I created a copy of prod's MSSQL database under the same machine that hosts MySQL and found that the problem persists. So it is something else in the environment that is causing the problem.
