### ISSUE TITLE
Bad string interpolation syntax in Medoo.php

### ISSUE THREAD

**Issue by greg1lutz** [catfan/Medoo#1074]
Lines 870 and 1321 of Medoo.php, ver 2.1.7, use the wrong string interpolation syntax: " ... ${var} ... " rather than " ... {$var} ... ". As of php 8.2, this syntax is deprecated, and produces messages to that effect when the code is executed.

**Comment by catfan** [comment]
v2.1.8 was released with the fix. https://github.com/catfan/Medoo/releases/tag/v2.1.8
