### ISSUE TITLE
debug() don't work in the latest version.

### ISSUE THREAD

**Issue by martinloren** [catfan/Medoo#1081]
Got latest version with composer ->  "catfan/medoo": "^2.1",
1. DB connection works
2. no error output with the debug methods

WORKING INSTRUCTION
$data = $db->query('SELECT * FROM users_stats')->fetchAll();

NOT WORKING INSTRUCTION (output just the query without any content)
$data = $db->debug()->select("users_stats", "*");

**Comment by catfan** [comment]
What is the full code you actually ran?

You may need to check out your code in your whole project.

**Comment by martinloren** [comment]
Found in the source code that actually when you add ->debug() in front of the function it doesn't execute the function.

Thanks anyway, can be closed.
