### ISSUE TITLE
sum() sometimes returns string instead of number

### ISSUE THREAD

**Issue by m-nienberg** [catfan/Medoo#1083]
If the sum() functions doesn't find any matches it returns an empty string. I suggest it would be better to return zero. Otherwise you can get a fatal error if you try to use the result in a function that will not accept a string.

    $total = $database->sum("account", "money", ["currency" => "dollars"]); 
    echo "We have $" . number_format($total, 0);   <--- fatal error

The documentation at https://medoo.in/api/sum says that the return will be a number.
I haven't tested, but the same may be true for the other Aggregation functions.

**Comment by catfan** [comment]
That's the document problem. I have fixed it. [4cb6410](https://github.com/catfan/Medoo/commit/4cb64107b6be97525353a4704a9f4f394844600d)

Those aggregate methods will return a string. You have to cast it to float or integer. Zero will not be correct in some cases.
