### ISSUE TITLE
invalid value for parameter "client_encoding": "utf8mb4"

### ISSUE THREAD

**Issue by rexluciano** [catfan/Medoo#1084]
**Information**
- Version of Medoo: 2.1.8
- Version of PHP: 8.0
- Type of Database (MySQL, MSSQL, SQLite...): PostgreSQL
- System (Liunx|Windows|Mac): Linux

**Describe the Problem**
A clear and concise description of what the problem is.
I'm using PostgreSQL version 14 and it was giving me invalid value for parameter "client_encoding": "utf8mb4"

**Detail Code**
The detail code you are using causes the problem.
```php
// Write your PHP code here

```

**Expected output**
A clear and concise description of what output you expected.

**Comment by catfan** [comment]
Please remove the `'charset' => 'utf8mb4'` or change it to `utf8` from your database connection option.

It's an optional option.
