### ISSUE TITLE
'String' in Data Type Declaration does not work

### ISSUE THREAD

**Issue by webgoto** [catfan/Medoo#1085]
Thanks for the great library.

**Information**
- Version of Medoo: 2.1.8
- Version of PHP: 8.1
- Type of Database (MySQL, MSSQL, SQLite...): SQLite
- System (Liunx|Windows|Mac): Windows

**Describe the Problem**
A clear and concise description of what the problem is.

`$db->select('folder', ['id[String]','name','articleOrder[JSON]']);`
Even if you run this, the ID will be returned as a number.

Looking at the source code
https://github.com/catfan/Medoo/blob/master/src/Medoo.php#L1464
```php
                        case 'String':
                            $stack[$columnKey] = $item;
                            break;
```
Shouldn't we add (string) like this?
`$stack[$columnKey] = (string) $item;`

**Comment by catfan** [comment]
Thanks for the feedback.

Would you submit a pull request for this?

**Comment by webgoto** [comment]
Sorry. Due to my lack of skill, I don't know how to use git.

**Comment by carliblaz** [comment]
I'm not sure that this was OK, db field bigint(20) has now string value not int.
