### ISSUE TITLE
more database support please

### ISSUE THREAD

**Issue by aaronkingdom** [catfan/Medoo#1102]
**Information**
- Version of Medoo:
- Version of PHP:
- Type of Database (MySQL, MSSQL, SQLite...):
- System (Liunx|Windows|Mac):

**Describe the Problem**
A clear and concise description of what the problem is.

**Detail Code**
The detail code you are using causes the problem.
```php
// Write your PHP code here

```

**Expected output**
A clear and concise description of what output you expected.

redis + mondo??

**Comment by catfan** [comment]
It's a completely different type of database, so it's impossible.

And what's mondo?
