### ISSUE TITLE
 Fatal error: Uncaught Error: Class "Medoo\Medoo" not found in Project_Asset_Management+Ticket\includes\loader.php:39

### ISSUE THREAD

**Issue by KuugaYuuto** [catfan/Medoo#1106]
Hello, I recently created a project to try out Medoo for the first time but I got the error as shown in the title even I do like guidebook.
Can you help me fix it?
Here is my [project](https://github.com/KuugaYuuto/KuugaYuuto-KuugaYuuto-Project_Asset_Management-Ticket-PHP-MySQL).
I would be very grateful and appreciative if you would fix it for me!

**Comment by catfan** [comment]
You are not using Composer to load the package.

So you have to include the file of medoo.php into your project.
```php
require  PATH_OF_YOUR_PROJECT . '/Medoo.php';
```
