### ISSUE TITLE
Faster Migrate to Medoo From Conventional

### ISSUE THREAD

**Issue by JFOC** [catfan/Medoo#1107]
Hi,

IS there way for faster migration method to Medoo?

I have a lot of codes still using conventional __mysqli_query__ mostly (99%) is SELECT operation and no LEFT/RIGHT JOIN with none of them mysqli_real_escape_string

**Comment by catfan** [comment]
Well, you can use ChatGPT to do that:

Prompt:
```
Convert this MySQL query with Medoo:
$mysqli->query("SELECT Name FROM City LIMIT 10")
```

ChatGPT Result:
```php
$columns = ['Name'];
$limit = 10;

$results = $database->select('City', $columns, ['LIMIT' => $limit]);

foreach ($results as $result) {
    // Process each row in $result
    echo $result['Name'] . '<br>';
}
```

**Comment by JFOC** [comment]
thats brilliant 😅  probably you can add chatgpt features on medoo for everyone who want converting the query, but that out the scope of Medoo
