### ISSUE TITLE
The log() method reports an error, there is a problem with type judgment 'double' => PDO::PARAM_STR.

### ISSUE THREAD

**Issue by TimeIsGoOn** [catfan/Medoo#1108]
**Information**
- Version of Medoo:v2.1.10
- Version of PHP: 8.2.14
- Type of Database (MySQL, MSSQL, SQLite...): Postgresql
- System (Liunx|Windows|Mac):Linux 

**Describe the Problem**
执行log()方法报错

TypeError: Medoo\\Medoo::quote(): Argument #1 ($string) must be of type string, float given, called in /www/webman/vendor/catfan/medoo/src/Medoo.php on line 607 and defined in /www/webman/vendor/catfan/medoo/src/Medoo.php:696
Stack trace:
**#0 /www/webman/vendor/catfan/medoo/src/Medoo.php(607): Medoo\\Medoo->quote(555.1)**
#1 /www/webman/vendor/catfan/medoo/src/Medoo.php(2205): Medoo\\Medoo->generate('UPDATE \"page\" S...', Array)
#2 [internal function]: Medoo\\Medoo->Medoo\\{closure}(Array)
#3 /www/webman/vendor/catfan/medoo/src/Medoo.php(2203): array_map(Object(Closure), Array)
#4 /www/webman/app/wmapi/controller/PageController.php(215): Medoo\\Medoo->log()

  问题出在　https://github.com/catfan/Medoo/blob/eb1ad19d127bd358b9a44abc60166b4a2c19a988/src/Medoo.php#L749
![image](https://github.com/catfan/Medoo/assets/13595639/bfa397be-c66d-45bc-8d9d-5ed655d27131)
这里　double　类型被看做了字符串，但是555.1不是字符串，
导致调用quote函数时参数类型检查错误

https://github.com/catfan/Medoo/blob/eb1ad19d127bd358b9a44abc60166b4a2c19a988/src/Medoo.php#L607

![image](https://github.com/catfan/Medoo/assets/13595639/319eddc0-ec2a-4d2a-95b0-3c1dc22b6ccf)

![image](https://github.com/catfan/Medoo/assets/13595639/5d84c369-0aa6-4f6b-8c5d-5169b52e867f)

请看看这个如何修改，或者是在调用的时候，类型强制转换为 string

**Comment by catfan** [comment]
Fixed it on [b409028](https://github.com/catfan/Medoo/commit/b4090284893f7ef83eca723eb52c012409cac02c).

#1011
#1020
