### ISSUE TITLE
count() ignores $where clause

### ISSUE THREAD

**Issue by amitbansod** [catfan/Medoo#111]
I tried to use count as follows for a reason:
```php
public function count_main($table,$join=NULL,$column=NULL,$where=NULL){
	
		$count = $db->medoo->count($table,$join,$column,$where);
	}
```
If the $join and $column are NULL, the count() ignores the $where clause. 

But this works: 
```php
public function count_main($table,$join=NULL,$column=NULL,$where=NULL){
	
		$count = $db->medoo->count($table,$where);
	}
```
This happens because you assign $where = $join if $column is NULL and later $where = $join when $count_fn is SET.

Any way to get around this to use the count() in the format specified ? I always want to pass $join, $column and $where even when they are NULL.

**Comment by catfan** [comment]
Fixed
