### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by chenbaicheng** [catfan/Medoo#1124]
**Information**
- **Version of Medoo:** [non]
- **Version of PHP:** [5.6]
- **Type of Database:** [MySQL,.]
- **System:** [Windows]

**Describe the Problem**
When I haven’t run the CRUD functions and directly run the last function, the following error will pop up.
`<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>C:\xampp_5.6\htdocs\XXX\vendor\catfan\medoo\src\Medoo.php</b> on line <b>400</b><br />
`
**Code Snippet**
The detail code you are using that causes the problem:
```php
// Write your PHP code here
$database->last();
```

**Comment by catfan** [comment]
The line 400 of the code is about the MSSQL connection.

What is the full code you called?

**Comment by chenbaicheng** [comment]
> The line 400 of the code is about the MSSQL connection.
> 
> What is the full code you called?

Sorry for the late response. I haven’t opened GitHub for the past few weeks. I tried it out a bit, and if the CRUD operations have never been executed, running the last function directly will throw an error. So, I deleted the last function, and it worked fine since it’s just for debugging purposes. I just wanted to output the SQL statement during debugging.

Also, my current version seems quite old, PHP 5.6. Maybe the newer versions don’t have this issue. I’m not sure if it’s a problem with the foreach function, but it shouldn’t throw an error if it’s empty. I also find it quite strange. As long as the CRUD operations have been executed once, the last function won’t throw an error.

**Comment by catfan** [comment]
The line of 400 is not `foreach()`.

https://github.com/catfan/Medoo/blob/d1ff4e0e873a3e032e3d8804031dd6be4e013b22/src/Medoo.php#L399-L401

And the `last()` will return null if it has no log data.

https://github.com/catfan/Medoo/blob/d1ff4e0e873a3e032e3d8804031dd6be4e013b22/src/Medoo.php#L2194-L2203

Are you sure you are using the latest version of Medoo?
