### ISSUE TITLE
Uncaught TypeError: PDO::__construct(): Argument #2 ($username) must be of type ?string, bool given

### ISSUE THREAD

**Issue by Aspyryan** [catfan/Medoo#1128]
**Information**
- **Version of Medoo:**  2.1.12
- **Version of PHP:** 8.2.4
- **Type of Database:** [MySQL
- **System:** Windows

**Describe the Problem**
Randomly getting the following error on like 1/3 of the times I call the API
```
:  Uncaught TypeError: PDO::__construct(): Argument #2 ($username) must be of type ?string, bool given in D:\Projects\Programmeren\handbal\vendor\catfan\medoo\src\Medoo.php:450
Stack trace:
#0 D:\Projects\Programmeren\handbal\vendor\catfan\medoo\src\Medoo.php(450): PDO-&gt;__construct('mysql:dbname=;h...', false, Object(SensitiveParameterValue), Array)
#1 D:\Projects\Programmeren\handbal\common\DatabaseFunctions.php(20): Medoo\Medoo-&gt;__construct(Array)
```

I am also never able to catch the PDO Exception to get more information. This happens in development and never in production

**Code Snippet**
The detail code you are using that causes the problem:
```php
<?php
class DatabaseFunctions
{
	private static Medoo | null $connection = null;
	public static function connect(): Medoo
	{
		try {
			if (self::$connection != null) {
				return self::$connection;
			}

			(new DotEnv(__DIR__ . '/../.env'))->load();

			self::$connection = new Medoo([
				'type' => 'mysql',
				'host' => getenv("DATABASE_SERVER"),
				'database' => getenv("DATABASE_NAME"),
				'username' => getenv("DATABASE_USERNAME"),
				'password' => getenv("DATABASE_PASSWORD"),
				'charset' => 'utf8'
			]);

			return self::$connection;
		} catch (\PDOException $e) {
			throw new \Exception("Database connection failed: " . $e->getMessage());
		}
	}
}

```

**Expected Behavior**
It to work consistently and not fail randomly

**Actual Behavior**
failing 1/3 of the times with the error above, fails on the new Medoo() call.

**Comment by Aspyryan** [comment]
Also never able to catch the PDOException

**Comment by catfan** [comment]
The error says that `getenv("DATABASE_USERNAME")` returns a bool value, not a string.

You may check out why `getenv()` returns that.

**Comment by Aspyryan** [comment]
Instead of my own DotEnv implementation I started using https://github.com/vlucas/phpdotenv, was probably something with thread safety. Issue resolved, thanks!
