### ISSUE TITLE
[Feature Request] Allow DISTINCT in a select statement

### ISSUE THREAD

**Issue by Brobin** [catfan/Medoo#113]
For example, I would like to run a query like this.

`SELECT DISTINCT(month), year FROM posts`

I haven't found anything in the documentation that addresses this. Perhaps the syntax could be like this:

`$medoo->select("posts", array("month", "year"), array("DISTINCT" => "month"));`
or:
`$medoo->select("posts", array("DISTINCT month", "year"));`
or:
`$medoo->select("posts", array("DISTINCT(month)", "year"));`

I don't think this would be too difficult to implement. I would be willing to help out, but I need to study the codebase more carefully first.

**Comment by darre4nbrown** [comment]
This is how i did it.
under the comment for variables add the line
protected $distinct_mode = false;

then i added the folowing function below the debug function 

	public function distinct()
	{
		$this->distinct_mode = true;

		return $this;
	}

to the function select_context($table, $join, &$columns = null, $where = null, $column_fn = null) I added:

		if($this->distinct_mode)
		{
			$distinct = 'DISTINCT ';
		} else {
			$distinct = '';
		}

and changed the return line (last line in the function) to

return 'SELECT ' . $distinct  . $column . ' FROM ' . $table . $this->where_clause($where);

Then it can be set the same way as using the debug() function ie

$database->distinct()->select(...
$database->debug()->distinct()->select(...

hope this helps for anyone in the future

**Comment by emvo** [comment]
@darre4nbrown thanks mate

**Comment by dimitrycastex** [comment]
@darre4nbrown thanks, but in latest version the function should be
return 'SELECT ' . $distinct . $column . ' FROM ' . **$table_query** . $this->where_clause($where);

**Comment by repat** [comment]
Another workaround:
```php
$result = array_unique($database->select($table, $columns));
```

**Comment by adarshmadrecha** [comment]
This is how you can select distinct values - by passing SQL functions using `Medoo::raw`

```
    $resultset = $db->select(
      // table name
      'posts',
      // Columns
      [
        'month' => Medoo::raw( 'DISTINCT (month' )
      ],
    );
```

**Comment by cw1427** [comment]
Hi, how about the distinct feature implement? Could we use it in the latest version?

**Comment by nathanael540** [comment]
Hi, how about the distinct feature implement? Could we use it in the latest version?

**Comment by scr4bble** [comment]
Any progress on this?

**Comment by SevenbitsIt** [comment]
I'd love to see this implemented too.

**Comment by meast** [comment]
use Medoo::raw like this:

`
 $where = []; # some conditions.
 $db->select('table', ['field_name'=>Medoo\Medoo::raw('DISTINCT field_name')], $where);
`
