### ISSUE TITLE
[Feature Request] Update Batch like Codeigniter

### ISSUE THREAD

**Issue by snail007** [catfan/Medoo#115]
Codeigniter database driver can update batch data once ,use mysql's "WHEN ...  THEN ... " statement .
MySQL example:
UPDATE categories
    SET display_order = CASE id
        WHEN 1 THEN 3
        WHEN 2 THEN 4
        WHEN 3 THEN 5
    END,
    title = CASE id
        WHEN 1 THEN 'New Title 1'
        WHEN 2 THEN 'New Title 2'
        WHEN 3 THEN 'New Title 3'
    END
WHERE id IN (1,2,3);
This feature has  great performance when we had many  similar data to update.
Such as:
$db->update_batch($table,$full_data,$case_column)

**Comment by wakerman** [comment]
Unfortunately, there is no such function
