### ISSUE TITLE
[MySQL] - don't understand " for table, only `

### ISSUE THREAD

**Issue by ghost** [catfan/Medoo#116]
As i wrote in title, for Mysql all my requests are KO.

for BAD example generated :

``` sql
SELECT * FROM "table"
```

for GOOD example : 

``` sql
SELECT * FROM `table`
```

if type is mysql, object delimiter (database, table and column) is `

**Comment by kovinet** [comment]
Could you explain how you solved this? How can I make MySQL to use standard quotes? I have to specify this in constructor?

**Comment by catfan** [comment]
@kovinet If you are using Medoo, you don`t have to care about the quotes. And I also answered the reason why the quote identifier is different.

**Comment by pekkanikolaus** [comment]
> $commands[] = 'SET SQL_MODE=ANSI_QUOTES';

doesn't always work, especially in shared hosting environments.
Changing a mySQL option to cater for a framework creating broken mySQL code is "register_globals"-level insanity. 

The solution is to escape table names the way all other frameworks utilizing mySQL do: with backticks.
