### ISSUE TITLE
ORDER RAND() not working

### ISSUE THREAD

**Issue by omphteliba** [catfan/Medoo#133]
Hi,

i can't get "ORDER RAND()" to work. When i add it with

 "ORDER"=>"RAND()"

the query produced looks something like that:

SELECT "screen_name" 
FROM "users" 
WHERE "screen_name" != '' 
ORDER BY "RAND" LIMIT 100

but i want "ORDER BY RAND()"

Am i doing it wrong?

**Comment by jasonlav** [comment]
This solution does not work with the latest version of medoo.

**Comment by hlo2109** [comment]
Esto es para la última versión la dejo aquí para seguir el hilo

'ORDER' => Medoo::raw('RAND()')

Si tienen una clase y dentro incluye su base de datos seria algo asi 
'ORDER' => $this->db->raw('RAND()')

https://medoo.in/api/raw
