### ISSUE TITLE
Special columns

### ISSUE THREAD

**Issue by carlosmellado** [catfan/Medoo#136]
Hi,
I've been looking the documentation in medoo.in and I haven't found nothing about doing select with special columns like COUNT(), SUM(), etc...
Not to count lines in a returned query, I'm talking to doing queries like:

SELECT count(`thing`), `thing2` FROM `table` GROUP BY `thing2` ORDER BY `thing`;

I think it's a basic query...

There is any way to do this?

thank you!

**Comment by Wikunia** [comment]
+1 I would like to have these queries as well and it's really bad that there is no answer to this questions for half a year :/

**Comment by bars38** [comment]
+1 vote for such a query

**Comment by iyaozhen** [comment]
+1 vote

**Comment by shdinx** [comment]
+1

**Comment by richardaum** [comment]
+1

**Comment by CodeBrauer** [comment]
+1

**Comment by akahen** [comment]
Select account, sum(amount) from table group by account is what I'm looking for
+1

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
