### ISSUE TITLE
Bug in where clause, when "LIKE" and "AND"/"OR"

### ISSUE THREAD

**Issue by carlosmellado** [catfan/Medoo#137]
There is no way to do WHERE clause filtering by this way.

$where=array("OR"=>array("user_id"=> "1","LIKE"=>array("name"=>"a")));
returns
SELECT * FROM user_meletes WHERE user_id = '1' OR "LIKE" IN ('a')

Is there any way to do this?

Thanks

**Comment by catfan** [comment]
Improve since 0.9.8 http://medoo.in/api/where
