### ISSUE TITLE
query("SELECT ...")->fetchAll() returns rows twice

### ISSUE THREAD

**Issue by Strosch** [catfan/Medoo#139]
Hi guys!

First off: Awesome lil framework you've got there! :-)

Unfortunately I don't know if this bug was already reported so here it is:
Running a complicated SELECT query via $database->query() and then doing fetchAll() returns all rows twice.

Something like that:
```
row: id val: 357
row: data val: 'foobar'
```
would give the following array:
```
array('id' => 357, 0 => 357, 'data' => 'foobar', 1 => 'foobar')
```

Any ideas on this?

cheers, P

**Comment by BurakBoz** [comment]
use PDO::ATTR_DEFAULT_FETCH_MODE on connection.

```
new Medoo([
                'database_type' => 'mysql',
                'charset'       => 'utf8mb4',
                'collation'     => 'utf8mb4_general_ci',
                'option'        => [PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC]
            ]);

```
