### ISSUE TITLE
STOP minification

### ISSUE THREAD

**Issue by aequasi** [catfan/Medoo#142]
Theres really no point to doing it, and the size of the project really isn't a big deal at all. As none of this code gets transferred to the client, theres no bandwidth issue.

**Comment by aequasi** [comment]
Bump.

**Comment by GaryJones** [comment]
I think this can be closed?

**Comment by aequasi** [comment]
Its still being minified

**Comment by GaryJones** [comment]
I must be missing it - where is it minified?

**Comment by aequasi** [comment]
http://medoo.in/download

**Comment by aequasi** [comment]
No links to minification on the main page, or in source control. Closing this issue
