### ISSUE TITLE
API insert return 0 even the insert execute success

### ISSUE THREAD

**Issue by vanjor** [catfan/Medoo#154]
My table has a A composite key which used as the primary key. such as:
 PRIMARY KEY (`kw`,`date`),

execute insert api , the data is successfully loaded into db, but it still return 0, which can not identify whether the sql is execute successful.
while using  alternative  error() to detect is to fuzzy

**Comment by Jervelund** [comment]
Depending on how the primary key is composed, I don't think it can be done consistently in an easy way:
http://stackoverflow.com/questions/7187690/mysqlphp-getting-last-id-of-multiple-composite-primary-key

**Comment by vanjor** [comment]
Thanks,
for API insert, some concerns the insert item key id,  while some others concerns the insert execute successfully.
As it to me, I think checking insert  execute successfully is more important as a fundamental require for db persistence API. 

To solve this problem, My way is add a new method: (which only copy insert() and change two lines )
public function insert_with_status_check($table, $datas)
	{
		$lastId = array();

		// Check indexed or associative array
		if (!isset($datas[0]))
		{
			$datas = array($datas);
		}

		foreach ($datas as $data)
		{
			$keys = array_keys($data);
			$values = array();
			$columns = array();

			foreach ($data as $key => $value)
			{
				array_push($columns, $this->column_quote($key));

				switch (gettype($value))
				{
					case 'NULL':
						$values[] = 'NULL';
						break;

					case 'array':
						preg_match("/\(JSON\)\s*([\w]+)/i", $key, $column_match);

						if (isset($column_match[0]))
						{
							$values[] = $this->quote(json_encode($value));
						}
						else
						{
							$values[] = $this->quote(serialize($value));
						}
						break;

					case 'boolean':
						$values[] = ($value ? '1' : '0');
						break;

					case 'integer':
					case 'double':
					case 'string':
						$values[] = $this->fn_quote($key, $value);
						break;
				}
			}
                        
                        // return effect records
			$rs = $this->exec('INSERT INTO "' . $table . '" (' . implode(', ', $columns) . ') VALUES (' . implode($values, ', ') . ')');

			$lastId[] = $rs;
		}

		return count($lastId) > 1 ? $lastId : $lastId[ 0 ];
	}

**Comment by verybigelephants** [comment]
i would like to address this issue once more. even if you didn't get the latest inserted id, you could at least get a **true** on the successful insert. it is truly difficult to detect errors right now

**Comment by Jervelund** [comment]
Can you use `$dbh->error()` ?
http://medoo.in/api/error

This should do the trick:
```
if($dbh->error()[1])
  die('database error');
```
