### ISSUE TITLE
Return an error if update/insert is in error

### ISSUE THREAD

**Issue by DEK4** [catfan/Medoo#160]
Is there any way to get an -1 return if the update is in error?

thanks

**Comment by numediaweb** [comment]
medo error returns always an array!

**Comment by numediaweb** [comment]
Currently, to check for errors, I use
```
    /**
     * Helper funtion to check if error is on the last DB error
     * @return bool
     */
    public static function isError()
    {
        $db = self::getInstance();
        $lastError = $db->error();
        return (isset($lastError[2]) && $lastError[2]) ? true : false;
    }
```

Would be great to have this helper function inside the library.
Related issues; [281](https://github.com/catfan/Medoo/issues/281),  [151](https://github.com/catfan/Medoo/issues/151)

**Comment by pixelpaulaus** [comment]
i have been noticing that the returned insertid is sometimes returned even tho a record is not there when i check my database table. and no error is returned either. Makes it very anoying, as only way to check if it REALLY was inserted is to query the table after the insert.

**Comment by lfxc** [comment]
i have noticed the same.   insert is not capturing errors.  In my case the error that was supposed to have been captured is a foreign key constraint being violated

**Comment by lfxc** [comment]
I found out why it wasn't throwing an error for me.  You have to do the following after creating you medoo db object in order for insert errors to be thrown:

$db->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
