### ISSUE TITLE
Distinct

### ISSUE THREAD

**Issue by Supme** [catfan/Medoo#173]
SELECT DISTINCT name FROM table
How to perform a select?

**Comment by callumb** [comment]
I would like to know as well. thanks!

**Comment by SyuTingSong** [comment]
#235 provides a non-official implement or just call

    $medoo->query('SELECT DISTINCT "name" FROM "table"');

**Comment by wangxiaolong100** [comment]
From v1.5 use
`$medoo->select('table', ['name' => Medoo::raw('DISTINCT(name)')])`
