### ISSUE TITLE
Error count row affected on delete mysql

### ISSUE THREAD

**Issue by valix85** [catfan/Medoo#174]
When i delete n rows medoo return always 1, not a number of row deleted.
i use mySql anche the query is:
$db->delete("intervento_componenti", ["id_i"=>$id]);

i have n rows, but return always 1 and in db all n row have been affeceted.

resolve it

**Comment by webtsp** [comment]
I also encountered the same problem, I do not know the solution

**Comment by catfan** [comment]
Check out https://medoo.in/api/delete
