### ISSUE TITLE
unable to connect sybase

### ISSUE THREAD

**Issue by gantoday** [catfan/Medoo#180]
could not find php_pdo_dblib in php.ini
and wamp say:
Fatal error: Uncaught exception 'Exception' with message 'could not find driver' in F:\wamp\www\medoo.php on line 125
Exception: could not find driver in F:\wamp\www\medoo.php on line 125

please help me. thanks!

**Comment by catfan** [comment]
So, you have to install or compile the `php_pdo_dblib` driver for PHP to load.

**Comment by gantoo** [comment]
@catfan thinks!
sorry,but i don't know how to compile the php_pdo_dblib driver for PHP and i google with no answer.could you give me some tips.

**Comment by gantoo** [comment]
and my web server is centos
