### ISSUE TITLE
In LIKE query does not add the % character

### ISSUE THREAD

**Issue by zlababa** [catfan/Medoo#184]
if "LIKE" string shorter than 3 chars, does not add the % character

Problem is in regular expression /^[^%].+[^%]$/ on line 320 in file medoo.php (v0.9.7)

"sfd".match(/^[^%].+[^%]$/) 
return ["sfd"]

"fd".match(/^[^%].+[^%]$/) 
return  null

**Comment by catfan** [comment]
Fixed it.

**Comment by zlababa** [comment]
thx :)
