### ISSUE TITLE
increase performance server

### ISSUE THREAD

**Issue by misaf** [catfan/Medoo#186]
hi, why when i using Medoo for Connection to MYSQL, this class increase RAM usage ?

for example with mysqli connection my server using 350 MB ram but when i using Medo i see 650~700 MB RAM usage.

thanks

**Comment by catfan** [comment]
You may try this attribute: https://coderwall.com/p/k5qauw/running-out-of-memory-with-pdo-php

**Comment by misaf** [comment]
how can i use this on medoo class ?
$database=new medoo(
	[
		'database_type'=>'mysql',
		'database_name'=>DB_NAME,
		'server'=>DB_HOST,
		'username'=>DB_USER,
		'password'=>DB_PASS,
		// optional
		'port'=>DB_PORT,
		'charset'=>DB_CHARSET,
		// driver_option for connection, read more from http://www.php.net/manual/en/pdo.setattribute.php
		'option'=>[PDO::ATTR_CASE => PDO::CASE_NATURAL]
	]
);

i used above code for connecting...

**Comment by catfan** [comment]
'option' => [
	PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false
]

**Comment by misaf** [comment]
i should replace this code with older section ?
replace above code wit this ?
 'option'=>[PDO::ATTR_CASE => PDO::CASE_NATURAL]

**Comment by catfan** [comment]
@misaf No. You can add any attribute option if you needed, or provide nothing. It's up to you.

**Comment by misaf** [comment]
ok, this means i should add below code on my file?

'option' => [PDO::ATTR_CASE => PDO::CASE_NATURAL],
'option' => [PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false]

**Comment by catfan** [comment]
....No, option is an array with PDO options. It's optional. Just add if you really needed.

```
'option' => [
	PDO::ATTR_CASE => PDO::CASE_NATURAL,
	PDO::MYSQL_ATTR_USE_BUFFERED_QUERY => false
]
```
