### ISSUE TITLE
MYSQL Functions

### ISSUE THREAD

**Issue by yozel** [catfan/Medoo#19]
Hi (sorry for my english)

I have used salt for my user passwords. So, I should use mysql MD5 function like this: 

...WHERE MD5(concat('$_POST['password']',salt))=password

How can i do this ? I think I can use the query() function but probably this cause sql injection.

Can you help me ?

**Comment by creativelifeform** [comment]
Yep, I'm currently using medoo in a small twitter app related project and I'm liking it, but I'm also wondering about using MySQL methods like NOW() because they are pretty essential.
