### ISSUE TITLE
GROUP BY mutiple columns

### ISSUE THREAD

**Issue by mrsoto** [catfan/Medoo#191]
The group by only support 1 column, array desired .

**Comment by catfan** [comment]
It's now supported.

**Comment by mrsoto** [comment]
Pull request #190 is probably supported too.
Actually I moved to respect relational. This project look to be abandoned

**Comment by sebam91** [comment]
In version 1.2.1, multiple GROUP BY is still not working for me. Still getting the following error:

> expects parameter 2 to be string, array given

**Comment by mrsoto** [comment]
As far as I understand you have to fork this repo because it only support
owner projects' requirements

**Comment by catfan** [comment]
@sebam91 Oh, sorry. I mixed this issue up with ORDER by.

It's added on develop branch now, and will be release soon. 8c796f48eb
