### ISSUE TITLE
Support aggregate functions in select clause

### ISSUE THREAD

**Issue by mrsoto** [catfan/Medoo#192]
Select clause only support columns aliased or not but doesn't support aggregate functions in conjunction with group by clause

**Comment by phil294** [comment]
+1

**Comment by fmieres** [comment]
+1

**Comment by germansokolov13** [comment]
It's possible to write a simple string to the columns parameter of the `select` function. But if I write sum or avg in there Medoo breaks it for some reason. No complicated query can be written with this library. I am so disappointed.

**Comment by catfan** [comment]
@germansokolov13 It's possible on next version https://github.com/catfan/Medoo/issues/635

**Comment by germansokolov13** [comment]
This is great news! I could also use `query` with full SQL statement but then I don't know how to pass an array of ids to the `IN ()` expression of the `WHERE` sentence. Maybe I could work around this?

**Comment by catfan** [comment]
It's now released.

https://medoo.in/api/raw
