### ISSUE TITLE
noSQL support

### ISSUE THREAD

**Issue by HudsonNicoletti** [catfan/Medoo#196]
Would be nice to have support to mongodb or other nosql databases

**Comment by jiaxunjiaxun** [comment]
Medoo is based on PDO. Why NoSQL? And if it supports NoSQL, it will be re-designed.

**Comment by 3zzy** [comment]
+1

**Comment by filisko** [comment]
Adding NoSQL support will increase the amount of code significantly, instead use some of the following... [NoSQL libraries](https://github.com/ziadoz/awesome-php#nosql)

Cheers! :+1:
