### ISSUE TITLE
How to construct such SQL？

### ISSUE THREAD

**Issue by xuebingwang** [catfan/Medoo#198]
eg：
SELECT
	*
FROM
	tablea
LEFT JOIN tableb b ON tablea.field1 = b.field1
LEFT JOIN tablec c ON b.field2 = c.field2

php code：
$join['[>]tableb (b)'] = array('field1'=>'field1');
$join['[>]tablec (c)'] = array('field2'=>'field2');

**Comment by Jervelund** [comment]
Did you read the chapter on Table Joining under Select in the documentation?
http://medoo.in/api/select

**Comment by Wikunia** [comment]
@Jervelund I have the same problem and I don't know how to join tables which aren't directly connected to the first `FROM` table.
My code:
```
$datas = $database->select("Tags", [
		"[><]ID_Links_Tags" => ["id" => "tag"],
		"[><]Links" => ["ID_Links_Tags.link"=>"id"]
	], [
		"Links.link",
	], [
		"Tags.tag"=>"NodeJS"
	]);
```

That generates this query:
```
SELECT "Links"."link" FROM "Tags" INNER JOIN "ID_Links_Tags" ON "Tags"."id" = "ID_Links_Tags"."tag" INNER JOIN "Links" ON "Tags"."ID_Links_Tags.link" = "Links"."id" WHERE "Tags"."tag" = 'NodeJS' 
```
Where you have to delete all the `"` 
```
SELECT Links.link FROM Tags INNER JOIN ID_Links_Tags ON Tags.id = ID_Links_Tags.tag INNER JOIN Links ON Tags.ID_Links_Tags.link = Links.id WHERE Tags.tag = 'NodeJS'
```
The problem is `Tags.ID_Links_Tags.link` which should be `ID_Links_Tags.link`.

Is there a way using Medoo to such queries? Should be really easy to implement.

**Comment by Jervelund** [comment]
Could you join it as the following? 

    $datas = $database->select("ID_Links_Tags", [
        "[><]Tags" => ...,
        "[><]Links" => ...
    ], [
        "Links.link",
    ], [
        "Tags.tag"=>"NodeJS"
    ]);

**Comment by Wikunia** [comment]
Maybe but that doesn't solve the problem with more than 3 tables

**Comment by xuebingwang** [comment]
Thanks for all your help!

**Comment by xuebingwang** [comment]
https://github.com/Wikunia/Medoo/commit/127fa545d7c88463da7ee004ac051d3592734814
