### ISSUE TITLE
ON DUPLICATE KEY UPDATE

### ISSUE THREAD

**Issue by PiJoules** [catfan/Medoo#199]
Is there ay way when I insert new values into columns that I can update the values for one of the rows if a duplicate value exists for a unique column.

I essentially want to do
`insert into myTable (col1, col2) values ('newVal1', 'newVal2') on duplicate key update col1='newVal1'`
(where `col1` has a `unique` constraint) using Medoo.

Is there any way I can do this?

Thanks in advance.

**Comment by catfan** [comment]
Well, you cannot do this via Medoo. This feature is only for MySQL, and not a standard SQL syntax.

Perhaps you can use `query()` or `pdo->prepare()` to do this specially.

**Comment by PiJoules** [comment]
M'kay

**Comment by nantes123** [comment]
`public function insertOrUpdate($table,$data,$where){
        if($this->has($table,$where)){
            $this->update($table,$data,$where);
        } else {
            $this->insert($table,$data);
        }
    }`

**Comment by marki555** [comment]
> public function insertOrUpdate($table,$data,$where){ if($this->has($table,$where)){ return $this->update($table,$data,$where); } else { return $this->insert($table,$data); } }

This approach has a race condition if not done inside an isolated transaction.
