### ISSUE TITLE
Debugging doesn't work properly

### ISSUE THREAD

**Issue by ghost** [catfan/Medoo#210]
I've tested this several times but I think something is wrong with Medoo.
In my project I use Medoo through a controller project. I use Medoo in each page so I can update the 'stats' column in a table. After that I try saving some other stuff using Jquery AJAX again using Medoo. While trying to debug Medoo in the ajax php file, I get the first query which was used to select data for 'stats'.
Log doesn't work too. Of course it didn't work when I was trying to dump it from ajax file.
If you need to see the code, this is the [repository](https://github.com/MahdiPOnline/Librario). Stats updates in **/templates/article.php** and ajax file is **/includes/save-data.php**. Controller class is located in **/includes/functions.php**.

**Comment by catfan** [comment]
How do you debug for that?

Have you tried this? http://medoo.in/api/debug

**Comment by MahdiPOnline** [comment]
Exactly like what's descripted
