### ISSUE TITLE
Combining MATCH and or

### ISSUE THREAD

**Issue by Wikunia** [catfan/Medoo#212]
Is there any way to combine "MATCH" and "OR"?
Sth like:

```
$where["OR"] = [
            "MATCH"=>  [
                "columns" => ['title','description'],
                "keyword" => 'word',
            ],
            ["link[~]"=>"word"]
]
```

**Comment by Jervelund** [comment]
What are you trying to match?

    ((columns and keywords) or link)

or

    (columns or keywords or link)

**Comment by Wikunia** [comment]
Well match against uses columns and keywords so they are combined in `MATCH`.  Now I want to create a SQL statement like :
`select a from tbl where Match(col1) against ('val1') or col2 = 'val1'`

**Comment by catfan** [comment]
Well, the `MATCH` is actually under consideration to be redesigned like `LIKE -> [~]` does. I'm thinking of its syntax.
