### ISSUE TITLE
HAVING COUNT(id) = ? is that kind of combination possible with medoo?

### ISSUE THREAD

**Issue by istals** [catfan/Medoo#213]
I tried different variations to get right query, but with no success.

```
SELECT x.id, y.t_id, y.x_id    FROM x LEFT JOIN y ON x.id = y.t_id 
WHERE y.t_id IN (1, 2)
GROUP BY x.id
HAVING COUNT( y.t_id ) = 2
```

this is query what I'am trying to get with medoo,
is that possible?

**Comment by VeeeneX** [comment]
I think It's not possible in this version, I had had the same problem

**Comment by catfan** [comment]
That's can be possible via raw object: https://medoo.in/api/raw
