### ISSUE TITLE
can't insert data to table

### ISSUE THREAD

**Issue by Holy015** [catfan/Medoo#214]
there is no error in my codes but it can't insert

here is my code

<?php
require_once 'init.php';
if(isset($_POST['addstud'])){
	if(isset($_REQUEST['cn'])){
		$cn = $_REQUEST['cn'];
		$lname = $_REQUEST['lname'];
		$fname	= $_REQUEST['fname'];
		$mname = $_REQUEST['mname'];
		$gender = $_REQUEST['gender'];
		$course	= $_REQUEST['course'];
		$bmonth = $_REQUEST['bmonth'];
		$bday = $_REQUEST['bday'];
		$byear = $_REQUEST['byear'];
		$bplace	= $_REQUEST['bplace'];
		$ctizen	= $_REQUEST['ctizen'];
		$eadd = $_REQUEST['eadd'];
		$pschool = $_REQUEST['pschool'];
		$ischool = $_REQUEST['ischool'];
		$sschool = $_REQUEST['sschool'];
		$addr = $_REQUEST['addr'];
		$fatname = $_REQUEST['fatname'];
		$motname = $_REQUEST['motname'];
		$yenroll = $_REQUEST['yenroll'];
		$stat = $_REQUEST['stat'];

		//$SID = $course.$gender.$cn.$yenroll;
		$bdate = $bmonth."-".$bday."-".$byear;

		$profile = $DB->insert('profile', [
			'cn' => $cn,
			'lname' => $lname,
			'fname' => $fname,
			'mname' => $mname,
			'gender' => $gender,
			'course' => $course,
			'bdate' => $bdate,
			'bplace' => $bplace,
			'ctizen' => $ctizen,
			'eadd' => $eadd,
			'pschool' => $pschool,
			'ischool' => $ischool,
			'sschool' => $sschool,
			'addr' => $addr,
			'fatname' => $fatname,
			'motname' => $motname,
			'yenroll' => $yenroll,
			'stat' => $stat
		]);
		
	}
}
?>

**Comment by Jervelund** [comment]
What are the values of your variables?

You could try to look at your data, to see if it matches your schema, by using:

    var_dump([
        'cn' => $cn,
        'lname' => $lname,
        'fname' => $fname,
        'mname' => $mname,
        'gender' => $gender,
        'course' => $course,
        'bdate' => $bdate,
        'bplace' => $bplace,
        'ctizen' => $ctizen,
        'eadd' => $eadd,
        'pschool' => $pschool,
        'ischool' => $ischool,
        'sschool' => $sschool,
        'addr' => $addr,
        'fatname' => $fatname,
        'motname' => $motname,
        'yenroll' => $yenroll,
        'stat' => $stat
    ]);

**Comment by alexantr** [comment]
Maybe quotes around tablename in final SQL-query do not working on that server?
```sql
INSERT INTO "sometable" VALUES ()
```

**Comment by whatacold** [comment]
you could print out the final medoo-constructed sql like this:

	$profile = $DB->insert('profile', ...);
	echo $DB->last_query();

then you should find out what's wrong in the sql statement, and so the insert array.

**Comment by chaegumi** [comment]
' maybe "

**Comment by manulaiko** [comment]
Did you tried printing the error?

    var_dump($DB->error());

**Comment by chaegumi** [comment]
no,i didn't.

ps:
$this->query('select * from table1 where filed="' . $val . '"')->fetch(PDO::FETCH_ASSOC);    // is error
$this->query("select * from table1 where field='"  . $val . "'")->fetch(PDO::FETCH_ASSOC); // is correct
