### ISSUE TITLE
add BINARY ability in columns 

### ISSUE THREAD

**Issue by almakano** [catfan/Medoo#217]
when searching "HelLo" and "hello" - result is same. BINARY word behind column name can be case sensitive:
SELECT  BINARY `a` FROM b WHERE a LIKE '~%HelLo%~'

**Comment by rkkoszewski** [comment]
Any news about this? I'm in the same situation.

**Comment by mengdodo** [comment]
wtf,when i use left join to select infomations, this issues make me wrong!
