### ISSUE TITLE
AND + ORDER BY + LIMIT combination possible?

### ISSUE THREAD

**Issue by FileMana** [catfan/Medoo#219]
Hello,
Is it possible to have AND + ORDER BY and LIMIT in 1 statement with medoo?
SQL Statement:
SELECT * FROM table WHERE c1 = 1 AND c2 != 2 AND c3 > 0 ORDER BY c4 LIMIT 0, 20
My codes:
$sql->select('table', *, [
				'AND'=> [
					'c1' => 1,
					'c2[!]' => 2,
					'c3[>]'=>0
				],
				'LIMIT'=> [0, 20],
				'ORDER'=>'c4 DESC'
			]);
but when i call $sql->last_query() the LIMIT part is missing.
last_query() output:
SELECT * FROM "table" WHERE "c1" = 1 AND "c2" != 0 AND "c3" > 0 ORDER BY "c4" DESC

help please!!!

**Comment by VeeeneX** [comment]
Yes, It's possible

**Comment by FileMana** [comment]
how??? my codes do not work...

**Comment by VeeeneX** [comment]
```php
$sql->select('table', "*", [ // Missing "
'AND' => [
'c1' => 1,
'c2[!]' => 2,
'c3[>]' => 0
],
'LIMIT'=> [0, 20],
'ORDER' => ['c4 DESC']
]);
```

**Comment by FileMana** [comment]
yea, i tried that as well... The quote was missing when i copy it over.

last_query() on your select statement doesnt show the LIMIT part
SELECT * FROM "table" WHERE "c1" = 1 AND "c2" != 0 AND "c3" > 0 ORDER BY "c4" DESC
