### ISSUE TITLE
Doesn't support NULL as parameter

### ISSUE THREAD

**Issue by b3bb0** [catfan/Medoo#221]
When inserting eve if use:
 '#fieldname' = NULL 
or
 '#fieldname' = 'NULL'
or
 'fieldname' = NULL 
or
 'fieldname' = 'NULL'

it always insert the string 'NULL' and not the NULL value.

**Comment by iyaozhen** [comment]
If field ```DEFAULT NULL```
I think you should not set this field, when you insert.
