### ISSUE TITLE
WHERE doesn't have an option for case insensitive, lower or uppercase

### ISSUE THREAD

**Issue by AdrianVerde** [catfan/Medoo#225]
An option that can get the same results as a query like
```SELECT mail FROM users WHERE LOWER(`mail`) = 'user@domain.tld';```
through $medoo->has, get or select would be great :D

**Comment by catfan** [comment]
The better way is using PHP native function to do that.

**Comment by AdrianVerde** [comment]
Yeah, and/or using case insensitive collaton in the database, already did, thanks.
