### ISSUE TITLE
Fetch errors for Multi-Insertion

### ISSUE THREAD

**Issue by shdinx** [catfan/Medoo#227]
In the version 0.9.8.2 the method $medoo->error() returns PDO::errorInfo();
PDO::errorInfo — Fetch extended error information associated with the last operation on the database handle

If insert1 and 2 are wrong in the following multi insert example, I will not be able to fetch the error of insert1:
    $medoo->insert( table, [insert1],[insert2],[insert3] )
    print_r($medoo->error());

This will only return the last error and save it as long as a new error occur.

Can you give me an example how to fetch insert errors in general as well as fetching errors within a multi insert? I cannot see anything in your source code reflecting this proper.

$medoo->insert();
$medoo->error(); 
This is not a practical solution.

**Comment by catfan** [comment]
The data of multi-insertion is:

```php
$medoo->insert( table, [insert1, insert2, insert3] )

$database->insert("account", [
	[
		"user_name" => "foo",
		"email" => "foo@bar.com",
	],
	[
		"user_name" => "bar",
		"email" => "bar@foo.com",
	]
]);
```

Just read more about the documentation.

**Comment by catfan** [comment]
Multi-insertion will execute only one query on Medoo 1.2.
