### ISSUE TITLE
AND within JOIN

### ISSUE THREAD

**Issue by annoyingmouse** [catfan/Medoo#234]
Hi there, not so much an issue as a query. I've the following SQL which works but I was wondering how to do the same in Medoo:

        SELECT
            users_temp.*,
            c1.name,
            c1.date
        FROM
            users_temp
        INNER JOIN
            courses_temp c1
        ON
            users_temp.id = c1.user_id
        LEFT JOIN
            courses_temp c2
        ON
            users_temp.id = c2.user_id
        AND
            c1.date < c2.date
        WHERE
            c2.date IS NULL
        AND
            c1.date < now() - interval 2 year;

I've tried this:

    $db->select(
        'users_temp',
        array(
            '[><]courses_temp(c1)' => array(
                'users_temp.id' => "c1.user_id"
            ),
            '[>]courses_temp(c2)' => array(
                "AND" => array(
                    'users_temp.id' => 'c2.user_id',
                    'c1.date' => 'c2.date'
                )
            )
        ),
        array(
            'users_temp.*',
            'c1.name',
            'c1.date'
        ),
        array(
            'AND' => array(
                'c2.date' => null,
                'c1.date[<]' => date('Y-m-d', strtotime('-2 year'))
            )
        )
    );

But the output is always false. I've tried removing the **AND** but that doesn't help either. What am I doing wrong?

**Comment by catfan** [comment]
There is no alias supported for table joining yet.

**Comment by annoyingmouse** [comment]
Ahh, okay. Thank you anyway - I did think that might be the case but wanted to check I wasn't being dense! Thank you.
