### ISSUE TITLE
Error if WHERE IN column start with or OR and

### ISSUE THREAD

**Issue by 4t0m1k** [catfan/Medoo#236]
Hi,

This query does not work :

$database->select('orders', array(
    'order_date'
), array(
    'order_id' => array(1, 2)
));

because order_id begins with 'or'.

The query should be : SELECT order_date FROM orders WHERE order_id IN (1, 2)
But actually, this is : SELECT order_date FROM orders WHERE (() ())

Workaround : 

replace line 268 : /^(AND|OR)\s*#?/i
with : /^(AND|OR)\s*(#.*)?$/i

Sorry for my bad english.

**Comment by catfan** [comment]
Fixed it on develop branch. #229
