### ISSUE TITLE
Warning: PDO::getAttribute(): SQLSTATE[IM001]: Driver does not support this function: driver does not support that attribute in medoo.php on line 944

### ISSUE THREAD

**Issue by quantuumsnot** [catfan/Medoo#241]
Title speaks for itself ... Using $database->getinfo() prints this ...

Btw it's weird why I can't insert anything. No errors, no nothing, everything is ok in my script, but nothing is inserted ... Using the examples:
$database = new medoo(['database_type' => 'sqlite', 'database_name' => 'test.db']);
$database->insert('metrics', [
    'date' => $res['date'], //Current date
    'function' => $res['function'], //Function name
    'steps' => $res['steps'], //Steps passed
    'time' => $res['time'], //Time taken
    'memory' => $res['memory'] //Memory used
  ]);

**Comment by quantuumsnot** [comment]
Nope ... just nope. The library continuously reports 'No such table' while it exists. Falling back to good old PDO prepared statements

**Comment by tttlh** [comment]
you should use 'database_file' instead of 'database_name' for sqlite
