### ISSUE TITLE
bug in medoo build query

### ISSUE THREAD

**Issue by Drive4ik** [catfan/Medoo#246]
Hello everyone!
I has a bug with build query, example
```php
$time = time();

self::$db->debug()->update('realty', [
	'preview_image' => 'some hash',
	'last-update-date' => $time
], [
	'AND' => [
		'user_id' => 1,
		'realty_number' => 1,
		'last-update-date[!]' => $time
	],
	'LIMIT' => 1
]);
```
this call has wrong query result:
```sql
UPDATE "realty" SET "preview_image" = 'some hash', "last-update-date" = '1432049999' WHERE "user_id" = 1 AND "realty_number" = 1 AND "last" = 1432049999 LIMIT 1
```

medoo I really like, but I found an another bug:
the medoo builded query
```sql
SELECT "preview_image" FROM "realty" WHERE "user_id" = 1 AND "realty_number" = 1 LIMIT 1
```

has error "#1064 - You have an error in your SQL syntax;"
because need replace double quote to reverse single quote - "`"
example:
```sql
SELECT `preview_image` FROM `realty` WHERE `user_id` = 1 AND `name` = 'first name' LIMIT 1
```
this query works fine

I really hope to help
I like Medoo, and I would not want to give it up!
God work!

**Comment by Drive4ik** [comment]
Hello! Very quickly fix! Thanks!
What about replace double quote for sql column?
```sql
SELECT "preview_image" FROM "realty" ...
```
to
```sql
SELECT `preview_image` FROM `realty` ...
```

**Comment by catfan** [comment]
@Drive4ik This is not a bug. Medoo is using standard SQL quote to be compatible for other SQL database. You can notice that we set `SET SQL_MODE=ANSI_QUOTES` for MySQL in initialization.

And why you execute the Medoo generated query alone, while Medoo can generate and execute itself correctly?

**Comment by Drive4ik** [comment]
Maybe, you misunderstood me.
I use the power of Medoo to maximum, and i like it.
Thanks for explanation for `SET SQL_MODE=ANSI_QUOTES`, i see this code.
Sorry, my english is bad..

Regards, @Drive4ik
