### ISSUE TITLE
ODBC support?

### ISSUE THREAD

**Issue by GaryJones** [catfan/Medoo#247]
Just been recommended Medoo for a project, but I'm looking for ODBC support via the PDO_ODBC driver. I can see that other PDO drivers are present, but not `new PDO( 'odbc:...', ... )`. Is it possible to add this support please?

**Comment by catfan** [comment]
It's now supported on Medoo 1.2.

**Comment by Forsakenfx** [comment]
You said that ODBC is supported, but I went through commit history and have seen nothing that shows support for it or any documentation.

**Comment by catfan** [comment]
@Forsakenfx You can use customized DSN to connect any kind of database.

https://medoo.in/api/new
