### ISSUE TITLE
CONCAT?

### ISSUE THREAD

**Issue by zlababa** [catfan/Medoo#256]
Hi, is possible use CONCAT, or if not, It could be possible to add?

for example SQL: SELECT column1, column2, CONCAT(column1, column2) as column3 FROM table...

something like:
$data = $database->select("table", [
    "column1",
    "column2",
        "#CONCAT[column1,column2] (column3)"
],[]);

Thanks for your great framework

Zlababa

**Comment by beckybeq** [comment]
use query http://medoo.in/api/query

**Comment by coosir** [comment]
see https://github.com/catfan/Medoo/pull/260

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
