### ISSUE TITLE
cache mechanism to prevent duplicate select queries in process

### ISSUE THREAD

**Issue by felipegabriel** [catfan/Medoo#258]
would this be possible?

**Comment by shdinx** [comment]
Not build in but I use http://www.phpfastcache.com/ in combination with medoo.

**Comment by ikandars** [comment]
Yes this possible.
1. Add new static class property
```
class medoo {
private static $cache = [];
}
```
2. Add view line of code in query method:
```
public function query($query)
	{
		if ($this->debug_mode)
		{
			echo $query;

			$this->debug_mode = false;

			return false;
		}
		
		$cacheKey = md5($query);
		
		if( isset(self::$cache[$cacheKey]) )
            return self::$cache[$cacheKey];

		array_push($this->logs, $query);

		return self::$cache[$cacheKey] = $this->pdo->query($query);
	}
```

I can PR's for this issue. So what do you think @catfan?

**Comment by manulaiko** [comment]
@ikandars The idea is nice if you suppose that the script is the only thing that interacts with the server. If there's any other thing that can change the database the returned values might be outdated.
Let me explain this, I'm working on a browser game that has 2 fundamental parts: The website and the Server.
Both of them interacts with the database, if the cached query result in medoo is the same the returned value wouldn't change when the server updates the database.

A possible fix for this is to store in the cache array a parameter that indicates when to update the result, something like this:

    public function query($query)
    {
        $timestamp = time();
        $expire = $timestamp + (5 * 1000 * 60); //The timestamp when we should renew the cached query (5 minutes, I'm bad at math so it might be wrong)
        
        $key = md5($query);
        
        //Check if the query isn't already in the cache
        if(!isset($this->cache[$key])) {
            //Add a new index to the cache array
            $this->cache[$key] = [
                "expire" => $expire,
                "query"  => $this->pdo->query($query)
            ];
            return $this->cache[$key]["query"];
        }
        
        //Check if the cached query has expired
        if($timestamp >= $this->cache[$key]["expire"]) {
            //update the query
            $this->cache[$key]["expire"] = $expire;
            $this->cache[$key]["query"]  = $this->pdo->query($query);
        }
        
        return $this->cache[$key]["query"];
    }

That might provide a simple fix to the problem of multiple programs accessing same database.

See you!

**Comment by catfan** [comment]
Actually, for most of database system, they have query cache feature also.

https://dev.mysql.com/doc/refman/5.1/en/query-cache.html

And you can use Redis or Memcache system for caching the result for better performance and management.

**Comment by jlamer** [comment]
You can also wrap medoo public functions with your functions and do caching there, see example below ... 

```php
class db
{
        private $medoo;
        public static function get($table, $join = null, $column = null, $where = null)
	{
		if(cached){
			return cache;
		}

		return $this->medoo->get($table, $join, $column, $where);
	}
)
```
