### ISSUE TITLE
[feature] Add action() for database transactions

### ISSUE THREAD

**Issue by catfan** [catfan/Medoo#261]
We currently added a new feature - action() 9fdfb67 on develop branch for using database transactions with more convenient.

With inline action call, all database actions with be automatically committed, and will be rollback if return `false` value inside.

Here is the sample for PHP 5.4+

``` php
$database->action(function ($database)
{
    $database->update('action', [
        'age' => 24
    ], [
        'name' => 'foo'
    ]);

    $database->update('action', [
        'age' => 27
    ], [
        'name' => 'bar'
    ]);

    // Return false to rollback the transactions
    return false;
});
```

Any ideas for this feature?

**Comment by chenbaicheng** [comment]
i have problem on action()  if i use try catch in action()....like:
$actionReturnValue = $pdo->action(function($pdo){
				try{
                                       $this->pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
					 $conditionCheck_1= $pdo->insert($this->table_name,$this->insertArray); 
					if(!$conditionCheck_1){
						throw new PDOException('插入注册用户数据失败 来自userRegisterViewModel');
					}
                                       $conditionCheck1= $pdo->query('CREATE TABLE IF NOT EXISTS  table_name(); ');  
								
					if(!$conditionCheck1){
						throw new PDOException($pdo->last_query());
					}
                              }catch(PDOEXCEPTION $e){}
it can't   rollBack ......the insert date ,still  contain in dataTable....and  create table not rollback  ...how to deal with that problem  thank ^^

**Comment by SyuTingSong** [comment]
@chenbaicheng The `CREATE TABLE` statement cause an implicit commit, as if you had done a `COMMIT` before executing it.

https://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by chenbaicheng** [comment]
@SyuTingSong   thank
