### ISSUE TITLE
date < date

### ISSUE THREAD

**Issue by pixelpaulaus** [catfan/Medoo#268]
why can't i do a simple WHERE 
"expiry[<]" => 'now()'

? i can only see <> or >< work

**Comment by pixelpaulaus** [comment]
and how do you do a ORDER when you are also doing an AND or OR

is it...

    $db_data = $app->db->select("domains", $columns, [
			'AND' => [
			"accountid" => $userid,
			"active" => 1,			
		], 'ORDER' => 'domain']);

or...

    $db_data = $app->db->select("domains", $columns, [
			'AND' => [
			"accountid" => $userid,
			"active" => 1,	
			"ORDER" => 'domain']
		]]);

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
