### ISSUE TITLE
update  use funciton combination  

### ISSUE THREAD

**Issue by tablecell** [catfan/Medoo#269]
``` A
$database->update("account", [

   // "#duetime" => "NOW()"   ok
    "#duetime" =>'DATE_ADD(NOW(),INTERVAL 1 MONTH)'  //fail
], [
    "uid" =>3
]);

echo $database->last_query();
```

UPDATE "account" SET "duetime" = 'DATE_ADD(NOW(),INTERVAL 1 MONTH)' WHERE "uid" = 3

**Comment by tablecell** [comment]
how aboud the syntax  'duetime|RAW' =>'DATE_ADD(NOW(),INTERVAL 1 MONTH)' ?

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
