### ISSUE TITLE
value update (switcher 0/1)

### ISSUE THREAD

**Issue by adminko-svk** [catfan/Medoo#270]
I would like to update the "show" value:
if value is 0 then change to 1
if value is 1 then change to 0

My current code is:

// get the value
$value = $this->db->get($this->table, 'show', [
    'id' => $id
]);

// change the value
$this->db->update($this->table, [
    'show' => 1 - $value,
], [
    'id' => $id
]);

Is this possible with only one update query in medoo?

Thank you

**Comment by manulaiko** [comment]
I didn't test it but it might work, bassically you can treat value as a boolean and then parse it to int, something like this:

    $this->db->update($this->table, [
        'show' => (int)!$value,
    ], [
        'id' => $id
    ]);

Let me know if it worked :)

**Comment by adminko-svk** [comment]
$value is undefined
