### ISSUE TITLE
Using the "Error!"

### ISSUE THREAD

**Issue by sina-mokhtari** [catfan/Medoo#274]
Hello , I use " !$results " to understand the data is added or not but it always writes "Error!" even when the data is added to database completely.
what should I do??
please help me.

$database = new medoo( );

$results=$database->insert( "users" , [
            'user_name' => $user_name ,
            'pass_word' => $pass_word 
        ] );
if(!$results){
      echo "Error!";
}
else{
      echo "The data have inserted successfully!"; 
}

**Comment by catfan** [comment]
insert() is now return the PDOStatement object, you can check out the error on it.
