### ISSUE TITLE
SQL Error on JSON Mode Array Serialization

### ISSUE THREAD

**Issue by ikandars** [catfan/Medoo#275]
Base on Array Serialization doc [http://medoo.in/api/insert](http://medoo.in/api/insert) if we use json:

```
$last_user_id = $database->insert("account", [
	"user_name" => "foo",
	"email" => "foo@bar.com",
	"age" => 25,
	"(JSON) lang" => ["en", "fr", "jp", "cn"]
]);
```

We expected the result in SQL is:
```
INSERT INTO "account" ("user_name", "email", "age", "lang") VALUES ('foo', 'foo@bar.com', '25', '["en","fr","jp","cn"]')
```

But actual result in SQL is:
```
INSERT INTO "account" ("user_name", "email", "age", " lang") VALUES ('foo', 'foo@bar.com', '25', '["en","fr","jp","cn"]')
```
There is a space in "lang" field.

**Comment by catfan** [comment]
Thank for the report :+1:

I fixed it with simpler way.

And follow the contribution guide that submit your code to the develop branch, and start a pull request into it next time :)

**Comment by ikandars** [comment]
Yes, your solution more simpler and sorry for not following the guideline.
