### ISSUE TITLE
Cannot handle error of insert statement

### ISSUE THREAD

**Issue by onur-sahin-de** [catfan/Medoo#281]
Here is an method of my database-class which uses the insert-method of medoo

```
    public function addReferenceProject($getProjectName, $getProjectShortDescription, $getProjectURL, $getProjectMainImageFilename, $getProjectPreviewImageFilename) {

        $autoIncrementReferenceProject = self::getAutoIncrementOfTable(self::REFERENCE_PROJECT_TABLE);

        $referenceProjectInsert = $this->database->insert(self::REFERENCE_PROJECT_TABLE, [
            "reference-project-id" => $autoIncrementReferenceProject,
            "project-name" => $getProjectName,
            "project-short-description" => $getProjectShortDescription,
            "project-url" => $getProjectURL,
            "project-main-image-file-name" => $getProjectMainImageFilename,
            "project-preview-image-file-name" => $getProjectPreviewImageFilename
        ]);

        return $referenceProjectInsert;

    }
```

$referenceProjectInsert always returning the same value... how to check if the insert was successfull or not?

**Comment by manulaiko** [comment]
What about debuggin?
Try this and post the results:

    public function addReferenceProject($getProjectName, $getProjectShortDescription, $getProjectURL, $getProjectMainImageFilename, $getProjectPreviewImageFilename) {
        
        $autoIncrementReferenceProject = self::getAutoIncrementOfTable(self::REFERENCE_PROJECT_TABLE);
        
        $referenceProjectInsert = $this->database->insert(self::REFERENCE_PROJECT_TABLE, [
            "reference-project-id" => $autoIncrementReferenceProject,
            "project-name" => $getProjectName,
            "project-short-description" => $getProjectShortDescription,
            "project-url" => $getProjectURL,
            "project-main-image-file-name" => $getProjectMainImageFilename,
            "project-preview-image-file-name" => $getProjectPreviewImageFilename
        ]);
        
        die("referenceProjectInsert: ". var_dump($referenceProjectInsert ."<br/>Error: ". var_dump($this->database->error()));
        
    }
