### ISSUE TITLE
Can I Use mysql_fetch_array() to Process Array Returned From select()

### ISSUE THREAD

**Issue by frjalex** [catfan/Medoo#282]
Hello,

I am new to using medoo.

This may be a dumb question but it had been troubling me a long time.

So if I use select() to process a mysql request, such as

$myQuery=$db->select("table1","*",["data"=> '1']);

And use 
$row=mysql_fetch_array($myQuery);
echo $row['column'];

as i normally do to output the array, it won't work.

So why and how can I completely use the echo command to output a specific data fetched from an array?

**Comment by catfan** [comment]
Your $myQuery is what you wanted already.

**Comment by frjalex** [comment]
I see. Thank you.
