### ISSUE TITLE
Question and Request: Support for MYSQLI? :)

### ISSUE THREAD

**Issue by mamarilmanson** [catfan/Medoo#284]

**Comment by jlamer** [comment]
But ... why? :)

**Comment by tony0918** [comment]
Prefer to add mysqlnd support because it has been introduced to PHP 5.6 as default native mysql driver.

**Comment by mamarilmanson** [comment]
I was browsing the code and noticed there's just mysql... I'm mostly using mysqli because of news that mysql will be depreciated...

I don't know if this question/request is necessary or am I not aware of what I just said above? :)

**Comment by jlamer** [comment]
Medoo is using PDO objects (you can look it up) and, therefore, is completely fine. Thanks to PDO you can also use it with different database like Microsoft SQL or SQLite. If it used mysqli we would lost that compatibility provided by PDO.

**Comment by mamarilmanson** [comment]
Even with the database that comes along with WAMP and XAMPP? :)

**Comment by jlamer** [comment]
AFAIK xampp and any wamp software comes with mysql or compatible RDBMS like mariadb or percona so it should work without any problem.

I am using medoo on 5 different servers with original mysql 5.5, percona 5.6, mariadb 10 and sqlite 3 and I am absolutely sure you wont face any problems. Happy coding :)

**Comment by mamarilmanson** [comment]
Thank you for the information... :D

**Comment by jlamer** [comment]
Please close the issue if you don't have any more questions.

**Comment by mamarilmanson** [comment]
Yes... Thank you... I apologize... :)
