### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by flexbrane** [catfan/Medoo#288]
Hello,

I've try to do a select (http://medoo.in/api/select).

Exactly like this exemple, but I have "Warning: Invalid argument supplied for foreach()".

Please, how can I fix that ?

Thanks a lot

**Comment by flexbrane** [comment]
With 
https://stackoverflow.com/questions/2630013/invalid-argument-supplied-for-foreach
I suceed to avoid the warning. 

I just add "(array)" :
foreach ((array) $items as $item)

**Comment by catfan** [comment]
That's OK.
