### ISSUE TITLE
Can't find ver 1.0 in composer

### ISSUE THREAD

**Issue by Hatsunyan** [catfan/Medoo#295]
![2015-10-16_03-07-51](https://cloud.githubusercontent.com/assets/7223705/10528951/3c849ef6-73b3-11e5-8dcb-82fb3192dd41.png)
dev-master and dev-develop upload only 0.9.8

**Comment by iyaozhen** [comment]
I have this problem too. Can fix soon ?

**Comment by catfan** [comment]
I have sent a update request for https://packagist.org. It will be available now.

https://packagist.org/packages/catfan/medoo
