### ISSUE TITLE
Table Prefix for query

### ISSUE THREAD

**Issue by mbecker-bemit** [catfan/Medoo#296]
Dear Catfan,

i used some features, but didn't found something for "TRUNCATE TABLE xy".
Then I used 'query', and after analyze this method, I see that there is nowhere the property prefix.
Did I overlook something?
When not:
A method for truncate (MySQL) would be nice.
And if the prefix would be applied to every table that is accessed via the query method, but this could be very complicated (and slow).

a nice day!
michael

**Comment by ramiel** [comment]
Why was this closed? Is there a solution?

**Comment by mbecker-bemit** [comment]
I don't know, have build a wrapper class which extends medoo with things I need.
Could be that truncate is not everywhere possible, etc. Haven't got many experiences beside MySQL.
