### ISSUE TITLE
find_in_set feature

### ISSUE THREAD

**Issue by hooray** [catfan/Medoo#299]
类似的情况在数据库设计的时候经常会出现，应该属于比较实用的一个功能
介绍：http://www.xujiantao.com/archives/221
（抱歉，英文不好，只能留中文）

**Comment by pwwang** [comment]
@hooray Here is the translation:
He wishes to add a function `find_in_set`, which is frequently used in database design and will be useful. Some examples (in Chinese): http://www.xujiantao.com/archives/221

**Comment by hooray** [comment]
@pwwang thanks for translation :)

**Comment by wakerman** [comment]
Whether it is still only use the original SQL(like this: SELECT * FROM xujiantao WHERE FIND_IN_SET(44, game);) statement processing

**Comment by Sky-Gavin** [comment]
Does find_in_set support?

**Comment by ShuiPingYang** [comment]
@pwwang @hooray @Sky-Gavin I solve this problem,I give a pr,https://github.com/catfan/Medoo/pull/909
