### ISSUE TITLE
subtract & addition in where

### ISSUE THREAD

**Issue by mbecker-bemit** [catfan/Medoo#303]
Something like [+] or [-], and other things, would be nice in the where condition.
In some events I need to do this, but didn't find anything in the documentary.
Some example:
$dbmedoo->delete('cookies', [
    'AND' => [
        'expire[!]' => 0,
        '(lastupdate[+]expire)[<]' => microtime(true),
    ],
]);

should make for mysql:
DELETE FROM cookies WHERE expire != 0 AND ((lastupdate+expire) < 1445718226.7132)

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
