### ISSUE TITLE
MySQL query syntax error (double quotes in the wrong places)

### ISSUE THREAD

**Issue by Instagit** [catfan/Medoo#305]
````php
$last_user_id = $db->insert("table", [
        "column1" => "data",
        "column2" => "data",
        "column3" => "data"
]);
````

This code produces the following query:

````mysql
INSERT INTO "table" ("column1", "column2", "column3") VALUES ('data', 'data', 'data');
````
Which throws an SQL syntax error 1064 because of the double quotes around the table and column names.

**Comment by Instagit** [comment]
Sorry, the main problem was a configuration error on my part, but the debug output with wrong quotes doesn't help :wink:

**Comment by heichel** [comment]
@Instagit Can you specify what your configuration error was? We currently get the same SQL error and don't find the problem.
