### ISSUE TITLE
Method get must not return false

### ISSUE THREAD

**Issue by denisbondar** [catfan/Medoo#306]
Method get returns logical false if query has not given results.
But in my opinion it is more correct to returnn null instead logical false.

**Comment by jlamer** [comment]
:+1: but it is kind of late for that, it would break everyone's code. But if it was optional ...

**Comment by SyuTingSong** [comment]
Agree. Can add an option for strict mode or compatible mode.

**Comment by jlamer** [comment]
@SyuTingSong sounds perfect
