### ISSUE TITLE
table prefix is not work for left join

### ISSUE THREAD

**Issue by munggruel** [catfan/Medoo#311]
left join ，you can not Use table prefix

**Comment by munggruel** [comment]
使用连接的时候表名前缀加不上

**Comment by dingdejing** [comment]
我感觉其实medoo没必要吧join查询也放倒框架里，其实涉及到这样的查询，直接自己写原生的sql更方便

**Comment by SyuTingSong** [comment]
I got the same issue. I fixed this bug and create pull-request #316.

Sorry for pushing many times. I split different features into different branches and submit the pull-requests separately.

我遇到同样的问题，已经修复了并提交合并请求 #316 。
抱歉push了好几次，因为想把不同的功能分割到不同的分支上分别提交pull-request给项目组。
