### ISSUE TITLE
Duplicate Data Returned in query() with NOT IN (SELECT *)

### ISSUE THREAD

**Issue by clickbid** [catfan/Medoo#314]
I have a standard query that has a NOT IN (select) but when I print_r($dataAry) it gives me duplicate info (see below). Any ideas?

```
 $dataAry = $db->query("SELECT item_number,item_name,item_type_id 
 FROM items 
 WHERE id 
 NOT IN(
 SELECT items.id AS item_id 
    FROM items 
    JOIN bids ON bids.item_id = items.id 
    WHERE items.user_id = 123
    GROUP BY items.id) 
 AND items.user_id = 123 
 LIMIT 0,6")->fetchAll();
```

My Results print_r($dataAry):

```
    {
        "0": "100",
        "1": "Golden Ticket",
        "2": "3",
        "item_number": "100",
        "item_name": "Golden Ticket",
        "item_type_id": "3"
    }...
```

**Comment by SyuTingSong** [comment]
You can see the implementation of medoo::query() https://github.com/catfan/Medoo/blob/master/medoo.php#L154

Just pass PDO::FETCH_ASSOC to the fetchAll function so you get the associated array.

Or you can pass PDO::FETCH_NUM to the fetchAll function to get the indexed array.

**Comment by vincent-guesnard** [comment]
In case you would like to use objects, here is the solution i use : $this->pdo->query($query, PDO::FETCH_CLASS, 'stdClass');

But, since Syu point compatibility problems, i'm not sure that it's the right way.

**Comment by danilodecanini** [comment]
@clickbid I had the same issue and I did what @SyuTingSong said above and it worked for me.

`
$data = $db->query($query)->fetchAll(PDO::FETCH_ASSOC);
`

Thanks @SyuTingSong
