### ISSUE TITLE
"""error

### ISSUE THREAD

**Issue by wanjunlengfeng** [catfan/Medoo#315]
medoo use:
SELECT * FROM "radacct" WHERE "username" = '454175329@QQ.com' ORDER BY "radacctid" DESC LIMIT 10
 because of  the  field include ‘“’,show error record.

This is the correct sql is:
SELECT "adcb" FROM radacct WHERE username = '454175329@QQ.com' ORDER BY radacctid DESC LIMIT 10

**Comment by SyuTingSong** [comment]
Notice that medoo run `SET SQL_MODE=ANSI_QUOTES` while initializing. [Source Code Line 94](https://github.com/catfan/Medoo/blob/master/medoo.php#L94)

It makes double quotes work for MySQL.

You may probably show your PHP code and the SQL it generates and the error messages if there is any.

**Comment by haowran** [comment]
I have this problem too, my MySQL version is 5.5 :(
