### ISSUE TITLE
REPLACE INTO feature missing in Medoo.

### ISSUE THREAD

**Issue by jezmck** [catfan/Medoo#318]
Note that I am **not** referring to Medoo's [existing `replace` feature](http://medoo.in/api/replace).

MySQL allows `REPLACE INTO` queries which update existing rows or insert new row into the database if matching ones don't exist.

> REPLACE works exactly like INSERT, except that if an old row in the table has the same value as a new row for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the new row is inserted.
> https://dev.mysql.com/doc/refman/5.7/en/replace.html

This is a massively useful feature which could be implemented for non-`MySQL` DBs if required.

Note that I am **not** referring to Medoo's [existing `replace` feature](http://medoo.in/api/replace).

**Comment by SyuTingSong** [comment]
`REPLACE INTO` doesn't work fine with the foreign key constrains since it removes the row with duplicate key and insert new. I've moved to `INSERT ... ON DUPLICATE KEY UPDATE` syntax in MySQL. Poorly such syntax is supported only by MySQL.

**Comment by jezmck** [comment]
Is there documentation on how to use that syntax with Medoo?

**Comment by SyuTingSong** [comment]
It's a MySQL syntax, not supported by other DB. Medoo haven't provide a method to do that, you can call `$medoo->query($sql)` or `$medoo->exec($sql)` to run SQL directly.

**Comment by interactiveRob** [comment]
little confused here as this was closed by @catfan with no explanation. I assume this feature was not picked up?

**Comment by marki555** [comment]
> little confused here as this was closed by [@catfan](https://github.com/catfan) with no explanation. I assume this feature was not picked up?

Yes, the close reason should not be completed. I guess it is not implemented because Medoo is database-agnostic, so doesn't support things which work only in 1 of database engines.
