### ISSUE TITLE
Count Problem

### ISSUE THREAD

**Issue by inventr** [catfan/Medoo#320]
I have a data with 30000 records, when I make a count using $ database-> count the result is always 9551.

the SQL of log_query in to use phpmyadmin or  $database->query(), the counts 30000.

**Comment by catfan** [comment]
Would you like to output the result of $database->debug()->count and the query you used on PHPmyadmin?

**Comment by mabdullah353** [comment]
mysql> select count(*) from mo;
    +----------+
    | count(*) |
    +----------+
    |     5047 |
    +----------+
    1 row in set (0.00 sec)

Now i want to run this query using meedo i tried this.

        $mo = $this->DB->debug()->count('mo');
        var_dump($mo);
        var_dump($this->DB->error());

Output is this

    SELECT COUNT(*) FROM "mo"
    bool(false) 
    array(3) { [0]=> string(5) "00000" [1]=> NULL [2]=> NULL }

**Comment by SyuTingSong** [comment]
You sql will NOT be executed but only print if you call `debug()`
