### ISSUE TITLE
Request : add LOW_PRIORITY statement

### ISSUE THREAD

**Issue by touchweb-vincent** [catfan/Medoo#329]
Hello,

It would be perfect if you could add this kind of statement to manage the priority of ours insert/update queries.

An idea : $db->insert('exemple', $insert, 'low');

Thanks

Regards,

Vincent

**Comment by SyuTingSong** [comment]
You should explain more about the priority of statement.

**Comment by vincent-guesnard** [comment]
Admitting that your server is dealing with a high traffic, like 500 requests per second.

The internal mechanism of MySQL is to lock tables (MyISAM) or raws (InnoDB) when an insert/update request is fire, so no SELECT can be fired meanwhile.

On heavy loaded tables, that could make thousands of requests in a waiting state (and sometimes can cause MySQL crashes).

To avoid this fact, MySQL allow you to specify a priority on your request, then MySQL will choose the "best" (or "less worst") moment to fire your insert/update.

(if you add this statement, here is another usefull one : SQL_NO_CACHE)
