### ISSUE TITLE
[HOW TO] Join on multiple table with OR condition

### ISSUE THREAD

**Issue by Serg4554** [catfan/Medoo#331]
Right now we can join on multiple tables writing this **'join'** array:

``` php
[ ..., 
 '[>]table_3' => ['table_2.ID' => 'ID',
                  'table_1.ID' => 'ID']]
```

That generates something like that:

``` SQL
...
LEFT JOIN "table_3"
ON "table_2"."ID" = "table_3"."ID"
AND "table_1"."ID" = "table_3"."ID"
```

But I would like to join multiple tables using the **OR** condition (instead AND) and I'm not sure if Medoo can do it. For example, I would like a Query like this:

``` SQL
...
LEFT JOIN "table_3"
ON "table_2"."ID" = "table_3"."ID"
OR "table_1"."ID" = "table_3"."ID"
```

**Anyone knows how can I do it?**
Thanks

**Comment by emanwebdev** [comment]
IMBRICATED QUERY is your solution

**Comment by Serg4554** [comment]
How can we do it with Medoo? Nothing about imbricated queries appears on the API

**Comment by Serg4554** [comment]
I "solved" it rigging the array to generate the correct query. That's the code:
```php
[ ..., 
 '[>]table_3' => ['table_2.ID' => 'ID" OR "table_1"."ID" = "table_3"."ID']
```
But it is not the best solution. If anyone knows how to correctly generate that query, please let us know. Otherwise, please add this function.

Thanks!

**Comment by SyuTingSong** [comment]
Medoo not implement the conjunction OR in join at present.

**Comment by catfan** [comment]
Well, it is considerable.

**Comment by Serg4554** [comment]
Perfect. If you implement this function, let me know it to update the query.
