### ISSUE TITLE
Request : update GROUP accept array

### ISSUE THREAD

**Issue by vincent-guesnard** [catfan/Medoo#333]
Hello,

Dealing with this, may avoid direct query usage : 

$db->select('customer', '*', array('GROUP' => array('foreign1_id', 'foreign2_id' ,'foreign3_id')));

If you could add this support, it would sounds good to me.

Thank you :)

Regards,
Vincent

**Comment by SyuTingSong** [comment]
Seems useful.
```PHP
$db->select('customer', '*', array('GROUP' => array('foreign1_id', 'foreign2_id' ,'foreign3_id')));
```
Creates query
```SQL
SELECT * FROM "customer" GROUP BY "foreign1_id", "foreign2_id", "foreign3_id"
```

**Comment by catfan** [comment]
Supported on Medoo 1.4.
