### ISSUE TITLE
SQL Fail-safe

### ISSUE THREAD

**Issue by snopboy** [catfan/Medoo#342]
Hey,
Is there no fail-safe for Medoo?
If the database is down and Medoo tries to perform queries, it will not print any output after the point in which the first query was performed, meaning some html will be printed to the user but from the point where I try to execute a SQL query it will break all and not present any output that should've been printed from that point on, resulting in a half-page display (or even less, depends on where you started executing queries).

Is there a fail safe of some kind? Anyone has any idea how to implement one? I remember Laravel and CodeIgniter both had a fail safe so even if the SQL is not connected it will still present all the output.

**Comment by snopboy** [comment]
Any input?
@catfan 
@qatrix

**Comment by baschwartz** [comment]
`$database = new medoo();` would throw an error if there's a problem with the database.
