### ISSUE TITLE
Problem with select join (OR operator)

### ISSUE THREAD

**Issue by renat2985** [catfan/Medoo#345]
Tell me please how I can use the OR operator

> $quote = $database->select("quote",
>                             ['[>]users' => ['Email' => 'Email',    >>>>>OR<<<<<     'Phone' => 'Phone']],
>                             ['users.UserID', 'users.FName','users.LName', 'quote.JobTitle', 'quote.QuoteID', 'quote.Description'],
>                             ["ORDER" => 'quote.Create DESC']);

**Comment by baschwartz** [comment]
$quote->select('quote', [
		'[>]users' => ['QuoteID' => 'UserID'],
	],[
		'users.UserID', 'users.FName','users.LName', 'quote.JobTitle', 'quote.QuoteID', 'quote.Description'], 
	],[
		'OR' => ['Email' => 'email','Phone' => 'phone'],
		'ORDER => ['quote.Create DESC']
]);

**Comment by renat2985** [comment]
@baschwartz, it is not suitable for me

**Comment by james090500** [comment]
@renat2985 Did you even find a suitable fix for this?
