### ISSUE TITLE
No release note and no new version tag

### ISSUE THREAD

**Issue by jiaxunjiaxun** [catfan/Medoo#347]
Was version 1.0.1 a bug fixed version? or did it add some new features? Please, release a new version tag. I think a lot of users have these questions. By the way, composer library can not download the latest version. Thanks.

**Comment by SyuTingSong** [comment]
I checked git commit log. It's a bugfix version. Changes I commented in #346

**Comment by jiaxunjiaxun** [comment]
Thanks~
