### ISSUE TITLE
Can't order in DESC

### ISSUE THREAD

**Issue by iMohammadReza** [catfan/Medoo#350]
Hi
At first I should say that medoo in awesome.
Then, I use this line to search into my records:
$datas = $database->select("Board","*",["OR" => ["title[~]" => $_GET['q'],"text[~]" => $_GET['q']]],["ORDER" => "id DESC",]);
Its works but not in DESC order and the output is in ASC order…
How to order it in DESC or What’s my mistake?
And also, Does this line secure ( SQL Injections)?
Thanks…

**Comment by SyuTingSong** [comment]
`ORDER` should be the same level as `OR` in where clause.
```PHP
$datas = $database->select("Board","*",[
    "OR" => [
        "title[~]" => $_GET['q'],
        "text[~]" => $_GET['q']
    ],
    "ORDER" => "id DESC"
]);
```

**Comment by iMohammadReza** [comment]
Thanks a lot.
It fixed but Does this code safe for SQL Injections?

**Comment by SyuTingSong** [comment]
Medoo quote every value with [`PDO::quote`](https://secure.php.net/manual/en/pdo.quote.php)
