### ISSUE TITLE
How can i sort arrays?

### ISSUE THREAD

**Issue by da411d** [catfan/Medoo#352]
How can i sort arrays?

**Comment by SyuTingSong** [comment]
https://secure.php.net/manual/en/array.sorting.php

**Comment by da411d** [comment]
It is good but it would be great to sort arrays in medoo)

**Comment by SyuTingSong** [comment]
If you mean sort by database, check the `ORDER` condition in medoo [doc](http://medoo.in/api/where).

**Comment by jiaxunjiaxun** [comment]
http://medoo.in/api/where
## Order Condition
