### ISSUE TITLE
why not support page select?

### ISSUE THREAD

**Issue by metowolf** [catfan/Medoo#355]
`$db->select('xx','xx',['page'=>[2,30]])` -> `$db->select('xx','xx',['LIMIT'=>[(2-1)*30,30]])`

**Comment by jiaxunjiaxun** [comment]
Why support ;) ~~ You can implement it simply, and 'page' will be another keyword, that we should pay attention. =)

**Comment by metowolf** [comment]
I was oblivious of that, THK! : )
