### ISSUE TITLE
Typo on line 869 require instead of return

### ISSUE THREAD

**Issue by Stantastic** [catfan/Medoo#356]
`	public function has($table, $join, $where = null)
    	{
		$column = null;

		$query = $this->query('SELECT EXISTS(' . $this->select_context($table, $join, $column, $where, 1) . ')');

		if ($query)
		{
			return $query->fetchColumn() === '1';
		}
		else
		{
			require false;
		}
	}`

i think it should be `return false;`

**Comment by catfan** [comment]
Really sorry for this stupid bug! We fixed it now.
