### ISSUE TITLE
Postgis ST_ASTEXT problems in Medoo

### ISSUE THREAD

**Issue by Enso-Sa** [catfan/Medoo#359]
Hi,

I have been developing with Medoo framework and I have a problem when I try to execute this code:
$data = $database->select(self::$mytable, ['id', 'point as ST_ASTEXT(point)], [deleted_date' => null]);
I have following error:
Array
(
    [0] => 42703
    [1] => 7
    [2] => ERROR:  column "ST_ASTEXT" does not exist
LINE 1: "id","ST_ASTEXT...
                   ^
)

Someone already had the same error? Someone can help me?
Thks

**Comment by SyuTingSong** [comment]
use `$database->log()` to fetch queried SQLs or use `$database->debug()->select()` to echo SQL without querying.
