### ISSUE TITLE
Documentation - lastInsertId in PostgreSQL

### ISSUE THREAD

**Issue by OnPe** [catfan/Medoo#364]
Hello,
I'm not able to find, what is correct syntax to receive id of last record from insert for PostgreSQL. What is in documentation is ok only in MySQL.

Where is possible to find more details?

Thx

**Comment by OnPe** [comment]
I found way, how to receive id of last inserted record, but I don't like my solution. Can you help me, what's the best way, if I'm using Medoo and PostgreSQL?

Thx

**Comment by SyuTingSong** [comment]
`$medoo->insert()` returns the id(s) of inserted record(s).

**Comment by OnPe** [comment]
Thx, but for me not works. With MySQL it's OK, but with PostgreSQL not. I solved it using $db->insert(".....]) and $last_id = $db->pdo->lastInsertId('............');
