### ISSUE TITLE
[Bug] Returns nothing in MSSQL when nvarchar(MAX) is used

### ISSUE THREAD

**Issue by StephenShamakian** [catfan/Medoo#367]
Using MSSQL nothing is returned when you do a SELECT on a DB table that has a column with nvarchar(MAX) set. If I change the column to nvarchar(250) it returns the results from the table.

Inserting data is not an issue. Just returning data.

**Comment by jcrben** [comment]
There's various PHP bugs reported on this: https://bugs.php.net/bug.php?id=67437
