### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by omaressa** [catfan/Medoo#371]
Hi, 
First of all, thank you so much for creating this useful library..I've been using it a lot lately - But I've noticed the documentation is not so clear. For Instance, I wanted to run an update query with multiple AND conditions and so i went to http://medoo.in/api/update and I noticed that there was no documentation regarding  queries with complex logic e.g multiple boolean operators, etc. It would make sense to include examples with various boolean operators - I'd be happy to modify the content and add more examples!
Thanks!

**Comment by omaressa** [comment]
@catfan Looking forward to hear back from you on this.

**Comment by catfan** [comment]
The doc is now with more examples.
