### ISSUE TITLE
medoo 如何进行数据库字段的加和?

### ISSUE THREAD

**Issue by no13bus** [catfan/Medoo#372]
比如 select a+b from cc
a 和 b 分别是 cc 库的两个字段

**Comment by omaressa** [comment]
@no13bus  Could you please post this in English? I might be able to help you out!
Thanks!

**Comment by SyuTingSong** [comment]
Here is the translate:

How to plus column values in medoo.
For example `select a+b from cc`
`a` and `b` are two fields in table `cc`

**Comment by omaressa** [comment]
@SyuTingSong  I believe that is not possible to do so out of the box, however you can run raw query using the query api http://medoo.in/api/query

**Comment by no13bus** [comment]
@omaressa thanks. Actually, I check the source code of medoo,  but I am not sure.

**Comment by catfan** [comment]
It's now possible for Medoo 1.2.
