### ISSUE TITLE
bug: compound conditions in where clause referencing same column name only register the last condition

### ISSUE THREAD

**Issue by lfxc** [catfan/Medoo#373]
$db->debug()->select("tablename", [ "id", "status" ],
      [ "AND" => [ "OR" => [ "status" => "STATUS1" , "status" => "STATUS2" ],  "ID" => "7"]]);

produces:

SELECT "id","status" FROM "tablename" 
    WHERE ("status" = 'STATUS2') AND "ID" = '7'

The first OR condition ( "status" => "STATUS1"  ) gets lost.  I assume it's because the OR statement is referencing the same column name ("status") more than once and it's only remembering the last one it saw.   Probably an associative array key issue when building the where clause.

**Comment by SyuTingSong** [comment]
You cannot use the same key twice in PHP Associated-Array.
Try this
```
$db->debug()->select("tablename", [ "id", "status" ], [
         "AND" => [
            "status" => ["STATUS1" , "STATUS2" ],
            "ID" => "7"
        ]
    ]
);
```

**Comment by lfxc** [comment]
perfect!  thanks
