### ISSUE TITLE
Sanitize Inputs

### ISSUE THREAD

**Issue by Jeff-P** [catfan/Medoo#379]
I just got a project where the other dev used this library and it looks cool. I dont see in the docs how they recommend or sanitize input. Im assuming this is secure(says it on the website) but would like to know before proceeding with it. Thanks

**Comment by omaressa** [comment]
Hi @Jeff-P  , The input is sanitized by passing the input to quote function which is just a shiny wrapper around the pdo quote function.  http://php.net/manual/en/pdo.quote.php
