### ISSUE TITLE
PDO ssl certs

### ISSUE THREAD

**Issue by Jeff-P** [catfan/Medoo#380]
I cant find in the documentation where it shows how to add or if its compatible to use ssl certs for a pdo connections

**Comment by omaressa** [comment]
I believe this is currently not supported by Medoo, however since Medoo uses PDO under the hood so it should be relatively easy to patch this in.

**Comment by catfan** [comment]
You can add this for initialization as option
```php
'option' => [
        PDO::MYSQL_ATTR_SSL_KEY  => '/etc/mysql/client-key.pem',
        PDO::MYSQL_ATTR_SSL_CERT => '/etc/mysql/client-cert.pem',
        PDO::MYSQL_ATTR_SSL_CA   => '/etc/mysql/ca-cert.pem'
]
```

**Comment by Jeff-P** [comment]
Worked for me thank you
