### ISSUE TITLE
SQL function in SELECT clause

### ISSUE THREAD

**Issue by carestad** [catfan/Medoo#381]
Hi

Is there any way to perform data conversion etc. in the SELECT caluse, like in WHERE?

For example:

```
SELECT NVARCHAR(uuid) AS uuid
FROM table
```

In my mind it could work almost as when doing this in WHERE:

```
$db = new medoo($dbconf);
$db->get('table', '#NVARCHAR(uuid) AS uuid');
```

When prefixing the table with a pound sign, the parenthesis syntax for aliasing tables would naturally break, but why not just disable it altogether then and allow for writing it yourself?

**Comment by jasonlav** [comment]
+1

**Comment by JunJun-Love-Amber** [comment]
+1

**Comment by jerrywham** [comment]
+1

See https://dev.mysql.com/doc/refman/5.7/en/functions.html for all possibility
and https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html

It would be usefull to wrote something like this :
```php
$medoo->select(
    'table',
    [
       'HEX(uuid) (uuid)',
       'LCASE(name) (name)'
       "DATE_FORMAT(dateofbirth,'%Y') (birthday)"
   ],
   [
       "DATE_FORMAT(`dateofbirth`,'%Y')" => "DATE_FORMAT((CURDATE()),'%Y)",
      'GROUPBYWITHROLLUP' => 'phase'
   ]);
```
That would generate something like this :
```sql
SELECT HEX(uuid) AS uuid, LCASE(name) AS name, DATE_FORMAT(dateofbirth,'%Y') AS birthday 
FROM table
WHERE DATE_FORMAT(`dateofbirth`,'%Y') = DATE_FORMAT((CURDATE()),'%Y)
GROUP BY 'phase' WITH ROLLUP

**Comment by catfan** [comment]
Using SQL functions will be supported on v1.5. You can use it as raw object. It's developing.

All those issues will be closed after this feature is finished.

**Comment by nealoke** [comment]
+1

@catfan really appreciate this project and don't want to be pushy, but when do you think `v1.5` will be put out? :)

**Comment by catfan** [comment]
It's now released.

https://medoo.in/api/raw
