### ISSUE TITLE
Documentation is not working.

### ISSUE THREAD

**Issue by unglud** [catfan/Medoo#383]
Hi!

Here http://medoo.in/api/where looks like some debug dump, as result cant read page.
Same here http://medoo.in/api/log

![](https://up.kibakoapp.com/c5ThwdNAUq!)

Thanks!

**Comment by catfan** [comment]
Can you show the ping result of medoo.in? We have nothing change for the website in current.

**Comment by omaressa** [comment]
Working fine over here too. Could be network issue.

**Comment by SyuTingSong** [comment]
Seems like DNS hijack
