### ISSUE TITLE
Can't use sql  function?

### ISSUE THREAD

**Issue by linjielig** [catfan/Medoo#389]
```
protected function fn_quote($column, $string)
    {
        return (strpos($column, '#') === 0 && preg_match('/^[A-Z0-9\_]*\([^)]*\)$/', $string)) ?
            $string :
            $this->quote($string);
    }
```

Because this function only allow function don't have parameter, so I can't use function like this:
`['#store_time[>=]']="SUBDATE(CURDATE(),WEEKDAY(CURDATE()))"`

Are you should use this regex:
`/^[A-Z0-9\_]*\(.*\)$/`

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
