### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by penn-ma** [catfan/Medoo#391]
当时用表前缀配置数据库连接，并且在select中使用关联查询是，出现错误拼接表前缀。
 SELECT * FROM "st_test" LEFT JOIN "st_test2" ON st_"st_test"."id" = "test2"."test_id" WHERE "id" = 1
可以看到在ON后多出来一个st_表前缀，而且test2没有增加表前缀。
错误出现在500行。$joins[] = $this->prefix . (

**Comment by Filisko** [comment]
can't you write in english? :S

**Comment by penn-ma** [comment]
When using table prefix to configure the database connection, and select join table query error。
SELECT * FROM "st_test" LEFT JOIN "st_test2" ON st_"st_test"."id" = "test2"."test_id" WHERE "id" = 1
In the "ON" with a "st_" table prefix,and table "test2" not prefix
Error in the 500 line.
$joins[] = $this->prefix . (

**Comment by penn-ma** [comment]
I find commits on feb 14, 2016 about this bug.
colse
