### ISSUE TITLE
Translate doc

### ISSUE THREAD

**Issue by fabioassuncao** [catfan/Medoo#394]
@catfan where I can make a fork of the **documentation** so I can produce the **translation** for my language (**pt BR**). **I am sure it will help many developers**. Grateful!

**Comment by catfan** [comment]
Our documentation system is not open-sourced. It may update often. For better quality, we may find professional translator for internationalization job if we have enough fund. But seemly impossible just now :(.

**Comment by catfan** [comment]
We have Brazilian Portuguese version now: https://medoo.in/pt-BR.
