### ISSUE TITLE
Error query join table with table prefix

### ISSUE THREAD

**Issue by kovloq** [catfan/Medoo#403]
HI,

I have a query like this

`
$message=$database->select("messages",
                array("[>]user" => array("user_id" => "id")),
                array("user_id","admin_id","title","message","created_at"),
                array("ORDER" => "id DESC","user_id"=>$_SESSION["user_id"]));
`

The error message when I did a var_dump($database->error()); is

`array(3) { [0]=> string(5) "42000" [1]=> int(1064) [2]=> string(228) "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"srce_messages"."user_id" = "user"."id" WHERE "user_id" = '1' ORDER BY "id" DESC' at line 1" }`

Lastly here is the generated query when I did $database->last_query();

`SELECT "user_id","admin_id","title","message","created_at" FROM "srce_messages" LEFT JOIN "srce_user" ON srce_"srce_messages"."user_id" = "user"."id" WHERE "user_id" = '1' ORDER BY "id" DESC`
I think this generated query parts that makes the error occurred

> srce_"srce_messages"
> The prefix was called twice.

Is this a bug?or I have a wrong query?

Thank You

**Comment by catfan** [comment]
Fixed it on cd389ed
