### ISSUE TITLE
Medoo is not working on ubuntu server

### ISSUE THREAD

**Issue by eratsu** [catfan/Medoo#404]
I'm coding a project with medoo on my computer, but when i send it to the server (vps) the page which contains this code is not working and receive a blank page. 
`$database = new medoo([
    'database_type' => 'mysql',
    'database_name' => 'test',
    'server' => 'localhost',
    'username' => 'root',
    'password' => '123',
    'charset' => 'utf8'
]);`

I've tried to upload my project in 2 vps, php 7 and 5

**Comment by catfan** [comment]
Check your log file and see what's wrong.
