### ISSUE TITLE
md5 with Select Query Column 

### ISSUE THREAD

**Issue by somasish** [catfan/Medoo#408]
Hi,
i am 1st time user of Medoo
i have a situation where md5 of a column equals a string. Something like this below. 
How can i do it using Medoo

$datas = $database->select("account", [
    "user_name",
    "email"
], [
    md5("user_id") => $SomeMd5String
]);

Thanks In Advance

**Comment by catfan** [comment]
How about this?

```php
$datas = $database->select("account", [
		"user_name",
		"email"
	], [
		"user_id" => md5($SomeMd5String)
	]
);
```

**Comment by somasish** [comment]
Hi,
Thanks for the reply,
but the above solution will yield me double md5 of the string which equals to the user_id column in the query.
We don't have decryptMd5 function but that will yield me perfect result. 
`$datas = $database->select("account", [
        "user_name",
        "email"
    ], [
        "user_id" => **decryptmd5**($SomeMd5String)
    ]
);`
any possible way to handle through the medoo query.
one possible way through programming is to fetch all user_id and convert to MD5 and compare. but it's not an effective way of programming

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
