### ISSUE TITLE
Does Medoo support MySQL 5.7 new JSON feature?

### ISSUE THREAD

**Issue by Nicero** [catfan/Medoo#410]
I installed on my VPS MySQL ver. 5.7 because since this version MySQL added native JSON data type that enables an efficient access to data in JSON.

Can I use these new feature with Medoo? If so, can you post an example?

Thank you

**Comment by catfan** [comment]
It didn't support MySQL JSON function, but you can assign the column data as JSON and Medoo will insert it as JSON string data into database.

http://medoo.in/api/insert
