### ISSUE TITLE
where syntax cannot set the same table's field

### ISSUE THREAD

**Issue by bitkwan** [catfan/Medoo#412]
for example,
I wanna set the where syntax:

> 'service.transfer_enable'>'service.total_use'

I tried it in my code:

`$user=$db->select("service",[
            "[>]members" => ["uid" => "uid"]
        ],[
            "service.id",
            "service.transfer_enable",
            "service.total_use",
            "members.transfer"
        ],[
            "AND"=>[
                "service.transfer_enable[>]"=>"service.total_use",
                "members.transfer[>]"=>1048576
            ]
        ]);`

**Comment by catfan** [comment]
It supported now.
