### ISSUE TITLE
How to use OFFSET?

### ISSUE THREAD

**Issue by iMohammadReza** [catfan/Medoo#413]
I didn't find any documents for using LIMIT and OFFSET...
and this code didn't work:
`$datas = $database->select("notepad", [
		"message_text"
		], [
		"ORDER" => "id DESC",
		"LIMIT" => "5",
		"OFFSET" => "2"
		]);`

**Comment by ajm113** [comment]
Have you tried doing this?

`$datas = $database->select("notepad", [ "message_text" ], [ "ORDER" => "id DESC", "LIMIT" => [5, 2]);`

You can simply pass an array to the LIMIT key, and that can handle your offset. `[100, 2]`

**Comment by ajm113** [comment]
P.S The issues is more of a "bug tracker", I can see why you could think this a bug/problem with the library, but please do your research before posting issues next time. Stackoverflow has you covered regarding assistance using the library.

http://stackoverflow.com/questions/tagged/medoo

**Comment by iMohammadReza** [comment]
Thanks for your help  and P.S...
and sorry about that...

**Comment by ajm113** [comment]
No problem, and no worries! We all have to start somewhere.
