### ISSUE TITLE
[feature] Mysql Regexp Function

### ISSUE THREAD

**Issue by indiwine** [catfan/Medoo#414]
Hi.

Its not an issue itself. 
Is it good idea to add [MySQL regexp](http://dev.mysql.com/doc/refman/5.5/en/regexp.html) function support to Medoo? 

Unfortunately its not possible to do a PDO::quote on any regexp.
Is there any way to make such queries secured?

What do you think about it?

**Comment by elbyvilayil** [comment]
Hi 
I added  Regexp in where. You can check in the issue **"Add REGEX in WHERE query #416"** . But I didn't check with PDO::quote

**Comment by indiwine** [comment]
Oh 
I also do the same(on the local branch, of course) :)
But with syntax: 
[ "REGEXP#comment" => [
       'column' => 'some column',
       'pattern' => '[abz]
]]

Is secure to pass a regexp pattern to mysql without any checks?

**Comment by elbyvilayil** [comment]
I think its not secure but if the regexp will be provided by the developer its no problem. The challenge is how can we filter regex ?

**Comment by indiwine** [comment]
Maybe some regexp? Regexp to check regexp

**Comment by catfan** [comment]
v1.5 support regexp.

https://medoo.in/api/where
