### ISSUE TITLE
How to use date_format in select or get ?

### ISSUE THREAD

**Issue by elbyvilayil** [catfan/Medoo#415]
How to convert following query to medoo select ?

select *, date_format(column_name, '%d %b %Y') as column_alias from table_name;

**Comment by kaiser-tushar** [comment]
We can use like this,
table.created[<=]  = date('Y-m-d H:i:s', $end_date)

But how can we use this,
DATE(table.created)[<=]  = date('Y-m-d', $end_date)

I need to run DATE(created) type query. Can we do that?

**Comment by catfan** [comment]
It's possible to do that using raw object. https://medoo.in/api/raw
