### ISSUE TITLE
update + join

### ISSUE THREAD

**Issue by adminko-svk** [catfan/Medoo#417]
Hi, how can I use JOIN in UPDATE?

```
$users_id = $db->select('bans', [
    '[><]' . 'users' => ['user' => 'id'],
], 'users.id', [
    'bans.value[>]' => 0,
]);

$db->update('bans', [
    'value[-]' => 1,
], [
    'id' => $users_id,
]);
```

As you can see, now I must select users IDs with `SELECT` and then I use `UPDATE`.
I would like to use only one (UPDATE) query.

**Comment by wenpeng** [comment]
you can use the "action" method
