### ISSUE TITLE
$this->logs memory growth problem

### ISSUE THREAD

**Issue by iyaozhen** [catfan/Medoo#419]
Medoo code:

``` PHP
public function query($query)
{
    ...
    array_push($this->logs, $query);
    return $this->pdo->query($query);
}
public function exec($query)
{
    ...
    array_push($this->logs, $query);
    return $this->pdo->exec($query);
}
```

I use medoo in php-cli, loop rpop data from redis list and insert data to mysql. `array_push($this->logs, $query);` make memory grow fast, until OOM.

Pls fix it. Limit logs array size? OR add some config? And notice It in document.

**Comment by synchronized** [comment]
You can create class extends Medoo and create function popLog() to return logs and clear the variable $this->log

**Comment by iyaozhen** [comment]
Thx, This is good way.
