### ISSUE TITLE
function column_quote Have bug

### ISSUE THREAD

**Issue by mengjie0827** [catfan/Medoo#428]
$last_user_id = $db->insert("userlist", [
    "username" => "foo",
    "(JSON)userqq" => ["en", "fr", "jp", "cn"] 
]);

SQL:
INSERT INTO "userlist" (username, (JSON)userqq) VALUES ('foo', '[\"en\",\"fr\",\"jp\",\"cn\"]')

Can not replace JSON?

**Comment by easylogic** [comment]
column quote pattern is wrong. 


```php
protected function column_quote($string)
{
     return preg_replace('/(\(JSON\)\s*|^#)?([a-zA-Z0-9_]*)\.([a-zA-Z0-9_]*)/', '"' . $this->prefix . '$2"."$3"', $string);
}
```

you must add table name before field name.

```php
$last_user_id = $db->insert("userlist", [
"username" => "foo",
"(JSON)userlist.userqq" => ["en", "fr", "jp", "cn"] 
]);
```
