### ISSUE TITLE
NOW() function

### ISSUE THREAD

**Issue by aidenko** [catfan/Medoo#429]
In the version 1.0.2 this worked

_$db->insert('table', array('#created_at' => NOW()))_

in the version 1.1.1 this does not work, because a query is

_INSERT INTO table (#created_at) VALUES(NOW())_

Was there any update in the latest version for using mysql functions?

Thanks,
Artem

**Comment by elbyvilayil** [comment]
Yes NOW is not working for INSERT in new version

**Comment by leonirlopes** [comment]
Same problem with 'UPDATE'.

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
