### ISSUE TITLE
Let assign ALIAS to Select Columns

### ISSUE THREAD

**Issue by jimolina** [catfan/Medoo#43]
Hi

If you need this query:

Select a.name, b.name from section as a left join gallery as b on(a.idsection=b.section_idsection)

In the Medoo format:

$Data = $database->select("section", 
                [
                "[>]gallery" => ["idsection" => "section_idsection"]
                ], 
                [
                "section.name",
                "gallery.name",
                ]
]);

But you can't differentiate between NAME of Section or NAME of GALLERY. You need have an ALIAS in the query. So:

1) Add in the LINE: 127

```
    protected function column_quote_as($string)
    {
            return str_replace('.', '`.`', $string);
    }
```

2) Add in the LINE: 405 (original line)

if (is_array($columns)){
        foreach($columns AS $Columns){
            $columnsTemp =explode('[>]',$Columns);
            $columnsVal = ($columnsTemp[1]!='') ? '`' . $columnsTemp[0] . '` AS \'' . $columnsTemp[1] . '\'':'`' .$columnsTemp[0] . '`';
            $ColumnsEnd[] = $columnsVal;
        }
}else{
            $ColumnsEnd[]='`' .$columns . '`';
        }

3) Change the LINE: 408 (original line)

```
                is_array($ColumnsEnd) ? $this->column_quote_as( implode(', ', $ColumnsEnd) ) :
```

And now, the new format to take the query is:

$Data = $database->select("section", 
                [
                "[>]gallery" => ["idsection" => "section_idsection"]
                ], 
                [
                "section.name",
                "gallery.name[>]NameGallery",
                ]
]);

**Comment by elbyvilayil** [comment]
How to convert following query to  medoo select ?

select *, date_format(column_name, '%d %b %Y') as column_alias from table_name;
