### ISSUE TITLE
like putting AND in mysql query

### ISSUE THREAD

**Issue by mauriciosouza** [catfan/Medoo#436]
This is the array I have in WHERE

Array ( [AND] => Array ( [p.nome[~]] => Array ( [0] => hd [1] => 500 ) ) [LIMIT] => Array ( [0] => 0 [1] => 30 ) ) 

but it is always placed OR:
WHERE p.nome LIKE '%hd%' OR p.nome LIKE '%500%' LIMIT 0,30

**Comment by progressify** [comment]
Hi
I have created a patch for this problem
Today I commit this change for approval
