### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by KiborgMaster** [catfan/Medoo#437]
in version 1.1.2 
1) ORDER BY RAND()  - does not work
2) Function [SELECT]  does not return array value, because i check my query, and [SELECT] must return three value, but he dont return never and PHP answer Warning: Invalid argument supplied for foreach()

**Comment by catfan** [comment]
1. Yes, ORDER BY RAND() is not supported, and we don't recommend you to use that for randomizing data.

2. Would you like to show me the code you used for `select()`?

**Comment by KiborgMaster** [comment]
But sumthing my client use RADNOM view.  THis is my code, in version Medoo 0.9.8.3 all work very good

$_postData = $this->db->select('v_'.PREFIX.'short_posts', ['incr', 'incr_cat'], 
			[  'AND'=>['incr_cat[=]'=>$viewIncrCats, 'lang'=>$lang, 'status'=>'active'],
			   'ORDER'=>$_dataCat['order_by'].' '.$_dataCat['order_type'],
				 'LIMIT'=>[ $bLimit, $eLimit ] 
			] 
			);
	
foreach($_postData as $value) ........
echo $this->db->last_query()  =   SELECT "incr","incr_cat" FROM "v_wst_short_posts" WHERE "incr_cat" IN ('5') AND "lang" = 'ru' AND "status" = 'active' ORDER BY "incr" DESC LIMIT 0,10

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw.
