### ISSUE TITLE
[BUG] ORDER old sintax v1.1.2

### ISSUE THREAD

**Issue by Hatsunyan** [catfan/Medoo#444]
In version 1.1.1 work old sintax ORDER

```php
['ORDER'=>'id DESC']
```
after update on 1.1.2 work only new sintax

**Comment by catfan** [comment]
Yes, we don't support this syntax anymore. Split the order sorting keyword to make the code looked cleaner.

```php
"ORDER" => [
	"id" => "ASC"
]
```
