### ISSUE TITLE
Select GROUP ordering issue

### ISSUE THREAD

**Issue by fpswebmaster** [catfan/Medoo#446]
Medoo V = 1.1.2

When doing a ORDER function, you cannot pass along the direction it should order by

It returns a FALSE statement. Checking LINE 493 I can clearly see its not being passed as an array ... and when I FAKE it being an array the "$stack[] = $this->column_quote($column) . ' ' . $value;" does not function.

Below is the example SELECT statement I am running.

EX:

```
<!--BREAKS-->
$techs = $this->medoo()->select("stat_technicians", // DB Table
    ["id","l_name"], // DB Columns
    ["ORDER" => "l_name ASC"]
);

<!--WORKS-->
$techs = $this->medoo()->select("stat_technicians", // DB Table
    ["id","l_name"], // DB Columns
    ["ORDER" => "l_name"]
);

UPDATE
<!--WORKS ... But doesn't SORT-->
$techs = $this->medoo()->select("stat_technicians", // DB Table
    ["id","l_name"], // DB Columns
    ["ORDER" => "stat_technicians.l_name ASC"]
);
```

**Comment by catfan** [comment]
Check out the new ORDER syntax for v1.1.
