### ISSUE TITLE
support json_decode on select

### ISSUE THREAD

**Issue by levu42** [catfan/Medoo#450]
I can do an insert and the array gets converted into a text by `(JSON) settings` but the other way round it's not possible, to `->select('users', ['(JSON) settings'], […]);` and get an array. Why?

**Comment by catfan** [comment]
Because it will have to check out every selected data and convert it into JSON. It will cause some performance issue.

I'm considering the better way to improve for this.

**Comment by catfan** [comment]
Support on latest version.
