### ISSUE TITLE
insert columns are not quoted

### ISSUE THREAD

**Issue by AceWT** [catfan/Medoo#454]
when trying to insert eg:

$db->insert('table',
    array(
        'accountID' =>  27,
        'order' => 123
    )
);
its not executing becouse order is not quoted. Works fine in update etc..
Please fix.

**Comment by DeltaWolf7** [comment]
I have the same thing with the latest version 1.1.2.

Using insert command, the output generated by Medoo is:-

 (key, value, userid) VALUES ('TEST', 'This is a test', '0')

As you can see the column names are not is quotation marks. From my object the input was:-

["key" => "TEST", "value" => "This is a test", "userid" => "0"]

Worked fine with passed 1.0.2.

Thanks

**Comment by vishtany** [comment]
i have the issue after an update to 1.1.2.
