### ISSUE TITLE
columns in select result set is in different order on different environment

### ISSUE THREAD

**Issue by brnogz** [catfan/Medoo#457]
i'm trying to generate formatted string from query result. however query result is not same on my local and remote environment. in my condition, i cannot use column names so order of the columns is important.

select query
`$this->db->select('activity_elevation',['elevation','time'],[ 'activity_id'=>$activityId]);`

result on local
`array ( 'time' => '3', 'elevation' => '98.21', )`

result on remote
`array ( 'elevation' => '98.21', 'time' => '3', )`

**Comment by ajm113** [comment]
And the remote and local database has the same exact table layout I assume?

**Comment by brnogz** [comment]
there is only remote database. i connect remote database from my local
