### ISSUE TITLE
BIG BUG (NOW I FIXED THEM)

### ISSUE THREAD

**Issue by KiborgMaster** [catfan/Medoo#461]
In version 1.1.2 select do not return array values
$postData = $this->db->select('v'.PREFIX.'short_posts', ['incr', 'incr_cat'], 
[ 'AND'=>['incr_cat[=]'=>$viewIncrCats, 'lang'=>$lang, 'status'=>'active'],
'ORDER'=>$_dataCat['order_by'].' '.$_dataCat['order_type'],
'LIMIT'=>[ $bLimit, $eLimit ] 
] );

foreach($_postData as $value){
 ........
}
PHP Error - Warning: Invalid argument supplied for foreach()

 In version Medoo 0.9.8.3 its work, please fix this, its vegy big bug, because impossible to use the new version with this BUG

**Comment by KiborgMaster** [comment]
I found problen it ORDER, if i use Single condition this not work if use Multiple condition all work.

**Comment by KiborgMaster** [comment]
That's the problem
 in Single      - [  ORDER BY "incr DESC" ] - incorrectly
 in Multiple  - [ ORDER BY "incr" DESC  ]  - correctly

**Comment by KiborgMaster** [comment]
Error in string 512
$where_clause .= ' ORDER BY ' . $this->column_quote($ORDER);

My solution
$order = explode(' ', $ORDER);
$where_clause .= ' ORDER BY "'.$order[0].'" '.$order[1];

**Comment by catfan** [comment]
There is a new syntax since v1.1.

http://medoo.in/api/where

**Comment by KiborgMaster** [comment]
You dont understand the plorblem, one smore 
my code 'ORDER'=>$_dataCat['order_by'].' '.$_dataCat['order_type'],
 if translate query its [ ORDER BY incr DESC ] but query write with error ORDER BY "incr DESC" argument DESC in quotes its error. In your documentation http://prntscr.com/cd1nds
