### ISSUE TITLE
Data updating bug?

### ISSUE THREAD

**Issue by tevenfeng** [catfan/Medoo#464]
I got a problem when i try to use $database->update(), it looks like there's a bug in the code that makes it impossible to update data in MySQL. And i get the error message: column "fengdingwen@outlook.com" not exists in where clause. And when i try to use $database->query() with the same UPDATE sql statement which can be executed without any problems in  MySQL workbench, it turns out to get the same error message. So i'm just wondering that whether there's a bug in the medoo code?

```
$database->update("users_information", ["user_nickname",
    "user_password"=>$password_to_update,
    "user_nickname"=>$nickname_to_update,
    "user_gender"=>$gender_to_update,
    "user_area"=>$area_to_update,
    "user_phonenumber"=>$phone_to_update], ["user_email" => $user_to_select]);
```

And here $user_to_select = fengdingwen@outlook.com

**Comment by catfan** [comment]
```
$database->update("users_information", ["user_nickname", // <-- What's that?
    "user_password"=>$password_to_update,
    "user_nickname"=>$nickname_to_update,
    "user_gender"=>$gender_to_update,
    "user_area"=>$area_to_update,
    "user_phonenumber"=>$phone_to_update], ["user_email" => $user_to_select]);
```
