### ISSUE TITLE
Join operations on Mysql reserved keywords such as "status", "key"

### ISSUE THREAD

**Issue by leoncool** [catfan/Medoo#466]
I have some MYSQL tables with some reserved field names such as "status" and "key" , in the earlier versions, I didn't encounter any problem, but after updated to the 1.1.2 version, some join operations will not be executed, either, no error will be shown.

**Comment by jdanielcmedina** [comment]
I have the same problem... try another word.

**Comment by paulholden** [comment]
An easy workaround is to prepend the reserved field name with the table name, e.g. '_MyTable.Status_' (trying to alias the field doesn't work)
