### ISSUE TITLE
SQL functions should be case insensitive

### ISSUE THREAD

**Issue by adius** [catfan/Medoo#467]
This does not work:

``` php
$insertId = $database->insert('vouchers', [
  'code' => $code,
  'value' => $value,
  '#expires' => "from_unixtime($timeStamp)",
]);
```

But this does:

``` php
$insertId = $database->insert('vouchers', [
  'code' => $code,
  'value' => $value,
  '#expires' => "FROM_UNIXTIME($timeStamp)",
]);
```

SQL is case insensitive and therefore both versions should work!

**Comment by catfan** [comment]
Check out the new feature raw object https://medoo.in/api/raw. Case insensitive also works, but we recommend capitalize with this for better readability.
