### ISSUE TITLE
SQL syntax issue

### ISSUE THREAD

**Issue by lluiscab** [catfan/Medoo#471]
I'm using version 1.1.2 and I'm getting this error.
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '"password" = 'HASHED MD5 HERE'' at line 1`

The code that I use to execute the query is:
` $user = $db->select('users', [
				'name', 'id'
			],[ 
				'email' => $email,
				'password' => $pass,
            ]);`

The generated query:
`SELECT "name","id" FROM "users" WHERE "email" = 'MY EMAIL' "password" = 'HASHED MD5 HERE`

It's me or there should be an 'AND' between "email" and "password"?

**Comment by Nicero** [comment]
I see a comma after `$pass`. Maybe is that?

**Comment by ajm113** [comment]
@Nicero For some odd reason PHP allows orphan commas after last array just like JS. (Don't know why...)

@lluiscab You are generating your query incorrectly. Please read the documents next time first before reporting an issue. The time you would spend writing the issue could have been used to debug the issue yourself and continue your day.

http://medoo.in/api/where
Read the "Relativity Condition" section.

Thanks.

**Comment by lluiscab** [comment]
Thanks ;) I feel so stupid right now ;)

**Comment by ajm113** [comment]
No problem! And I know what you mean. Specially sometimes when the answer hangs in front of your face just after you post a question. haha

Cheers!

**Comment by lluiscab** [comment]
This time I've been looking to the docs (Select and where) but I can't find a way of executing that query (I'm sure there's a way and also I'm sure It's in front of my face)
`
SELECT *
FROM   conversations
WHERE  id IN (SELECT conversation_id
              FROM   member_conversation_map
              WHERE  member_id = 123)`
