### ISSUE TITLE
Select function should return var typed on database types

### ISSUE THREAD

**Issue by grimidev** [catfan/Medoo#475]
For example: I have a table "users" with 

```
---------------------------------------
| id(int) | username(text) | age(int) |
---------------------------------------
|     1   |   username1    |    22    |
---------------------------------------
|     2   |   username2    |    50    |
---------------------------------------
```

if i retrive data from database, I obtain an array of strings, so

```
$user = $database->select("users", "*", ["id"=> 2]);
echo $user[0]["age"] === 50; //false
echo gettype($user[0]["id"]); //string
```

I'd like to treat variables without casting them everytime i fetch data from database

**Comment by david-06studio** [comment]
i found that problem too... but i get around with doing my if statements in two ways : 
`
if ( (int)$user[0]["age"] === 50 ) or
if ( $user[0]["age]=== "50" )
`
Anyway we always test the return values... in my case anyway. Good Luck !

**Comment by catfan** [comment]
Yes, it's possible. But it will slow down the fetching performance, because it have to covert the type for every data.

Anyway, it will still consider for it.

**Comment by catfan** [comment]
Data mapping is now supported.
