### ISSUE TITLE
meddo项目换人了吗?

### ISSUE THREAD

**Issue by iscraft** [catfan/Medoo#487]
为什么要求一定要用英语提交?!
我在微软的vscode用中文提了6点建议
他们是通过google翻译成英文后了解我的意图然后给了我解答
如果这个项目没有换人的话
catfan在v2ex发表话题和回复都是使用的中文
怎么在这里就要求用户必须使用英文来提交issues?!

**Comment by catfan** [comment]
Your issue will be displayed for all GitHub followers around the world here, most of them are not chinese and don't understand what you talking about if you don't translate into English.

For better feedback and discussion about the project issue on GitHub, English is the best choice. And we don't have too much manpower to help translating all non-English issues.

If you have any questions that you really don't know how to express in English, please send us email and we will help you as possible.

Thank you.
