### ISSUE TITLE
WHERE current year

### ISSUE THREAD

**Issue by Jeff-P** [catfan/Medoo#491]
is there a way to use a where statement for the current year like 
`WHERE YEAR(START_DATE) = YEAR(CURDATE()` in medoo?

**Comment by assbach** [comment]
@Jeff-P how did you solve this issue? I'm trying to get this select in meedo:
`SELECT COUNT(*) FROM rechnungen WHERE YEAR(datum) = "2017" AND QUARTER(datum) = 1`
