### ISSUE TITLE
Space in Column Name

### ISSUE THREAD

**Issue by etcook** [catfan/Medoo#492]
How do you escape a space in a column name so Medoo doesn't sanitize out everything after the space?

I'm trying to query a table that has multiple column names with a space in them. I'm using MSSQL.

**Comment by Yousha** [comment]
You must use **bracket** [COLUMN NAME] on column name.

**Comment by etcook** [comment]
@Yousha Thanks for responding. I tried that, unfortunately it still seems to sanitize it out.

**Comment by bnvnclq** [comment]
Is there a solution for this? 

I tried using the **_brackets_** / **_backtick_** and still uses the first word from column name with space.
