### ISSUE TITLE
如果在where语句中，写如1=1这样的语句时会报错

### ISSUE THREAD

**Issue by TaSnow** [catfan/Medoo#502]
如果在where语句中，写如1=1这样的语句时会报错，使用自带的error()方法打出的报错信息如下：
Array ( [0] => 42S22 [1] => 1054 [2] => Unknown column '1' in 'where clause' )
请问要如何解决？

**Comment by ajm113** [comment]
```'#1' => '1'```
http://medoo.in/api/where
