### ISSUE TITLE
Order by lost if where is set  

### ISSUE THREAD

**Issue by g-audio** [catfan/Medoo#503]
Hello,  and thanks for this tool is very helpful,
Now i cant figure out whats wrong.

`$Z = $database->select("Vorgaenge", ["ID","Pos","btext"],
["Verwendung" => "Geldzaehler"],
["ORDER" => "Pos"]);`
`echo $database->last_query();`
`SELECT "ID","Pos","Buchungstext" FROM "Vorgaenge" WHERE "Verwendung" = 'Geldzaehler'`
The Order by is lost.

if i use without **where**   **ORDER** works.
`$Z = $database->select(["Vorgaenge", ["ID","Pos","btext"], ["ORDER" => "Pos"]]);`
`echo $database->last_query();`
SELECT "ID","Pos","Buchungstext" FROM "Vorgaenge" ORDER BY "Pos"

**Comment by catfan** [comment]
There are no 4th parameter for the method call in this case.

The condition for value and ORDER are together.

```php
$database->select("Vorgaenge", [
	"ID",
	"Pos",
	"btext"
], [
	"Verwendung" => "Geldzaehler",
	"ORDER" => "Pos"
]);
```

**Comment by catfan** [comment]
There are no 4th parameter for the method call in this case.

The condition for value and ORDER are together.

```php
$database->select("Vorgaenge", [
	"ID",
	"Pos",
	"btext"
], [
	"Verwendung" => "Geldzaehler",
	"ORDER" => "Pos"
]);
```
