### ISSUE TITLE
Error while sending QUERY packet.

### ISSUE THREAD

**Issue by as911** [catfan/Medoo#505]
after execute project with medoo, PHP error log store this:
PHP Warning:  Error while sending QUERY packet. PID=237174 in /medoo.php on line 183

**Comment by kanuj** [comment]
I'd say check the following settings in your my.ini file as this seems more likely to be a MySQL configuration issue:

`SET GLOBAL max_allowed_packet=524288000;`
`SET GLOBAL wait_timeout 10;`
