### ISSUE TITLE
ORDER BY

### ISSUE THREAD

**Issue by bars38** [catfan/Medoo#506]
Hi I try to make query as in exemple:

```
            $new = $this->db->select(
            "u_company", 
            ["id", "co_name"],
            [
                "active" => '1',
                "ORDER"  => 'u_company.co_name DESC'
            ]
            );
```

and got such query last_query(); 

`SELECT "id","co_name" FROM "u_company" WHERE "active" = '1' ORDER BY "u_company"."co_name"`

Where is the problem?

Thank you

**Comment by bars38** [comment]
And if I change query like 
```
            $new = $this->db->select(
            "u_company", 
            ["id", "co_name"],
            [
                "active" => '1',
                "ORDER"  => 'co_name DESC'
            ]
            );
```
got such a result

`SELECT "id","co_name" FROM "u_company" WHERE "active" = '1' ORDER BY "co_name DESC"`

**Comment by tannu13** [comment]
Try the array style syntax for Order By -- 
`"ORDER" => ["u_company.co_name" => "DESC"]`

Hope it helps.

**Comment by bars38** [comment]
Thank you!
