### ISSUE TITLE
Docs versions?

### ISSUE THREAD

**Issue by CodeBrauer** [catfan/Medoo#507]
So I'm currently working on a older system that is using 0.9.6.2 and I can't figure out what features are new / what features I can't use.

Is there anything beside [archive.org](https://web.archive.org/web/20141111111538/http://medoo.in/)?

**Comment by CodeBrauer** [comment]
And which versions can be updated/which versions don't have backward compatibility?

**Comment by catfan** [comment]
We added upgrade documentation on official website. You will see the changes while you upgrading to the latest version.

https://medoo.in/api/upgrade

**Comment by CodeBrauer** [comment]
In case anyone searching for older docs for legacy projects:

Here are medoo documentations for older versions (from the beginning)

- 0.9.6: https://web.archive.org/web/20140625044946/http://medoo.in/doc
- 0.9.8: https://web.archive.org/web/20150215213036/http://medoo.in/doc
- 1.0.0: https://web.archive.org/web/20151006114145/http://medoo.in:80/doc
- 1.0.2: https://web.archive.org/web/20160620023645/http://medoo.in:80/doc
- 1.1.1: https://web.archive.org/web/20160702121735/http://medoo.in:80/doc
- 1.1.2: https://web.archive.org/web/20160807170540/http://medoo.in:80/doc
- 1.1.3: https://web.archive.org/web/20160905153430/http://medoo.in:80/doc

**Comment by CodeBrauer** [comment]
In case anyone needs the docs for medoo 1.7 (last version for PHP5.4 - PHP7.2), still installable with composer

There are only the docs online for 1.6.1 (last version crawled by waybackmachine)
So https://web.archive.org/web/20190216193429/https://medoo.in/doc

+ The new features `create()` / `drop()` and mapping are explained in the release note:
https://github.com/catfan/Medoo/releases/tag/v1.7.0
