### ISSUE TITLE
Please consider use <`> instead of <"> to quote

### ISSUE THREAD

**Issue by JunJun-Love-Amber** [catfan/Medoo#508]
**I dont think use <"> is a good idear.when i use the function debug() to print SQL and run it,MySQL can not correctly analyze the <">.** 
please forgive my poor English
ex:
```php

protected function table_quote($table)
{
        return '`' . $this->prefix . $table . '`';
}
protected function column_quote($string)
{
        preg_match('/(\(JSON\)\s*|^#)?([a-zA-Z0-9_]*)\.([a-zA-Z0-9_]*)/', $string, $column_match);
        if (isset($column_match[ 2 ], $column_match[ 3 ]))
        {
            return '``' . $this->prefix . $column_match[ 2 ] . '`.`' . $column_match[ 3 ] . '``';
        }
        return '`' . $string . '`';
}
```

**Comment by tannu13** [comment]
Yeah that is a drag, running it via Command Line, though you can run below command
`SET SQL_MODE = ANSI_QUOTES`
Think, this changes (for the session) your default quotes and the query works :)

**Comment by GAMELASTER** [comment]
Try to pull request :-)

**Comment by synchronized** [comment]
This may be in order to compatible with other databases system, for example SQL server

**Comment by wakerman** [comment]
**Mysql has driven the choice is the case, it should automatically field "to 'comparison Well** :) 💯 
print_r($database->info());
Array
(
    [server] => Uptime: 859629  Threads: 13  Questions: 1649573  Slow queries: 0  Opens: 74168  Flush tables: 1  Open tables: 256  Queries per second avg: 1.918
    [driver] => mysql
    [client] => mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
    [version] => 5.5.40
    [connection] => 192.168.0.24 via TCP/IP
)
**When I use Medoo inquiries， the output similar to this：**

```
SELECT * FROM "rob_orders" WHERE "hidden" = -1 AND "duration" > 0 AND "time" <= 1483588213
```

This will be reported in MySQL syntax errors.
If they can automatically converted to the

```
SELECT * FROM `rob_orders` WHERE `hidden` = -1 AND `duration` > 0 AND `time` <= 1483588213
```

**Comment by wakerman** [comment]
In Mdeoo Lane is running 👍  .
If you want to copy to phpmyadmin would have to convert their own
