### ISSUE TITLE
Use data from select() as object

### ISSUE THREAD

**Issue by mikhailrepka** [catfan/Medoo#516]
Hello, thank you for your code.

I've used before mysql_fetch_object (for example: $user->email), but in Medoo I can't find this way, and forced to use data as array (for example: $user[0]['email']).

How can I use data from DB as objects?
Thank you for attention.

**Comment by mikhailrepka** [comment]
Ok, bad way is
$user = $database->select("users","email",["id" => "1"]);
$user = (object) $user[0];
echo "email: ".$user->email; // result: email: hello@world.com

**Comment by turbopixel** [comment]
Use get() for single data:
```
$user = (object)$database->get("users","email",["id" => "1"]);
```

**Comment by mikhailrepka** [comment]
Anyone?

**Comment by turbopixel** [comment]
I wrote in my new version `(object)$medoo->select()` too. But this is ugly. So I change all positions from `$data->username` to `$data['username']`.

**Comment by maicol07** [comment]
@catfan any news on this feature?

**Comment by t-walker-wei** [comment]
I face the same issue. If no need to change all ` $data->username`  to ` $data['username']` was perfect to me.
