### ISSUE TITLE
Not really an ISSUE but a notice about query() function

### ISSUE THREAD

**Issue by batica81** [catfan/Medoo#518]
When using $database->query() function, it is important to know that an INSERT statement has to be written WITHOUT the trailing semicolon!

So, 
$database->query("INSERT INTO table VALUES (1, 2);");  WILL NOT WORK, 

but
$database->query("INSERT INTO table VALUES (1, 2)"); will work flawlessly.

Thank you for creating such a great tool, and please consider updating the documentation with this small addendum, you might save someone a few hours next time :)

**Comment by turbopixel** [comment]
Where the columns? `INSERT INTO table VALUES (1, 2)`. My query works with and without a semicolon. 
(Use `exec()` for INSERT/UPDATE queries.)

**Comment by smartclash** [comment]
And @catfan I really didn't want to create an issue. But there are some really too much of grammar mistakes in the documentation. I know that your main language is not English. But still, please take care of the grammar. In some places, we couldn't even understand what you are trying to say.

If possible, I will be happy to help you out

**Comment by catfan** [comment]
@smartclash Great! It's very appreciated if you can help it out. You can send me the correct content via email, so that I can update for it :)
