### ISSUE TITLE
Old ORDER syntax in docs

### ISSUE THREAD

**Issue by doodlemeat** [catfan/Medoo#520]
http://medoo.in/api/select

Do a search for ORDER syntax and you notice it uses the old way of writing the ORDER BY clause. Since the docs site don't have a repo I can't make a pull request so I hope author sees this and changes 👍

**Comment by wakerman** [comment]
$database->select("account", "user_id", [
	// Single condition
	"ORDER" => "user_id",
]);

The default is in ascending or descending order ?

**Comment by turbopixel** [comment]
@wakerman @doodlemeat 

```
$database->select("account", "user_id", [
// Single condition
"ORDER" => ["user_id" => "ASC"],
/* or: "ORDER" => ["user_id" => "DESC"], */
]);
```

**Comment by catfan** [comment]
Thanks. It's fixed now.

**Comment by doodlemeat** [comment]
@wakerman I understand how to do it. The docs were just incorrect.
