### ISSUE TITLE
ORDER BY two columns. Result differs from manual SQL query

### ISSUE THREAD

**Issue by Nicero** [catfan/Medoo#523]
I have the following records:

end_date      | position
-------------|------
2017-12-10 |  0  |
2017-12-12 |  10  |
2017-11-10 |  10 |
2017-02-10 |  10 |
2017-12-13 |  10 |
2017-12-23 |  0   |

I want to ORDER them BY `position` AND by `end_date` so I wrote:

    $datas = $database->select("events", "*", ["category" => "music"], ["ORDER" => "position DESC, end_date DESC"]);

But the result given was the following. Records have been ordered by `position` **but not** by `end_date`

end_date      | position
-------------|------
2017-11-10 |  10  |
2017-02-10 |  10  |
2017-12-12 |  10 |
2017-12-13 |  10 |
2017-12-10 |  0 |
2017-12-23 |  0   |

The query written using square brackets as explained in the DOCs generates an error:
`"ORDER" => ["position" => "DESC", "end_date" => "DESC"]`

Whilst the same query typed in phpMyAdmin or HeidiSQL actually ordered the records correctly:

`SELECT * FROM `events` WHERE `category` = "music" order by position DESC, end_date DESC`

end_date      | position
-------------|------
2017-12-13 |  10  |
2017-12-12 |  10  |
2017-11-10 |  10 |
2017-02-10 |  10 |
2017-12-23 |  0 |
2017-12-10 |  0   |

**Comment by tannu13** [comment]
`$datas = $database->select(
    "events",
    "*",
    [
        "AND" => ["category" => "music"],
        "ORDER" => [
            "position" => "DESC",
            "end_date" => "DESC"
        ]
    ],
);`

Was not able to run this but the idea here is that your 'WHERE' clause and the 'ORDER BY' clause (many others) are passed at the **3rd argument's position** under the same array separated by different respective indexes. Even if this doesn't work, 'cause I haven't run this and I make stupid errors that are usually invisible to my naked eye :) but the above info might sort u out.

**Comment by Nicero** [comment]
Thanks for answering. I understand that `WHERE` and `ORDER` must be passed as 3rd argument but I tried many solutions without success:
1. **Warning: Invalid argument supplied for foreach()** 
`$datas = $database->select("eventi", "*", ["AND" => ["category" => "live"], "ORDER" => ["position" => "DESC", "end_date" => "DESC"]]); `

2. **Warning: PDO::quote() expects parameter 1 to be string, array given** 
`$datas = $database->select("eventi", "*", ["AND" => ["category" => "live"], ["ORDER" => ["position" => "DESC", "end_date" => "DESC"]]]); `

3. **This does not report errors but it orders only by the first clause:**
`$datas = $database->select("eventi", "*", ["AND" => ["category" => "live"], "ORDER" => ["position DESC, end_date DESC"]]);`
