### ISSUE TITLE
Return data as object

### ISSUE THREAD

**Issue by Farhan5** [catfan/Medoo#535]
Can I return $medoo->select() or similar methods data as either object or array (array is already given in the example, so Im asking about object availability)?

Its nice to use objects to me:
$person->name;
$person->age;

instead of:
$person['name'];
$person['age'];

Also object takes less characters (2: ->) while array takes double (4: [' ']).

I do not know whether this feature already exists, I haven't used medoo yet. If it is, please put down some examples, docs or docs link here.

Other than, Im badly requesting this feature, its pretty and makes coding faster a bit.

**Comment by catfan** [comment]
```php
$data = $database->select("xxx")...

$object = (object) $data;
```

**Comment by turbopixel** [comment]
#516 - https://github.com/catfan/Medoo/issues/516#issuecomment-273734786

**Comment by Farhan5** [comment]
I also wasn't asking this way, rather an in-built solution.

**Comment by ankush981** [comment]
@catfan For multiple results, this only converts the outermost array to object. Inside, we still have arrays within arrays within arrays . . . Perhaps it'd be better to do a json encode and then decode into objects.

**Comment by sultank1** [comment]
author should provide options for this ... i have faced this issue ... since pdo usually return object ,,it should follow default pdo behaviour ....
