### ISSUE TITLE
Documentation Bug: get() has more params now!

### ISSUE THREAD

**Issue by ghost** [catfan/Medoo#537]
https://github.com/catfan/Medoo/blob/master/src/Medoo.php#L1071

```php
public function get($table, $join = null, $columns = null, $where = null)
```

But the docs claim:
http://medoo.in/api/get

```php
get($table, $columns, $where)
```

**Comment by SteveJobzniak** [comment]
Oh nevermind, the code is doing something really weird and rewrites it automatically so that $join becomes $columns and $columns becomes $where. Bleh.

**Comment by QuantumRevenger** [comment]
I can confirm this bug, it's becoming really annoying because my IDE is reporting errors when in fact there isn't any. A fix much desired ASAP.

**Comment by catfan** [comment]
Fixed it.
