### ISSUE TITLE
只查询一个表时，select()的LIMIT、ORDER功能不可用，及我的临时解决办法

### ISSUE THREAD

**Issue by aiyatee** [catfan/Medoo#538]
英文不好表达，直接上中文。

若想执行如下查询
SELECT "title","hits","tourl","id" FROM "fn_content_1" WHERE ("title" LIKE '%标题%') ORDER by id DESC LIMIT 2,3
用MEDOO，写如下语句：
$db->select("content_1",array("title","hits","tourl",'id'), array("title[~]"=>"标题"),array("LIMIT" =>array(2,3),"ORDER" =>array("id" => "DESC")));

得到的预期查询会是 
SELECT "title","hits","tourl","id" FROM "fn_content_1" WHERE ("title" LIKE '%标题%')

这个根本不是我们所想要的。
特别是用在搜索页面、列表页面，根本就不合适。

经过几个小时的摸索，我临时处理如下：

1、在
`	protected function selectContext($table, $join, &$columns = null, $where = null, $column_fn = null)
	{
		`
后加一行：$where2=$where;

2、把 return 'SELECT ' . $column . ' FROM ' . $table_query . $this->whereClause($where); 改成如下代码：
`			if($columns==$join){//
			$query_add='';//echo count($where2['LIMIT'])."xxx";
				if(count($where2['ORDER'])>0){
					foreach ($where2['ORDER'] as $ok=>$ov){	
					$query_add.=" ORDER by $ok $ov,";//ORDER
					}
				}
				$query_add=trim($query_add,",");
				if(count($where2['LIMIT'])>0){
					$query_add.=" LIMIT ".$where2['LIMIT'][0].','.$where2['LIMIT'][1];
				}
				$query_add=trim($query_add,",");
			}
		return '  SELECT ' . $column . ' FROM ' . $table_query . $this->whereClause($where).$query_add;`

至此，基本上完成我所需要的功能。
发扬共享精神，特发布出来，还望开发者老大能给个更好的方案。

**Comment by catfan** [comment]
Please read the documentation about what the parameters value is seriously.

http://medoo.in/api/select
