### ISSUE TITLE
Fatal error: Class 'Medoo' not found

### ISSUE THREAD

**Issue by jorhel** [catfan/Medoo#543]
structure:
/index.php
/init.php
/Medoo.php

Fatal error: Class 'Medoo' not found in G:\Proyectos\PecadoIntimo\htdocs\init.php on line 16

Editing the file Medoo.php i add a variable and can read the content on init.php, but Medoo Class not.

**Comment by catfan** [comment]
Check the PHP version (should be PHP 5.4+ for v1.2), and read the documentation on how to install and load Medoo.

**Comment by johnnycsy** [comment]
7.1.7也出现这样的问题
