### ISSUE TITLE
[MAJOR SECURITY FLAW] GET Statement returns first row when 'where' value is empty!

### ISSUE THREAD

**Issue by QuantumRevenger** [catfan/Medoo#546]
$emptyString = null;
        $record = $database->get('table', [
            'column'
        ],[
            'where' => $emptyString
        ]);

returns first row of table! It should never return a result because it does not match anything.

**Comment by catfan** [comment]
What's data you get for this statement? The `get()` method will return `false` if not match anything.

And in your case, you should not assign value for `'where' => xxx`, if you don't have a column named `where`
