### ISSUE TITLE
Select Query Output Problem when using Table Join queries

### ISSUE THREAD

**Issue by ghost** [catfan/Medoo#547]
Hello!

I recently stumbled upon an issue when using the select query with table join.
Here's the code I used:

$this->db->select('bookings', [
            '[><]jobs' => ['jobid' => 'id'],
            '[>]works' => ['workid' => 'id'],
            '[>]employees' => ['works.employeeid' => 'id'],
        ], [
            'bookings.id',
            'bookings.targetdate',
            'job' => [
                'jobs.title',
                'jobs.description',
            ],
            'work' => [
                'works.id',
                'works.status',
                'employee' => [
                    'employees.firstName',
                    'employees.lastName',
                ],
            ],
        ], [
            'bookings.userid' => $args['id'],
            'ORDER' => ['bookings.targetdate' => 'ASC'],
        ]);`

The problem is, as you can see, the output columns should have two columns with the 'id' column name (one for bookings.id, and works.id). What happens is that the values for both of these column are the same. Their values will follow the value of the last column using the 'id' name, in this case, work.id

However, using the SQL T version of this, the resulting columns were properly dstinguished (no column overlapping). 
Here's the code I used for the SQL Transact query

`SELECT bookings.id,
	bookings.targetdate,
    job.title,
    job.description,
    work.id,
    work.status,
    employee.firstName,
    employee.lastName
	FROM bookings
    INNER JOIN job
    	ON bookings.jobid = job.id
    LEFT JOIN work
    	ON work.id = bookings.workid
    LEFT JOIN employee
    	ON employee.id = work.employeeid
    WHERE bookings.userid=1
    ORDER BY bookings.targetdate ASC`

So i think the problem lies in the processing of the results? 
Although work.id and bookings.id have the same column name, this case 'id', they should still be distinguished from what table they came from since it was explicitly written there that one id should come from bookings, and the other was from work

The current fix i'm using is renaming the output col names to distinguish does two similarly named columns, which kinda defeats the purpose of transforming the resulting columns into an array of sorts (to properly differentiate them i guess)

Is this really a bug?

PS: i'm converting the output into JSON that's why i need the result to be transformed into an array

--
EDIT:
This seems to be a PDO related issue, i just confirmed it after delving further :(
though i don't know why phpmyadmin outputs the columns propery :(

**Comment by acumpab** [comment]
I am having the same trouble

**Comment by mBabbage** [comment]
Having the same issue
