### ISSUE TITLE
memory exhausted when insert a large quantity of data

### ISSUE THREAD

**Issue by imaginezz** [catfan/Medoo#548]
When I insert a large quantity of data(about 2915000), the php cli  throw an exception
`
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to al
locate 20480 bytes) in /srv/app/cli/php/vendor/catfan/medoo/src/Medoo.p
hp on line 971
`

**Comment by km3945** [comment]
In the CLI mode need to be modified. Mainly to do the 
```php
	// Variable
	protected $logs = [];

related changes

**Comment by catfan** [comment]
We supported LOB data type for inserting large quantity data on develop branch here: 94f293d6

**Comment by imaginezz** [comment]
Thank you, i will try it .
