### ISSUE TITLE
[ENHANCEMENT] Code does not follow PSR-1 or PSR-2

### ISSUE THREAD

**Issue by smartclash** [catfan/Medoo#552]
Hi @catfan ,

Medoo is a simple and awesome project. Every feature is tight-packed into a single class. I agree that point. But the more features getting added, the code style really varies from one line to another, one function to another.

To prevent this, please either use PSR-1 or PSR-2 code fixer implemented by symfony or simply create an account at styleci.io and it will take care of every thing.

And, most important thing, Nowadays, IDE's all believe in PHPDoc and all rely on them for code-completion and suggestions. Just launch up PHPDocGenerator and let it do the hard work for you.

**Comment by rakshazi** [comment]
good idea!
@catfan use PHP CS Fixer v2, please

**Comment by Glennmen** [comment]
Indeed please enforce PSR-2
