### ISSUE TITLE
update return 0 if dont change data?

### ISSUE THREAD

**Issue by betany** [catfan/Medoo#559]
i use function like this:
   ```
 $affected_row=$database->update("pages", [
        "Page_Title" => $Input_Title,
        "Page_Content" => $Input_Content,
        "Modify_Date" => $NOW_DATE
    ], [
        "AND" => [
            "Page_Id" => $Input_Id,
            "Page_Id[!]" => NULL
        ]
    ]);
```
it returns 0.
it work only if i change on of the column (Page_Title or Page_Content)
why i cant update table with same previous data?

**Comment by timbotron** [comment]
I think it's a SQL thing. It knows that it doesn't need to actually run the UPDATE statement if nothing would change, so it doesn't affect any rows.

**Comment by turbopixel** [comment]
I think there is an option called FLAG_FOUND_ROWS

**Comment by catfan** [comment]
Medoo 1.4 is now return the PDOStatement. You can call rowCount() to get the affected row number. If nothing changed, it returns 0 of course.

**Comment by betany** [comment]
thanks. can i replace medoo latest version with all older versions.i use medoo last year in one of my projects.
also i know should use medoo namespace in new version
