### ISSUE TITLE
when select "*" get a php warning

### ISSUE THREAD

**Issue by fax001** [catfan/Medoo#564]
Use medoo 1.4

$database->select("account","*", [
	"user_id[>]" => 100
]);

A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: src/Medoo.php

Line Number: 935

**Comment by catfan** [comment]
Well, fixed it. But we always recommended that don't use `*` for fetching all columns data. It's no good for the performance and readability.

**Comment by rakshazi** [comment]
@catfan release bugfix as new version (eg: `1.4.1`), please

**Comment by rakshazi** [comment]
@catfan any update on this?

**Comment by anaggh** [comment]
Medoo v1.4.1 was released - https://github.com/catfan/Medoo/releases

**Comment by rakshazi** [comment]
@anaggh thank you! Didn't notice it
