### ISSUE TITLE
1.4 exec() - missing $map

### ISSUE THREAD

**Issue by turbopixel** [catfan/Medoo#565]
We use ´exec()` in our system. Now the method is exploding, because $map is not set. 
I think a default value is missing

> 2017/05/11 13:46:51 [error] 26062#26062: *19052 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Medoo\Medoo::exec(), 1 passed in /var/www/....

**Comment by catfan** [comment]
In fact, `exec()` is an undocumented API for special usage. The old version is `exec()` is a short cut for `PDO::exec`, but for the 1.4, `exec()` is `PDOStatement::execute` for prepared statement. It will be different result.

It's OK for me to make it work again without $map parameter. I will fix for it soon. But for correct `exec()` call like old version, you may use `$database->pdo->exec()` instead.

**Comment by catfan** [comment]
b5f9f60

**Comment by turbopixel** [comment]
Thanks!
`$database->pdo->exec()` is a good compromise for both, I think.
