### ISSUE TITLE
Insert having  wrong values 

### ISSUE THREAD

**Issue by ParshvaZymr** [catfan/Medoo#569]
My file 

`<?php 
require 'Medoo/src/Medoo.php';
// Using Medoo namespace
use Medoo\Medoo;
// Initialize
$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => 'account',
    'server' => 'localhost',
    'username' => 'root',
    'password' => ''
]);
$newTokenArr=array('emp_number' => '75','token'  => '10');
$database->insert("api_token",$newTokenArr);
var_dump( $database->log() );
exit;
?>`

 

Result 

> array(1) {
  [0]=>
  string(67) "INSERT INTO "api_token" ("emp_number", "token") VALUES ('10', '10')"
}

Issue: 
While there is emp_number is 75 it is taking my token value. i.e. 10 My medoo version in 1.4.1. Also, the same values are inserting in my database 10,10 instead of 75,10. I think there is some issue insert

**Comment by anaggh** [comment]
I can confirm this bug exists when running Medoo v1.4 or v1.4.1 on Windows 7 (xampp-win32-7.1.2-0-VC14-installer) to be specific. When I tried it again on Ubuntu XAMPP, the bug does not occur. @catfan Is Medoo supported on Windows?

**Comment by catfan** [comment]
@anaggh I cannot reproduce this case. Would you like to show the code you are using also? And how about your PHP version?

**Comment by ParshvaZymr** [comment]
Hi @catfan  Here are my xampp version detail 

![image](https://cloud.githubusercontent.com/assets/13659637/26047513/1a62f1d0-3971-11e7-8e8c-83c5a09622ab.png)

**Comment by catfan** [comment]
Well, I checked out about this case. The problem may be about the `uniqid()` bug on PHP, especially on XAMPP.

You can try this code on your server:
```php
<?php
var_dump(uniqid());
var_dump(uniqid());
?>
```
If two those output number are the same, that is problem.

@ParshvaZymr @anaggh Would you like to run the code, and show the output here?

**Comment by anaggh** [comment]
@catfan PHP v7.1.2

XAMPP Windows 7:
```
string(13) "591963f924c4a" string(13) "591963f924c4a"
```

XAMPP Ubuntu
```
string(13) "591964458e9b3" string(13) "591964458eba1" 
```

**Comment by catfan** [comment]
@anaggh OK, thank you. That's the point. I will fix for it.

**Comment by ParshvaZymr** [comment]
Yes, it is working from develop branch... Thanks

**Comment by anaggh** [comment]
Btw, this is not a XAMPP related bug. It is a Windows related bug. Even XAMPP alternatives (on Windows) would be affected.

From http://php.net/manual/en/function.uniqid.php
```
Warning

This function does not guarantee uniqueness of return value. Since most systems adjust system clock by NTP or like, system time is changed constantly. Therefore, it is possible that this function does not return unique ID for the process/thread. Use more_entropy to increase likelihood of uniqueness.
```

**Comment by catfan** [comment]
@anaggh I tested on my PC. Win10 64 bit + PHP 7.1 TS VC14 is no problem with this.

**Comment by anaggh** [comment]
Maybe it is Windows 7 related then. I tried `var_dump(uniqid());` again on DokuWiki MicroApache (Windows) WebServer (https://download.dokuwiki.org/) and it was returning the same ID. Anyway, thank you for fixing! <3
