### ISSUE TITLE
Update not working as documented

### ISSUE THREAD

**Issue by Kickupx** [catfan/Medoo#571]
`$db->update('table', ['col' => 42], ['col' => 41]);`
generates the following query:

UPDATE "table" SET "col" = 41 WHERE "col" = 41

I expect the set value to be 42.

**Comment by catfan** [comment]
This is the bug about #569.

We have fixed it and release a new version for this case.

**Comment by Kickupx** [comment]
Oh sorry, I guess my search skills needs an update^^
