### ISSUE TITLE
DSN Connection in Medoo

### ISSUE THREAD

**Issue by hanns08** [catfan/Medoo#572]
How to write DSN Connection in medoo.  I am using MSSQL server.

$database = new medoo([
    
    'dsn' => [
       
        'driver' => 'SQLSERVER',
       
        'server' => '.',
        'port' => '8886'
    ],
    
    'database_type' => 'sql',
 
    'username' => 'sa',
    'password' => 'xxxxx'
]);

that is mine connection, and it came error "invalid data source name"
please tell me how to solve this problem

**Comment by catfan** [comment]
Just check out the documentation.

`dsn` option is for building customized DSN string, but for most case, just change the `database_type` to `mssql` and config the correct server, username, password or port. It it enough.
