### ISSUE TITLE
Using insert ['#datecol' => 'NOW()'] not working in 1.4.2

### ISSUE THREAD

**Issue by skylarmt** [catfan/Medoo#574]
When I run:  
`$database->debug()->insert("table", ['#datecol' => 'NOW()', 'othercol' => $var])`  
I get:  
`INSERT INTO "table" ("datecol", "othercol") VALUES ('NOW()', 123)`.

This results in a datetime of `0000-00-00 00:00:00` in my table, which breaks things.  This began when I upgraded from 1.2.1 to 1.4.2.

**Comment by catfan** [comment]
OK, thanks for report that. It is a bug, and will be fixed soon.

But Medoo will have a new way for handling all SQL functions and raw queries on next version.

BTW, using PHP `date()` to get current time is better than using `NOW()` SQL function for this case.
