### ISSUE TITLE
select [Number] does not return floating point, truncates to integer

### ISSUE THREAD

**Issue by bits-of-static** [catfan/Medoo#580]
`var_dump` from a double-float column. 
Once defined for select as `'time [Number]'` the other as `'time'`.

string(15) "1496468069.4663"
int(1496468069)

**Comment by bits-of-static** [comment]
change line 992 (or seek for `case 'Number'`) to:
```
case 'Number':
	$stack[ $column_key ] = (double) $data[ $column_key ];
	break;
```

**Comment by JeansReal** [comment]
Same here!

**Comment by Bust3D** [comment]
The change on case 'Number': working fine if the numbers are bigger than 1.
all range between 0.01 - 0.99 returning 0

Is there a fix for this issue too ?
