### ISSUE TITLE
medoo debug mode generated sql not work

### ISSUE THREAD

**Issue by betany** [catfan/Medoo#584]
i use medoo debug mode and generated sql is here:
SELECT * FROM "orders" WHERE "Order_Status" != 'ONSTART' AND ("Order_System_Date" BETWEEN '۱۳۹۶/۰۳/۲۰' AND '۱۳۹۶/۰۳/۲۱')
but when i copy and past it in phpmyadmin it says:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"orders" WHERE "Order_Status" != 'ONSTART' AND ("Order_System_Date" BETWEEN 'Û±' at line 1 
 
why this happens?

**Comment by catfan** [comment]
We not encourage to execute the generated SQL directly. This problem is about the database default quote identifier. v1.5 will output with this.
