### ISSUE TITLE
Publicly expose $prefix property

### ISSUE THREAD

**Issue by CameronJThomas** [catfan/Medoo#594]
Would it be possible to change the `$prefix` property from `protected` to `public` so it can be retrieved again later on? As the prefix is not automatically applied to custom queries through the `query()` function, I am having to separately pass the `$prefix` property around my application through another variable, which seems a bit pointless when it would be so easy to access directly from the `$database` object.

Alternatively, if you do not wish for the `$prefix` property to be overridden once the object is created, you could always keep it `protected` and add a `get_prefix()` function to retrieve it.

This should be a quick change to make, so would be great to see in the near future if you are happy to implement.

**Comment by catfan** [comment]
If you want to use the $prefix, why do not just define the prefix alone and sent it for Medoo initialization? So you can access anywhere without asking Medoo.

```php
define("PREFIX", "PR_");
// or
$prefix = "PR_";

$database = new Medoo([
	// ...
	'prefix' => $prefix
]);

$database->query("SELECT $prefix ....");

// vs

$prefix = $database->prefix();
$database->query("SELECT $prefix ....");
```

**Comment by CameronJThomas** [comment]
Thanks for your response. I should probably elaborate a little on the structure of my app.

In order to restrict access to the database object by third party plugins, I am keeping it private (rather than using globals/constants/etc.) and passing it between my application's classes via the constructors like so:

```
$database = new Medoo([...]);

$my_class = new My_Class( $database );
```

But currently I am having to pass through two separate variables, i.e.:

`$my_class = new My_Class( $database, $prefix );`

This is of course not a major issue, but it would be much cleaner for me to just pass through the `$database` object and then have each class retrieve the prefix from there, rather than clogging up my constructors.
