### ISSUE TITLE
Auto generate the Response

### ISSUE THREAD

**Issue by errkranjan** [catfan/Medoo#596]
User expects some output after any Sql exectute. But medoo doesn't output anything after insert weather Insert is executed or not.

**Comment by catfan** [comment]
`insert()` and `update()` returns the PDOStatement object, so you can use its methods to get more information. 

```
$data = $database->update("account", [
	"age[+]" => 1
], [
	"user_id[>]" => 100
]);
 
// Returns the number of rows affected by the last SQL statement
echo $data->rowCount();
```
