### ISSUE TITLE
Group by in select query

### ISSUE THREAD

**Issue by Philippe-M** [catfan/Medoo#599]
Hello, it's possible in the next release to add a GROUP BY criteria in select query  ?

**Comment by BrianMoreno1994** [comment]
Medoo already supports Group By, example code from the docs:

```
$database->select("account", "user_id", [
        // GROUP by single value
	'GROUP' => 'type',
 
	// GROUP by array of values
	'GROUP' => [
		'type',
		'age',
		'gender'
	],
 
	// Must have to use it with GROUP together
	'HAVING' => [
		'user_id[>]' => 500
	]
]);
```

[https://medoo.in/api/where](https://medoo.in/api/where)

**Comment by Philippe-M** [comment]
oupss, Sorry I had not seen this in the doc.
