### ISSUE TITLE
Don't work with cyrillic symbols

### ISSUE THREAD

**Issue by inlanger** [catfan/Medoo#6]
I tried to get some cyrillic data from MySQL test database, but instead of my data I got "??? ????? ??????". I tried on two different servers(MacOS and Debian) - the situation is the same.

**Comment by verybigelephants** [comment]
i am having exactly the same problem. central european characters, such as čšľ
 that are stored in an utf postgres database are returned as question marks by medoo (but returned fine with other wrappers)

**Comment by psy21d** [comment]
WITH cyrillic symbols ?????????
framework that not work with utf8 == 'crap framework'

DELETE

**Comment by jnachtigall** [comment]
@catfan FWIW, I also get wrong characters when using Medoo and `query` with mysql. Using the same query with PDO and `prepare` the encoding is just fine. This happens for terms like e.g. `Äthiopien`. Umlauts like Ö, ö, ü, Ü, Ä, ä or ß are very common in German.

**Comment by verybigelephants** [comment]
this needs to get reopen. it stores bad utf-8 characters

**Comment by negrusti** [comment]
@catfan just got hit by this. UTF-8 must be default

**Comment by catfan** [comment]
@negrusti The charset setting is up to your project. Somewhere will need utf8 as default but somewhere will need utf8mb4 as default for supporting emoji. It cannot make a default charset for every situations.

The better way is setting the charset on database's configuration file.
