### ISSUE TITLE
last_query() 方法废弃了吗

### ISSUE THREAD

**Issue by charm-v** [catfan/Medoo#601]
last_query() 方法废弃了吗？文档上写的有last_query()方法，但是代码中却没有

**Comment by charm-v** [comment]
噢~找到了last()方法，希望能更新文档

**Comment by catfan** [comment]
Please read our official documentation website: https://medoo.in

**Comment by charm-v** [comment]
OK，Thx~

**Comment by charm-v** [comment]
I search Baidu in Medoo, see the first is [http://medoo.lvtao.net/](url), think this is your official website, now know the real website address.23333333~

**Comment by catfan** [comment]
This is not our website!!! **We strongly** recommend that do not read this non-official one. It's completely outdated and with a lot of mistake.

**Comment by charm-v** [comment]
OK, thanks
