### ISSUE TITLE
Using [<>] and [><] with portion of datetime

### ISSUE THREAD

**Issue by nealoke** [catfan/Medoo#603]
I'm wondering if I could use the `[<>]` and `[><]` with only a part of the date. I would like to filter a column named `birthday` which contains the whole birthday date of a person. I need to retrieve only the people who have their birthday on a certain date (eg. filtering on `month` and `day`, not on `year`).

Is this possible with the current version?

**Comment by Andrews54757** [comment]
https://www.w3schools.com/sql/sql_like.asp

@nealoke  Use like to run a query using wildcards.

```php
$Medoo->select('table',['birthday'],[
    'birthday[~]' => '%MM-DD'
]); // SELECT birthday FROM table WHERE birthday LIKE %MM-DD
```

**Comment by nealoke** [comment]
Thanks! I'll have a look at it as soon as I can :)
