### ISSUE TITLE
[1.4.5] Replace documentation error?

### ISSUE THREAD

**Issue by patrickvane** [catfan/Medoo#605]
In replace(), it seems the expected input is [valueFrom, valueTo] instead of [valueFrom => valueTo]?

This is weird, because in the documentation (https://medoo.in/api/replace) it says it should be [from => to], but the actual code ignores the keys, and just expects arrays with [from, to] instead. 

Is the documentation wrong, or is the code not working as it was intended?

**Comment by mbrowngold** [comment]
I've noticed this as well.

**Comment by catfan** [comment]
It's now fixed.
