### ISSUE TITLE
Why does this framework escape with double quotes?

### ISSUE THREAD

**Issue by Woeler** [catfan/Medoo#606]
Wanted to use this framework. Then I found out it forces the use of double quotes. My question is, why? This renders the whole thing unusable on many shared hosting solutions.

Frameworks should abide to the rules of the software they run on, not the other way around.

**Comment by catfan** [comment]
This issue have been discussed too many times here. We use SQL-92 standard for compatible with other database. Check out the initialization core and you will find out the initial connection command for using this standard, which also can make the Medoo generated query executable alone.

And also, it is strange that to execute the Medoo generated query alone on another place if you can run the Medoo core successfully. Medoo is not a SQL generator. `log()` is only for logging.
