### ISSUE TITLE
protected $logging = false; to public $logging = false;

### ISSUE THREAD

**Issue by km3945** [catfan/Medoo#610]
I just want to record all SQL at DEBUG.

protected $logging = false;
to:
public $logging = false;

```php
function getAll($debug=false){
	$this->db->logging = $debug;
	
	$this->db->select('test');
	$this->db->select('test1');
	$this->db->select('test2');
	
	if($debug){
		$sql=$this->db->log();
		die('<pre>'.htmlspecialchars(print_r(get_defined_vars(), true)).'</pre>');
	}
}

**Comment by catfan** [comment]
In what kind of situation you need to enable and disable logging while running the code and don't not make logging enable / disable on Medoo initialization?

**Comment by Andrews54757** [comment]
@km3945 If you want that, you can change it in your own copy too. No need to edit the main repo
