### ISSUE TITLE
Query didn't correct when a column type is timestamp.

### ISSUE THREAD

**Issue by bluestonemds** [catfan/Medoo#614]
this query return array(0)

`$result = $this->db->select("ac_order",[
            "card_num",
           "order_date
        ], [
            "order_date[>]" => '2017-08-01'
        ]);`

> order_date column type is timestamp

**Comment by Andrews54757** [comment]
@bluestonemds It should work: https://github.com/catfan/Medoo/blob/master/src/Medoo.php#L572-L588

**Comment by bluestonemds** [comment]
@Andrews54757 thank you for your help.  I finally know the error how to happen. below is my query code:
`$result = $this->db->select("ac_order",
                                       [ "card_num", "order_date ],
                                       ["and" => [
                                              [ "order_date[>]" => '2017-08-01' ]),
                                              ["pay"] => '1'
                                                         ]
                                                          ]);`

it should not work. but I capitalize the 'and'  to 'AND', the query worked well. the issue don't happen to the early version of MEDOO, like 1.1.2.

**Comment by Andrews54757** [comment]
@bluestonemds Yes, the casing is confusing. Would be better if everything was lowercase. In fact, I am having a conversation with catfan about it here: #609
