### ISSUE TITLE
多表查询出错

### ISSUE THREAD

**Issue by 596868636** [catfan/Medoo#615]
多表查询出错
PDOStatement {#17 ▼
  +queryString: "select e.id,e.name,d.name pd from pl_employee as e,pl_department as d where e.no="C001" and e.org_id=d.id and d.no="S000044" and e.deleted=0 limit 1"
  errorInfo: array:3 [▼
    0 => "42S22"
    1 => 1054
    2 => "Unknown column 'C001' in 'where clause'"
  ]
}

求解，已经更换了项目中的所有sql ，突然发现多表查询有错，悲剧，急急

**Comment by 596868636** [comment]
@catfan

**Comment by 596868636** [comment]
貌似我发现，其实是"C001"  双引号导致的，这个没做处理

**Comment by catfan** [comment]
Search before issuing, and nothing sufficient information provided. Closed.
