### ISSUE TITLE
Table left outer join

### ISSUE THREAD

**Issue by StefansArya** [catfan/Medoo#618]
Hi,
Can you implement [LEFT OUTER JOIN](https://stackoverflow.com/a/2479671/6563200) for the select API?
If a table doesn't contain related id, it will return null instead of empty string..

**users**
```
| user_id | username      |
| 123     | myusername    |
| 126     | otherusername |
```

**data**
```
| user_id | realname    |
| 126     | otherperson |
```

**Example 1**
`SELECT "data"."realname","users"."user_id" FROM "users" LEFT OUTER JOIN "data" ON "users"."user_id" = "data"."user_id" WHERE "users"."username" = 'myusername'`

Expected output
```
[
    ["realname"=>null, "user_id"=>123]
]
```

**Example 2**
`SELECT "data"."realname","users"."user_id" FROM "users" LEFT OUTER JOIN "data" ON "users"."user_id" = "data"."user_id" WHERE "users"."username" = 'otherusername'`

Expected output
```
[
    ["realname"=>"otherperson", "user_id"=>126]
]
```

**Comment by StefansArya** [comment]
Add in [this line](https://github.com/catfan/Medoo/blob/master/src/Medoo.php#L826)

**Comment by Andrews54757** [comment]
@StefansArya What would be the key? `<>`, `><`, `>`, and `<` are already taken.

**Comment by StefansArya** [comment]
Maybe `>~`

The regex will be
`(\[(?<join>\<|\>|\>\<|\<\>|\>\~)\])?(?<table>[a-zA-Z0-9_]+)\s?(\((?<alias>[a-zA-Z0-9_]+)\))?`

**Comment by Andrews54757** [comment]
@StefansArya Okay then, make a pull request. Catfan then can merge it later

**Comment by catfan** [comment]
@Andrews54757 @StefansArya No. This feature is acceptable, but please don't make a pull request. We can not make a final syntax decision from now. Need time to think around.

**Comment by StefansArya** [comment]
@catfan Yeah, I know that I don't need to create pull request. I already feel it when I dive into your library..
Anyway, thanks for your time!

**Comment by Andrews54757** [comment]
@catfan I suggest using the [PEAR](http://www.sourceformat.com/coding-standard-php-pear.htm)  format.

**Comment by catfan** [comment]
I checked out the manual. The `LEFT JOIN` is the same as `LEFT OUTER JOIN`. So, it don't need to implement the OUTER as option.

https://dev.mysql.com/doc/refman/5.7/en/join.html
