### ISSUE TITLE
Addition of array typing in defining parameters of methods that use data of type array.

### ISSUE THREAD

**Issue by efrj** [catfan/Medoo#621]
@catfan , I did a pull request without first opening a new issue.
I added the array typing in the call of the parameters of the methods that request data of type array.
I think the code should be compatible with PHP 7 to the max.
# Example:
```
<?php
class Medoo
{
    public function __construct(array $options = null)
    {
    }

    public function query($query, array $map = [])
    {
    }
}
```

### The Pull request ID is #620.

**Comment by catfan** [comment]
I don't think this is really need for this case right now. There is no great improvement if provided the type definition, and some parameter type of Medoo are changeable that like `get($table, $columns, $where)`, the $columns can be array or string.

This is a good suggestion, but I think it need more time to be tested, reviewed and considered.
