### ISSUE TITLE
Data Type Declaration doesnt work when using alias of multiple tables (on v1.4.5)

### ISSUE THREAD

**Issue by superdeeid** [catfan/Medoo#624]
This is a great feature i must agree... but, when making a join tables with alias, it does ommit the type declaration. the query still work but the int are still returned as string.

**Comment by catfan** [comment]
It fixed on v1.5 794ae2ec1b10c965374293b6ee5a480adce4d4d7 that support using alias and type declaration together.

**Comment by superdeeid** [comment]
Any plan to release it to master soon ?

**Comment by catfan** [comment]
@superdeeid Not yet. But if you really need, you can check out the v1.5 branch to use it.

**Comment by Andrews54757** [comment]
@superdeeid Or, you can use another tool. I suggest one called [SuperSQL](https://github.com/ThreeLetters/SuperSQL). It is much more faster, efficient, and advanced than Medoo.

![speed](https://user-images.githubusercontent.com/13282284/30243699-b4c76e32-957d-11e7-9bdb-ec96f53816b1.png)

**Comment by catfan** [comment]
@Andrews54757 I don't think it is really polite and appropriate to advertise your own project here. If you want to introduce for this, you can do it on HackerNews or other technological community.

Thanks!

**Comment by Andrews54757** [comment]
@catfan It was just a suggestion. I was inspired by your project to create an even better one. My comment was not off-topic nor was it extremely advertisy. It was a suggestion. I have nothing to gain. Its not like I can gain money from it.

**Comment by catfan** [comment]
@Andrews54757 It is honored for me. But that not mean you can post this kind of off-topic and spam advertising message to promote your product here. Here is the place talking about Medoo project ONLY. You are disturbing the community.

Please stop posting this kind of message again!

Thanks for your cooperation.

**Comment by superdeeid** [comment]
i must agree with Catfan. this is not the place to talk about something else here. Medoo is great for my needs and do more than i need. Loved his way of doing syntax structure.

@catfan : i'll wait to the official release to update it since anyway my current project use 1.4.5 and i test the value with (int)variable already. On furthers projects, if 1.5.0 is out, i'll use the proper way.
