### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by brownsugar** [catfan/Medoo#629]
https://medoo.in/api/where
At 'Basic Condition' L37:
```
$database->select("account", "user_name", [
	"birthday[><]" => [date("Y-m-d", mktime(0, 0, 0, 1, 1, 2015)), date("Y-m-d")]
]);
```
Which should generate:
WHERE "`birthday`" `NOT` BETWEEN '2015-01-01' AND '2015-05-01' (now)

However, L40 says:
```
//WHERE "create_date" BETWEEN '2015-01-01' AND '2015-05-01' (now)
```

**Comment by catfan** [comment]
Thanks for that. It fixed now.
