### ISSUE TITLE
replace is not working

### ISSUE THREAD

**Issue by adminko-svk** [catfan/Medoo#632]
Hello Angel,
replace function is not working.

Example code from https://medoo.in/api/replace is executed as:
`UPDATE "account" SET "type" = REPLACE("type", '', ''), "column" = REPLACE("column", '', '') WHERE "user_id" > 1000`
So without values to replace.

**Comment by catfan** [comment]
Yes, it is a bug. It fixed on 0ae17978b1b8.

**Comment by adminko-svk** [comment]
Thanks, can you create stable version 1.4.6?

**Comment by catfan** [comment]
@adminko-svk it will possibly be with v1.5 soon.
