### ISSUE TITLE
Group by not working

### ISSUE THREAD

**Issue by akahen** [catfan/Medoo#635]
Hi, the 'GROUP' with aggregate is not working both simple (i.e. count) and more importantly this:

select account, sum(amount), from table group by account

thanks

**Comment by Andrews54757** [comment]
@akahen Medoo doesnt support this. Sorry.

**Comment by catfan** [comment]
This will be supported on next version `v1.5`. You may check out this branch and try it.

```php
$database->select('table', [
	'account',
	'sum' => Medoo::raw('SUM(<amount>)')
], [
	'GROUP' => 'account'
]);
// SELECT "account", SUM("amount") AS "sum" FROM "table" GROUP BY "account"
```

**Comment by akahen** [comment]
That's great, yet that will allow only one sum or aggregate function per select. Why not take the actual column name for the implicit 'as'.

Thanks

On Sep 29, 2017 10:13 PM, Catfan <notifications@github.com> wrote:

This will be supported on next version v1.5. You may check out this branch and try it.

$database->select('table', [
        'account',
        'sum' => Medoo::raw('SUM(<amount>)')
], [
        'GROUP' => 'account'
]);
// SELECT "account", SUM("amount") AS "sum" FROM "table" GROUP BY "account"

**Comment by catfan** [comment]
@akahen That's will be a problem and confusing if it become more complex operation.

```php
$database->select('table', [
        'account',
        'sum' => Medoo::raw('SUM(<amount> + <age> + <weight>)')
], [
        'GROUP' => 'account'
]);
```

**Comment by akahen** [comment]
hi, will this support an additional aggregate like below? thanks
$database->select('table', [
        'account',
        'sum' => Medoo::raw('SUM(<amount> + <age> + <weight>)'),
        'sum2' => Medoo::raw('SUM(<amount>)')
], [
        'GROUP' => 'account'
]);

**Comment by catfan** [comment]
@akahen definitely

**Comment by akahen** [comment]
awesome, thanks.
can you please update composer as well?
thanks
