### ISSUE TITLE
Request feature to pass PDO object to constructor

### ISSUE THREAD

**Issue by kaala** [catfan/Medoo#636]
At the moment, I work out with subclass the Medoo, but this kind of hack may broken in future release.
Please consider add another constructor that can provide raw PDO object, this would great improve the feasible.

```

use Medoo\Medoo;

class Medoo2 extends Medoo {

    function __construct($type, $pdo) {
        $this->database_type = $type;
        $this->pdo = $pdo;
    }

}

```

**Comment by catfan** [comment]
Medoo initialization not only create PDO object, but also initialize more additional option for whole framework. Providing raw PDO object only is not enough.
