### ISSUE TITLE
Query with php string variable in OR

### ISSUE THREAD

**Issue by dagobertdebug** [catfan/Medoo#637]
Hi

```
$database->select("account", "user_name", [
	"OR" => [
		"user_id" => [2, 123, 234, 54]
	]
]);
```
I want to query with a php string variable instead of 2, 123, 234, 54 

$values = "2, 123, 234, 54";

```
$database->select("account", "user_name", [
	"OR" => [
		"user_id" => [$values]
	]
]);
```

I tried "'2',' 123', '234', '54'" but it did not work.

Any idea how to solve this?
Thanks and cheers
Dago

**Comment by catfan** [comment]
No, string is string, array is array. It's clear enough with this.

And it's very convenient to convert string and array on PHP using `implode()` and `explode()`, why need this kind of change?

**Comment by dagobertdebug** [comment]
hello catfan, thanks for your prompt reply. 

I am not asking for a change, I more ask for support as an expert. I tried implode/explode, but the values are always recognised as one value, and not several comma separated values.

So for example, the following code is working: 

`["OR" => ["site" => [24,25,26]]`

But 24,25,26 is not hardcoded, I get the data dynamically as a string "24,25,26", but it can be "343,754,847,485" as well, you know what i mean?

And when i get the data as a string, I have to pass it as a string to the WHERE clause. But it is not recognised.

`$data= "23,24,25`;
`["OR" => ["site" => [$data]]`

All I want is to pass the data which is dynamically. 

Can you help please?

**Comment by Andrews54757** [comment]
@dagobertdebug 


```php
$database->select("account", "user_name", [
	"OR" => [
		"user_id" => explode(',',$values)
	]
]);
```

**Comment by catfan** [comment]
@dagobertdebug No, the only way for this case is convert it as array, like using `explode()`. You have to do it yourself.

We don't know what's your string determinator, and what if someone really want to use the string value for querying or inserting with comma?

**Comment by dagobertdebug** [comment]
@Andrews54757: Thanks, that's the solution! Easy, and I learned something. Thanks!

@catfan Thanks for your support and this great library.

Cheers 
Dago
