### ISSUE TITLE
max_user_connections Error When Connecting Users

### ISSUE THREAD

**Issue by naghibi-farshad** [catfan/Medoo#638]
See the following error message when connecting users :

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'SQLSTATE[HY000] [1203] 
User DB_USER already has more than 'max_user_connections' active connections' in .../public_html/includes/classes/Medoo.php:203
```

You have a solution for this Problem?

**Comment by kuofp** [comment]
Not a medoo problem.
It's relate to `max_user_connections` and `max_connections` config setting.
Check  out:
https://stackoverflow.com/questions/11767487/disable-max-user-connections-limits
https://stackoverflow.com/questions/11183727/how-to-solve-mysql-max-user-connections-error
