### ISSUE TITLE
multi insert

### ISSUE THREAD

**Issue by roydekleijn** [catfan/Medoo#640]
Hi,

How much faster is multi insert? are there some statistics on it ?

Which of the following is more efficient?
1 at a time,
10 at a time,
100 at a time

something else?

Thanks,
R

**Comment by Andrews54757** [comment]
@roydekleijn If you want efficiency, dont use Medoo. Medoo is an abstraction layer for those who dont know much about sql. I do not think you would need high-performing tools. If so, then use those provided by frameworks such as Laravel.

**Comment by catfan** [comment]
We optimized multiple insertion with one query as possible. For most of time, the speed for any database operations are based on the database engine or the machine itself, not the framework.
