### ISSUE TITLE
Insert is broken...?

### ISSUE THREAD

**Issue by BrianMoreno1994** [catfan/Medoo#643]
I'm trying to insert data into a table like this:

   ```
$database->insert("cart", [
    'user_id' => '7',
    'created_at' => time()
]);
```

However, I'm facing a problem. When I run this the data gets inserted twice. The first row gets a null `user_id` and the second row get the correct `user_id`. [See image.](https://ibb.co/kRzCiw)

While I was trying to fix it, I tried added `->debug()` to see what the query being executed looked like. So it looked like this: 

```
$database->debug()->insert("cart", [
  'user_id' => '7',
  'created_at' => time()
]);
```

This was the output: `INSERT INTO "cart" ("user_id", "created_at") VALUES ('7', 1507739560)`

I then tried to copy and paste this query directly into my MySQL GUI (Sequel Pro) and it gave me the following error: [See image.](https://ibb.co/jZS4wG)

Is this normal? Why is this happening?

_I'm using v1.4.5 of Medoo._

**Comment by catfan** [comment]
Check out your code to see whether called insert twice.

And don't just copy and paste the debug generated query to another place to execute it, because Medoo used standard quotation mode. You can check out Medoo initialization code or see the issue discussed before.

You can run `SET SQL_MODE=ANSI_QUOTES` before execution or update the quotation by yourself.

**Comment by BrianMoreno1994** [comment]
That's the only insert statement being executed. Which is why I'm kinda confused, I don't really know whats going on. But I'll continue checking, I'll report back if I ever find the answer.

**Comment by Zippersk** [comment]
Try to insert user_id as number (delete apostrophes). Not as a string.

```
$database->insert("cart", [
 'user_id' => 7,
 'created_at' => time()
]);
```

**Comment by iamkhoirulanam** [comment]
> I'm trying to insert data into a table like this:
> 
> ```
> $database->insert("cart", [
>  'user_id' => '7',
>  'created_at' => time()
> ]);
> ```
> However, I'm facing a problem. When I run this the data gets inserted twice. The first row gets a null `user_id` and the second row get the correct `user_id`. [See image.](https://ibb.co/kRzCiw)
> 
> While I was trying to fix it, I tried added `->debug()` to see what the query being executed looked like. So it looked like this:
> 
> ```
> $database->debug()->insert("cart", [
>   'user_id' => '7',
>   'created_at' => time()
> ]);
> ```
> This was the output: `INSERT INTO "cart" ("user_id", "created_at") VALUES ('7', 1507739560)`
> 
> I then tried to copy and paste this query directly into my MySQL GUI (Sequel Pro) and it gave me the following error: [See image.](https://ibb.co/jZS4wG)
> 
> Is this normal? Why is this happening?
> 
> _I'm using v1.4.5 of Medoo._

how to catch syntax error from this code with medoo?

```
$db = new Medoo\Medoo([
    "database_type" => 'mysql',
    "database_name" => 'travel',
    'server'        => 'localhost',
    "username"      => 'root',
    "password"      => '',
    "port"          => 6033,
    "option"        => [
        PDO::ATTR_CASE    => PDO::CASE_NATURAL,
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ],
    'command'       => [
        'SET SQL_MODE=ANSI_QUOTES',
    ],
]);


// CODE
// ===============
try {

    $db->pdo->beginTransaction();

    $db->insert('hotel_city', [
        'hotel_city_id' => 'q',
    ]);

    $db->pdo->commit();

} catch (Exception $e) {
    $db->pdo->rollback();
}

var_dump($db->error());
// RESULT 
// ===============
// array(3) {
//   [0]=>
//   string(5) "00000"
//   [1]=>
//   NULL
//   [2]=>
//   NULL
// }
```
Result from other MySQL GUI
`Warning Code : 1366
Incorrect integer value: 'a' for column 'hotel_city_id' at row 1`
