### ISSUE TITLE
has() method problem under PostgreSQL

### ISSUE THREAD

**Issue by inspurhua** [catfan/Medoo#646]
存在返回t,不存在返回f 是bool类型
  public function has($table, $join, $where = null)
        {
                $map = [];
                $column = null;

                $query = $this->exec('SELECT EXISTS(' . $this->selectContext($table, $map, $join, $column, $where, 1) . ')', $map);

                if ($query)
                {
                        $has = $query->fetchColumn() ;
                        return $has === '1'|| $has === true;
                }
                else
                {
                        return false;
                }
        }

**Comment by catfan** [comment]
Fixed it.
