### ISSUE TITLE
Can't insert only one row with empty string

### ISSUE THREAD

**Issue by KaikePing** [catfan/Medoo#653]
if you insert empty string into some column on only one row, this won't be inserted into database:
`$medoo->insert("drug_auditrail", [
    'drugid'=>'12',
    'new'=>''
]);`

But if you insert more than two row, this would be successfully inserted into database:
`$medoo->insert("drug_auditrail", [
    ['drugid'=>'12', 'new'=>''],     
    ['drugid'=>'13', 'new'=>'']     
]);`

**Comment by catfan** [comment]
I tested it. It's OK.

What's your `new` column setting? And what's your database, version?
