### ISSUE TITLE
Select by id issue

### ISSUE THREAD

**Issue by Baom92** [catfan/Medoo#654]
Hi.
I need to get a row knowing the id. Buit, when I try this request, I get an error (Undefined offset: 0). the array return by the "select" function is empty but the table is not. I don't know where the issue is. Please help me.
`$id = $probleme['idUsager'];`
`$usager = $this->db->select("utilisateur",["nom", "prenom"],["id"=>$id]);`
`$nom = $usager[0]['nom']." ".$usager[0]['prenom'];`

**Comment by catfan** [comment]
For this case, you may use `get()` instead of `select()`.

**Comment by Baom92** [comment]
thx
