### ISSUE TITLE
exec($query, $map = []) can not show execute result???

### ISSUE THREAD

**Issue by louishua** [catfan/Medoo#659]
`
class Db
{
    private static $_conn;

    private function __construct()
    {
    }

    public static function getInstance()
    {
        if(empty(self::$_conn)){
            self::$_conn = self::connect();
        }
        return self::$_conn;
    }

    private static function connect()
    {
        $connParams = Yaf_Application::app()->getConfig()->db->params->toArray();
        $database = new \Medoo\Medoo([
            'database_type' => $connParams['driver'] ?? 'mysql',
            'database_name' => $connParams['dbname'],
            'server' => $connParams['host'],
            'username' => $connParams['user'],
            'password' => $connParams['password'],
            'port' => $connParams['port'] ?? 3306,
            'charset' => $connParams['charset'] ?? 'utf8',
        ]);
        return $database;
    }
}

$where = ['id'=>1];
$data = ['password'=>'123'];
$result = Db::getInstance()->update('member', $data, $where);

`
I want to know the function :update() ,excute it,how I know it affect ?? 

so ,I think
$statement->execute(); must return the result;

**Comment by catfan** [comment]
Please check out the documentation: https://medoo.in/api/update

It returns `PDOStatement` object, and you can call its methods, like `rowCount()` to see the affected row.

**Comment by louishua** [comment]
thanks!
