### ISSUE TITLE
Cannot switch to secondary database

### ISSUE THREAD

**Issue by jelevuser** [catfan/Medoo#660]
Hello,

When I initiate new medoo object for say database "accounts", I cannot make a select from a table in other database, let's say "users".

$data = $db->select("users.users", "*", [
    "id[>]" => "50"
]); // Doesn't work

Is there a fix to this? 
Also, if we make joins, will it work if tables are from different databases?

Thanks

**Comment by Andrews54757** [comment]
Duplicate #119
