### ISSUE TITLE
regresion: in where condition use array as field value, produces error

### ISSUE THREAD

**Issue by michael-caraiani** [catfan/Medoo#666]
was updated to 1.5 version and had this issue
where condition:
{AND: {customer_id: [100]}}
query:
SELECT * FROM "devices" WHERE ("customer_id" IN (:MeDoO_1_mEdOo0))

result:

PDOStatement::bindValue() expects parameter 3 to be integer, array given
PDOException: SQLSTATE[HY093]: Invalid parameter number: no parameters were bound

**Comment by catfan** [comment]
Sorry for that. We emergency fixed about it. It should works now.

**Comment by rakshazi** [comment]
Thank you!
We will test it tomorrow and close issue if all ok
