### ISSUE TITLE
Offline docs

### ISSUE THREAD

**Issue by yakuthemes** [catfan/Medoo#671]
Do you have offline docs? Site is down and I would like to work on my project. So unprofessional.

**Comment by catfan** [comment]
We are just upgrading the server. It should work again now.

Sorry for the inconvenience.

**Comment by anaggh** [comment]
Why not open source the site and docs? Maybe people could help fix typos/ improve docs.

**Comment by anaggh** [comment]
Some pages are broken:

* http://medoo.in/api/collaboration
* http://medoo.in/api/whatsnew
* http://medoo.in/api/raw

**Comment by catfan** [comment]
@anaggh Thanks, all fixed now.

We have no plan to open source the whole site. It's not just a simple documentation project.
