### ISSUE TITLE
SQLSTATE[HY000] [2002] No handler for this scheme

### ISSUE THREAD

**Issue by thecobe** [catfan/Medoo#673]
Hi
i've a vps on dreamhost and pdo seems workinkg
page returned this error

Fatal error: Uncaught exception 'Exception' with message 'SQLSTATE[HY000] [2002] No handler for this scheme'

What could it be?
thanks

**Comment by banstola** [comment]
What version of medoo are you using ?

**Comment by thecobe** [comment]
Hi

Version is 1.4.5

Bye

Marco

**Comment by thecobe** [comment]
Hi
i've uploaded version 1.5.1, same error
this is phpinfo
http://ordersmanager.macronstoregrandemilano.com/phpinfo.php
bye
Marco

**Comment by thecobe** [comment]
Hi 
did you checked my issue?
thanks

**Comment by banstola** [comment]
Please do not put your phpinfo like this in public. I am is it medoo that produce this error? Can you put stacktrace instead if you can because i can not produce the same error on my machine and you have not told what you are trying to do?

**Comment by thecobe** [comment]
Hi
application is working for me too in my local machine
But when i published it i have this error

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No handler for this scheme' 
in /home/mysite.com/Classes/Medoo.php:239 Stack trace: #0 
/home/mysite.com/Classes/connection.php(38): Medoo\Medoo->__construct(Array) #1 
/home/mysite.com/orders/orders.php(3): require_once('/home/ordersman...') #2 {main} thrown in 
/home/mysite.com/Classes/Medoo.php on line 239

i attached my connection file
this is how i call it
<?php
require '../Classes/connection.php';
?>

and this is erro query
<?php
$clubs = $database->select("orders", 
[ "[><]club" => ["id_club" => "id"]	], 
["club.description (club_description)",
"orders.id (order_id)"
]);
?>

[connection.txt](https://github.com/catfan/Medoo/files/1532790/connection.txt)

**Comment by banstola** [comment]
It clearly says this 

`// [optional] MySQL socket (shouldn't be used with server and port)
	'socket' => '',`

Then why do you use this when you are using server and port both . Please remove that socket option. And try again.

**Comment by catfan** [comment]
Is it problem solve after checking out the configuration?

**Comment by thecobe** [comment]
Hi
Yes it's solved
Thanks
Bye
Marco

Il ven 23 mar 2018, 20:56 Catfan <notifications@github.com> ha scritto:
