### ISSUE TITLE
Issue on column [type]

### ISSUE THREAD

**Issue by tipleavalentin** [catfan/Medoo#678]
Just upgraded to v1.5.1 and the column type functionality seems to be broken:

$user = $this->database->get(
        // from table
        $this->tableUsers,
        // select
        [ "id [Int]", "name" ],
        // where
        ['email' => $email]
      );

The id value is: [] => 0

I tested with [String] but it’s the same issue.

**Comment by catfan** [comment]
Thanks for reporting that. We released a new version for emergency fix for this :)

**Comment by tipleavalentin** [comment]
Great, it fixed the problem.
Good job!
