### ISSUE TITLE
Fatal error: Class 'Medoo' not found

### ISSUE THREAD

**Issue by pfriedl** [catfan/Medoo#684]
Hey all. Ok, I'm very excited to start using MeDoo - looks like the perfect framework for a lightweight app. However, I'm having an issue with instantiating an instance of Medoo. 

I've got Medoo.php in a folder namesd "vendors", and I'm using it like so:

`require './vendors/Medoo.php';
$database = new Medoo([
	'database_type' => 'mysql',
	'database_name' => $dbName,
	'server' => $host,
	'username' => $dbUser,
	'password' => $dbPass
]);`

However, I'm getting an error: Fatal error: Class 'Medoo' not found. Any help would be appreciated.

**Comment by catfan** [comment]
1. Check out your PHP version is >=5.4.
2. You may missing `use Medoo\Medoo;` for using Medoo namespace.

**Comment by pfriedl** [comment]
Thanks, adding `use Medoo\Medoo;` worked!
