### ISSUE TITLE
WHERE condition with []-values fails on columnnames cnt AND / OR...

### ISSUE THREAD

**Issue by alaniso1** [catfan/Medoo#690]
Hello catfan,
working with your great Framework i found a issue within the WHERE-condition:

By using a "value-Array" the Problem occours, if the columnname contains 'AND' or 'OR'...
Example:

`$database->select("account", "user_name", [
		"RECORD_ID" => [2, 123, 234, 54]
]);
`

Because the column "REC**OR**D_ID" contains the "OR" substring, the query fails!

**Comment by catfan** [comment]
Thanks for your feedback. This really a bug, and we fixed it.

Will release a version for this soon.

Best,
Angel
