### ISSUE TITLE
multi_query support

### ISSUE THREAD

**Issue by KirDE** [catfan/Medoo#692]
Is there a support for multi_query mysqli function where multiple tables are returned as result? If running $medoo->query()->fetchAll(); only first table is returned

**Comment by Andrews54757** [comment]
@KirDE Use SQL JOIN.

**Comment by KirDE** [comment]
@Andrews54757 i need two tables as result and they have completely different set of data. actually it is a procedure that is called. Currently we are doing it with new mysqli connection, but i don't like this solution.

**Comment by Andrews54757** [comment]
@KirDE What do you mean? Please elaborate on how SQL can do this. What would be the query?


If the query is something like ``SELECT * FROM `table`, `table2` `` then you can emulate that with JOIN

**Comment by KirDE** [comment]
We have 2 SELECT Queries stored as Procedure in mysql DB. We are not allowed to change this procedure to separate this queries.

**Comment by Andrews54757** [comment]
@KirDE Oh, okay. Sorry, I thought you were meaning something else. Anyway, in your case you would have to use [PDOStatement::nextRowset](http://php.net/manual/en/pdostatement.nextrowset.php). Medoo does not support this as of now.

@catfan

**Comment by Andrews54757** [comment]
@KirDE There is a helpful resource here: https://www.ibm.com/support/knowledgecenter/en/SSSNY3_10.1.0/com.ibm.swg.im.dbclient.php.doc/doc/t0023501.html
