### ISSUE TITLE
How to get the ID list of all newly inserted data when bulk inserting data?

### ISSUE THREAD

**Issue by zhubaoming** [catfan/Medoo#697]
Because after inserting the data is done, I need to deal with a series of ID corresponding to these data.
Update also has the same problem.
I love your Medoo very much and have been using it in my project very much. Thanks for your open source!

**Comment by catfan** [comment]
No, it can not. The id will be discontinuous and incorrect while inserting data with multiple thread or heavy IO operations. The best way is insert one record and fetch the id immediately.

**Comment by joserodriguez1** [comment]
> Because after inserting the data is done, I need to deal with a series of ID corresponding to these data.
> Update also has the same problem.
> I love your Medoo very much and have been using it in my project very much. Thanks for your open source!

I know it might be a little late, but if you do the bulk insert:
$data = $database->insert($table, $array);
then the id:
$database->id();
it will return the first id of all, so ... then you get the row count:
$data->rowCount();
And you are able to code your way out with a for loop to get the rest of the ids.
It seems not that beautiful but it is less work for the server than doing several inserts.

Hope this helps someone! :)
