### ISSUE TITLE
Join with same column names issue

### ISSUE THREAD

**Issue by tmblog** [catfan/Medoo#704]
Is there an issue with returning columns with same names from different tables? I am unable to return columns:

`$ddata = $database->select("q_text", [
"[>]text_chapter" => ["q_text.chapter_id" => "id"],
"[>]q_language" => "index"
],
[
"no",
"q_text.text",
"q_language.text",
"q_text.chapter_id",
"chapter_name"
], [
"q_text.index" => 50
]);?>`

These two are same named columns from two tables:

`"q_text.text",
"q_language.text",`

But unable to get it like this:

`$ddata[0]['q_text.text']`

results in unidentified index but this way only returns just the one:

`$ddata[0]['text']`

Is there an issue or is there another way of getting this? Cheers.

**Comment by catfan** [comment]
In this case, you may need to use alias feature. That what's for this kind of problem.

```php
"q_text.text (q_text)",
"q_language.text (language_text)"
```

https://medoo.in/api/select

**Comment by tmblog** [comment]
OK turns out it can be overcome by renaming columns:
https://medoo.in/api/select

Cheers
