### ISSUE TITLE
Try-catch to open the transaction in the insert and update operations failed to capture the Exception

### ISSUE THREAD

**Issue by xzs1994** [catfan/Medoo#707]
我在try-catch体中使用事务进行更新插入操作，即使传入错误字段或表名，catch也不能捕捉到错误。请问应该怎样才能正确操作？

**Comment by catfan** [comment]
Could you describe the problem in English here please?

**Comment by xzs1994** [comment]
sorry,my english is so bad . this is my question : 
I update and insert operation with the  PDO transaction in the try-catch body, and even if the error field or table name is passed in, the catch cannot catch the error. How can I operate correctly?

**Comment by catfan** [comment]
If the table name error information will be displayed on `error()` call when the query is executed. Try-catch is catching code or prepared statement level exception.
