### ISSUE TITLE
Fatal error: in lib\Medoo.php on line 239

### ISSUE THREAD

**Issue by psyapathy** [catfan/Medoo#710]
hello!

i try this code:
`<?php
require 'lib/Medoo.php';
use Medoo\Medoo;
$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => 'net_flow',
    'server' => 'localhost',
    'username' => 'root',
    'password' => 'pass'
]);
$database->sum('flow_table', 'packets', ["stamp[<>]" => ['2018-01-19 16:28:00', '2018-01-19 16:32:00']]);
?>`

but i have error Fatal error: in lib\Medoo.php on line 239

=(
Help me please

**Comment by catfan** [comment]
You may need to use `try` and `catch` to read the exception message.

It seem your configuration problem.

And also, provide the version you are using for issue.
