### ISSUE TITLE
Port does not work as expected

### ISSUE THREAD

**Issue by banstola** [catfan/Medoo#711]
```
   $pdo=        new Medoo(
[
 "server"=> "localhost",
  "database_type"=> "mysql",
  "database_name"=>"foobar",
   "username"=> "user",
   "password"=> "pass",
    "port"=>3306
]
);
````
causes `PDOException: SQLSTATE[HY000] [2002] No such file or directory` but 

```
   $pdo=        new Medoo(
[
 "server"=> "localhost:3306",
  "database_type"=> "mysql",
  "database_name"=>"foobar",
   "username"=> "user",
   "password"=> "pass"
]
);
````
works perfecto . We can sure use `localhost:3306` but just wondering why adding port does not work. [ Context: Running from command line, MAMP ]

**Comment by catfan** [comment]
MAMP is using unix_socket for database connection. You may need to change `port` to `unix_socket` instead.
