### ISSUE TITLE
nested query or sub query

### ISSUE THREAD

**Issue by classix16** [catfan/Medoo#712]
i have query:

select a.*, b.is_send 
from tbla as a 
left join (select * from tblb were sts = 1) as b
on a.id=b.id_a
where a.num > 10

how do i use medoo?

i dont want raw function. becouse my app have potential change database from mysql to posgrees or oracle

**Comment by catfan** [comment]
Sub query will be more complex for Medoo in current. I suggest just use raw function or separate into two function call for this case.
