### ISSUE TITLE
 Custom query log and debugging SQL ERROR

### ISSUE THREAD

**Issue by HeNian** [catfan/Medoo#714]
Because in this mode `SET SQL_MODE=ANSI_QUOTES`

`"` will be using for identifier.

Like this SQL
`update "attachment" set "name" = '["good","jack"]', "age" = '["18","20"]'`

Mysql will run as
``update `attachment` set `name` = '["good","jack"]', `age` = '["18","20"]'``

But log or debug mode show us
``update `attachment` set `name` = '[`good`,`jack`]', `age` = '[`18`,`20`]'``

**Comment by catfan** [comment]
What's your code for this query?

You can not just assign array value to column for update statement. It will be serialized or json_encode().

**Comment by HeNian** [comment]
The value is the JSON string. 
It's because the JSON string contains double quotes.

**Comment by catfan** [comment]
Any feedback for this case? Otherwise it will be closed.
