### ISSUE TITLE
USING statement don't work in MariaDB 10

### ISSUE THREAD

**Issue by azhilov** [catfan/Medoo#715]
For example code:
`$users = $this->ci->db->select(
            'users(u1)',
            [
                '[><]users(u2)' => ['u1.who_created', 'u2.id'],
                '[>]users(u3)' => ['u1.who_updated', 'u3.id']
            ],
            ['u1.id', 'u1.username', 'u1.login', 'u1.password', 'u1.email', 'u1.phone', 'u1.role', 'u1.active',
                'u2.username(who_created)', 'u3.username(who_updated)', 'u1.created_at', 'u1.updated_at']
        );`
generated in:
`SELECT u1.id,u1.username, u1.login, u1.password, u1.email, u1.phone,u1.role,u1.active,u2.username AS who_created,u3.username AS who_updated,u1.created_at,u1.updated_at FROM users AS u1 INNER JOIN users AS u2 USING (\"u1.who_created\", \"u2.id\") LEFT JOIN users AS u3 USING (\"u1.who_updated\", \"u3.id\")`

**Comment by pedrofsantoscom** [comment]
I have the same problem while trying to use a column from a previously joined table, in a new join. It returns this error:
`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'column1' in 'from clause'`

@azhilov did you find an alternative?

**Comment by pedrofsantoscom** [comment]
Found a way to work. use (`=>`)
```sql
[
    "[><]table" => ["table2.col" => "col2"]
]
```
instead of (`,`)
```sql
[
    "[><]table" => ["table2.col", "col2"]
]
```

Example:
```sql
$db->select("table1", 
    [
        "[><]table2" => "user",
        "[><]table3" => ["table2.column1" => "column2"],
    ]);
```

@azhilov in your example, this should work:
```sql
$users = $this->ci->db->select( 'users(u1)', 
    [ 
        '[><]users(u2)' => ['u1.who_created' => 'u2.id'], 
        '[>]users(u3)' => ['u1.who_updated' => 'u3.id']
    ], 
    ['u1.id', 'u1.username', 'u1.login', 'u1.password', 'u1.email', 'u1.phone', 'u1.role', 'u1.active', 'u2.username(who_created)', 'u3.username(who_updated)', 'u1.created_at', 'u1.updated_at']
);
```
