### ISSUE TITLE
Casting Null to Int gives 0.

### ISSUE THREAD

**Issue by utkant** [catfan/Medoo#721]
Hello!

I have a select where i cast the ids to Int in the select, but it casts the null value to 0 which is not what I want. Is this a bug or is this supposed to be like this?

`$fields = ["id [Int]"];
$this->database->get("table", $fields)`

If id is NULL then this gives it the value 0 and not null.

**Comment by mozart77** [comment]
If you cast NULL to Int what do you expect?

**Comment by utkant** [comment]
If I have a table where id can be NULL or an integer, and I want the result NULL when NULL and not 0 as in integer 0, since 0 can be a valid id, how can I achieve? I need to add code for that. I believe that this is a bug.

NULL (id) !== 0(id) ...

**Comment by mozart77** [comment]
Don't cast then

**Comment by utkant** [comment]
It would mean that all the ID fields in a database cannot be casted using Int casting due to this, or you would have to set the database up so that it starts all primary keys with 1. It also means that all fields that have id columns containing NULL values cannot use casting and needs extra processing. I would love it is medoo added a [Id] casting option where this was fixed. Possibility?

**Comment by utkant** [comment]
Something like this in the mapping switch
`case 'Id':
							$stack[ $column_key ] = is_null($data[ $column_key ]) ? null : (int) $data[ $column_key ];
							break;`

**Comment by utkant** [comment]
I would open a pull request and add it myself but I am not sure about how to actually do that...

**Comment by catfan** [comment]
Yes, this is a bug. The null value should return as Null not 0. I made a bug fix for this. d28ae10
