### ISSUE TITLE
How use medoo row in column name where cluase

### ISSUE THREAD

**Issue by HASSANDL** [catfan/Medoo#725]
hello, Is correct this code?
```
$database->get('account', [
	'user_name',
	'user_id' 
], [
	Medoo::raw('LEN(<experience>)') => 100
]);
```

```
SELECT "user_name", "user_id"
FROM "account"
WHERE LEN("experience") = 100
```

**Comment by catfan** [comment]
You can not assign raw object (or any PHP objects) as key of array in PHP language.

But it will be supported for next version of Medoo with new design method.

**Comment by ThisIsntMyId** [comment]
is this supported yet? i want to use mysql's JSON_OVERLAP function inside where clause but the problem is that the where part of the query is ready dynamic and build from somewhere else.

**Comment by kingkong19** [comment]
hey, this possible now?
