### ISSUE TITLE
1.5版本下mysql情况下ATTR_EMULATE_PREPARES设为false的时候has语句永远返回false

### ISSUE THREAD

**Issue by lovearthhome** [catfan/Medoo#729]
mysql情况下ATTR_EMULATE_PREPARES设为false的时候has语句永远返回false。还有在1.2版本的时候. count语句也是出错，count函数不能把字符串数字转换为int数字。两年前曾联系过作者，无回复。

**Comment by lovearthhome** [comment]
找到了解决方案："PDO::ATTR_EMULATE_PREPARES => true" 。应该是medoo在本地模拟编译的时候出了问题。也懒得查了。虽然这样牺牲一点性能。但可以接受。

**Comment by ha-ni-cc** [comment]
我是设置为
'option' => [PDO::ATTR_EMULATE_PREPARES => false, PDO::ATTR_STRINGIFY_FETCHES => true]，has正常。。。强制把数字toString。。。这样has里面的判断就正常了。。。因为用了==='1'。。。

**Comment by lovearthhome** [comment]
@ha-ni-cc 好奇怪，我这边只设了PDO::ATTR_EMULATE_PREPARES => true,也可以了。 @catfan

**Comment by lovearthhome** [comment]
@ha-ni-cc 我们的代码强烈依赖pdo去把搜出来的字段转换为原来的类型，所以PDO::ATTR_STRINGIFY_FETCHES必须设为false。 @catfan

**Comment by catfan** [comment]
Duplicated issue #720.
