### ISSUE TITLE
Data Type Transformation

### ISSUE THREAD

**Issue by stell** [catfan/Medoo#730]
In my Database there is a field saved as tinyint(1) where 1 and 0 stand for true and false.
When using Medoo

```
'prices' => [
    'courtage[Bool]'
]
```

does not turn a 0 to FALSE and a 1 to TRUE.

Is there a way to achieve this or am i missing something?

**Comment by stell** [comment]
I tried now something like this, but no luck so far:

`'courtage' => Medoo::raw('IF(<courtage>, "TRUE", "FALSE")')`

**Comment by catfan** [comment]
Could you like to info me that what's database and version you are using?

And the full code for this Medoo function call, data output.

**Comment by stell** [comment]
Server: 127.0.0.1 via TCP/IP
Server-Typ: MariaDB
Server-Version: 10.1.19-MariaDB - mariadb.org binary distribution
Protokoll-Version: 10

---

    public function getObjectById($id) {

        $data = $this->db->select('objects', 
           [
            "[>]prices" => ["id" => "oid"],
           ],
           [
           'courtage' => Medoo::raw('IF(<courtage>, "TRUE", "FALSE")')
           ],
            ['id' => $id, "LIMIT" => 1]
        );

        if (empty($data)) {
            throw new \Exception('No object found', 400);
        }        
        return $data[0];
    }

**Comment by catfan** [comment]
What's was the var_dump() output about this code?

```php
$data = $this->db->select('objects', [
	'courtage [Bool]'
], [
	'id' => $id
]);

var_dump($data);
```
