### ISSUE TITLE
Medoo wrapper

### ISSUE THREAD

**Issue by aryelgois** [catfan/Medoo#734]
Hello there!

Medoo is fantastic! Way better than dealing with `mysqli_*` functions or `PDO` all by myself.

But there is something that was still bothering me.. Having to create the connection everywhere, and having to pass the table name all the time.

So I created a wrapper that reuses the connections and allows me create one class for each table (OOP) real quick  :D

Here is the repository: https://github.com/aryelgois/Medools

I even named it to remember Medoo (there is no problem, right?). Medools would be Medoo + models, because the main class works like a model in a MVC pattern.

To take it to the next level, I just finished a router framework based on my wrapper. It makes very easy to create a RESTful APIs, where each resource maps to a model.

There is: https://github.com/aryelgois/medools-router

I hope you find it helpful

**Comment by catfan** [comment]
Great work for that!

It's pleasure to have this wrapper based on Medoo.

But here, the issue board, is the place reporting problem for Medoo project itself. Not a forum. So this kind of post have to be closed.

Anyway, keep up the work.

Hope the best,

**Comment by aryelgois** [comment]
Yeah, sorry about that

Is there any forum? :3
