### ISSUE TITLE
Fatal error: Class 'Medoo\Medoo' not found in Medoo-master\test.php on line 11

### ISSUE THREAD

**Issue by sl5net** [catfan/Medoo#737]
first error was: Fatal error: Class 'Medoo\Medoo' not found in Medoo-master\test.php on line 11

<?php 
require 'vendor/autoload.php';
use Medoo\Medoo;

i changed to
use src\Medoo;

next error is: 
Parse error: syntax error, unexpected '$database' (T_VARIABLE) in E:\fre\private\HtmlDevelop\AutoHotKey\global-IntelliSense-everywhere-Nightly-Build\Source\plugins\php\phpdesktop\www\Medoo-master\test.php on line 21

thats this line:
$file = "someDB.db"
$database = new Medoo([
'database_type' => 'sqlite',
'database_file' => $file,
]);

**Comment by Fahri5567** [comment]
You need to import the class
If you installed via composer, just use this code to requrie autoloader on the top of your projects like this:
```
require 'vendor/autoload.php';

// Using Medoo namespace
use Medoo\Medoo;
```
If not using the composer. Just download medoo.php and put it into the right directory and then require
```
require  'Medoo.php';

// Using Medoo namespace
use Medoo\Medoo;

```

For reference, see [https://medoo.in/api/new](https://medoo.in/api/new)

**Comment by sl5net** [comment]
thanks but that i did first.
composer created the vendor folder.
but no Medoo folder.
i renamed to src inside the source file

**Comment by catfan** [comment]
@Fahri5567 is right. That's namespace problem. Or read the initialization guide https://medoo.in/api/new.
