### ISSUE TITLE
select columns`t`.* when set join params generate a error sql query

### ISSUE THREAD

**Issue by allyfireshen** [catfan/Medoo#738]
i have a query like this:
`$this->database->select("post", [
        "[>]account" => ["author_id" => "user_id"]
        ],[
        "post.*",
        "account.city"
       ],[
        "post.user_id" => 100
       ])`;
and generate the error sql like this:
 `SELECT post."", account.city FROM post 
                 LEFT JOIN post ON post.author_id = account.user_id 
                WHERE post.user_id = 100`

if i want to get the all columns from `post`,i must set the all columns like `post.id,post.author`, can't use `post.*`?

**Comment by catfan** [comment]
Duplicated issue from #631. Please search before create new issue.
