### ISSUE TITLE
[!empty]Instead of[isset]

### ISSUE THREAD

**Issue by tianyiw2013** [catfan/Medoo#74]
function where_clause($where)
            if (isset($where['AND']))

suggest:
            if (!empty($where['AND']))

My code:
<?php
$where = array();
$uid&& $where['uid'] = $uid;
$type && $where['type'] = $type ;
$list = db()->select("table", '*',array('AND'=>$where));

**Comment by GaryJones** [comment]
This looks to be fixed: https://github.com/catfan/Medoo/blob/master/medoo.php#L429
