### ISSUE TITLE
How can I reconnect if the connection has been closed?

### ISSUE THREAD

**Issue by nikoskip** [catfan/Medoo#743]
Hi,

I'm using Medoo with MySQL in a very long process (it can take up to 2 hours to complete). When the process has finished I'm getting a `MySQL server has gone away (2006)`.

I would like to identify this and reconnect before executing any other query to the server.

Thanks.

**Comment by jamesst20** [comment]
@catfan 

Seems to be ignoring PRs and issues reported, but looks like the project is still maintened.

2 years ago I believe a fix for this was pushed https://github.com/catfan/Medoo/pull/513 altough it's true the PR code isn't perfect

**Comment by onefreddy** [comment]
hi i have the same problem. I do not want to change timeout of the mysql. I would like to see a setting in the library configuration that allows automatic reconnections.
sample:

```
$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => '',
    'server' => 'localhost',
    'username' => '',
    'password' => '',
	'autoreconifgoneaway' => true,
]);
```

**Comment by oriononair** [comment]
I also have the same problem. I don't have access to change timeout of mysql. I guess something like @onefreddy suggested would help. I could not solve it completely trying other things.

**Comment by catfan** [comment]
It's recommend to use singleton pattern for accessing database. https://medoo.in/api/collaboration

```php
$app->singleton(function ($name, $singletonObject) {
    if ($name === "database") {
        if ($singletonObject === null) {
            // do something if database is lose
            echo "Connection is lose";

            // or reconnect the database
            $database = new Medoo([
                'database_type' => 'mysql',
                ...
            ]);
        }
    }
});
```

If the connection is lose, you can reconnect the database there, or connect another database, or just output the error message to client without reconnection. All those ways are up to you.
