### ISSUE TITLE
[question]how about using stored procedure in mssql

### ISSUE THREAD

**Issue by LeeHM** [catfan/Medoo#745]
how about using stored procedure in mssql

**Comment by catfan** [comment]
That's not possible. But you can use `query()` for calling a stored procedure.

**Comment by supportreq** [comment]
@catfan while trying to execute the stored procedure using execute, it is returning 0 response..

  $Data = $db->query("exec List '2020-06-01','2020-07-30'");

Response
PDOStatement Object
(
    [queryString] => exec List '2020-06-01','2020-07-30'
)
Array
(
    [0] => 00000
    [1] => 
    [2] => 
)
