### ISSUE TITLE
Index failure

### ISSUE THREAD

**Issue by jusong** [catfan/Medoo#746]
#The generated SQL has a quotation mark, which causes the index to fail.
Like this

### normal:
explain select * from user where id = '2258361';
+----+-------------+-----------+-------+---------------+---------+---------+-------+------+-------+
| id | select_type | table     | type  | possible_keys | key     | key_len | ref   | rows | Extra |
+----+-------------+-----------+-------+---------------+---------+---------+-------+------+-------+
|  1 | SIMPLE      | user | const | PRIMARY       | PRIMARY | 4       | const |    1 | NULL  |
+----+-------------+-----------+-------+---------------+---------+---------+-------+------+-------+

### abnormal:
explain select * from user where 'id' = '2258361';
+----+-------------+-------+------+---------------+------+---------+------+------+------------------+
| id | select_type | table | type | possible_keys | key  | key_len | ref  | rows | Extra            |
+----+-------------+-------+------+---------------+------+---------+------+------+------------------+
|  1 | SIMPLE      | NULL  | NULL | NULL          | NULL | NULL    | NULL | NULL | Impossible WHERE |
+----+-------------+-------+------+---------------+------+---------+------+------+------------------+

**Comment by catfan** [comment]
The generated SQL is only for debug. We don't recommend that run this SQL query for another place.

The query Medoo will be executed is statements prepared.
