### ISSUE TITLE
ORDER not working

### ISSUE THREAD

**Issue by rvercesi** [catfan/Medoo#748]
```
$results = $db->select('mytable','*', [
        "title[~]" => $val,
        "page"    => $thispage
    ],[
        "ORDER" => ["status" => "DESC"],
        "LIMIT" => [$start, $limit]
    ]);
```

ORDER simply does not work, no error, no warning, just does not work at all.

**Comment by catfan** [comment]
What's your version and what's your debug() output?

**Comment by rvercesi** [comment]
I have 1.5.6 and the debug output is

"SELECT * FROM mytable WHERE title LIKE '%val%' AND page = 'thispage' ORDER LIMIT start, limit"

**Comment by catfan** [comment]
The ORDER and LIMIT should be with condition together.

```php
$results = $db->select('mytable','*', [
       "title[~]" => $val,
       "page"    => $thispage,
       "ORDER" => ["status" => "DESC"],
       "LIMIT" => [$start, $limit]
]);
```

**Comment by M001T** [comment]
"ORDER" => ["status" => "DESC"],

EXAMPLE:

"ORDER" => ["date" => "DESC"]
