### ISSUE TITLE
Join condition based on one of the tables

### ISSUE THREAD

**Issue by sourabhbajaj** [catfan/Medoo#752]
How to use join to select conditional data from one table. 

For example, look at this query: 

select question.id, question.text, vote.vote as myvote from question left join vote on vote.questionId=question.id and vote.userId=2 where question.id=6;

How to achieve similar results with Medoo?

**Comment by sourabhbajaj** [comment]
This results in this:
select question.id, question.text, vote.vote as myvote from question left join vote on vote.questionId=question.id and vote.userId=question.2 where question.id=6;

Basically, it reads value as if its a column from the other table.

**Comment by catfan** [comment]
@sourabhbajaj You may misunderstood the join syntax. Join is telling the relationship between columns, not the condition.

For your case, the SQL should be
```SQL
LEFE JOIN vote ON vote.questionId=question.id WHERE vote.userId=2 AND question.id=6
```

**Comment by sourabhbajaj** [comment]
This will not select any post if the user has not voted on it. You're telling SQL to select the rows which has vote.userId=2. In the query I suggested, it will select the post but the vote column will result null.

**Comment by catfan** [comment]
I'm not sure your table construction, but for the `JOIN xxx ON xxx`, it can not use `vote.userId=2` condition.

You may need to consider the LEFT/RIGHT/INNER/OUTER join type.

**Comment by sourabhbajaj** [comment]
I have given a simplified version of my table structure. The query I suggested works. These are the 2 tables of concern:

POST: id, text
VOTE: post_id, user_id, vote

Now I need to fetch all the posts with the info that a particular user has voted on it or not. What other way do you suggest?

**Comment by sourabhbajaj** [comment]
Check out the accepted answer in this post: https://stackoverflow.com/questions/22104308/where-clause-for-only-one-table-in-a-left-join?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by dragonares5** [comment]
I'm having this problem too, looks like Medoo is not inserting the number type as pure integer, returning "column"."12490" instead.
`'[>]UIGAUserItem(diamond)' => [
                'u.LoginUID' => 'LoginUID',
                'diamond.ItemID' => 12490
            ],`
This code will become
`"u"."LoginUID" = "diamond"."LoginUID" AND "diamond"."ItemID" = "diamond"."12490"`
But, the correct one is "ItemID" = 12490, that will work perfectly here in SQL Server 2017.


Note: The 12490 is fixed static value, so i dont have it on the column to compare with.

**Comment by dragonares5** [comment]
selectContext() function:
`$joins = [];

foreach ($relation as $key => $value)
{
	$joins[] = (
		strpos($key, '.') > 0 ?
			// For ['tableB.column' => 'column']
			$this->columnQuote($key) :

			// For ['column1' => 'column2']
			$table . '."' . $key . '"'
	) .
	' = ' .
	(is_numeric($value) ? $value : ($this->tableQuote(isset($match[ 'alias' ]) ? $match[ 'alias' ] : $match[ 'table' ]) . '."' . $value . '"'));
}
`

It's working now with this code.

**Comment by scr4bble** [comment]
I have the same issue. I would like to use a JOIN clause and compare a column with a constant value in "ON" clause.

Example:
SELECT *
from bookings
LEFT JOIN other_table
ON bookings.booking_id = other_table.booking_id
AND other_table.some_column = 42

How to use "some_column = 42" condition in JOIN clause?

**Comment by sourabhbajaj** [comment]
@scr4bble I have created a wrapper to handle this issue. If you want, I can share that with you.

**Comment by scr4bble** [comment]
@sourabhbajaj thank you but I have solved it in raw sql query. I just wanted to point out that it is missing in the framework and that @catfan might want to consider supporting it :)

**Comment by sourabhbajaj** [comment]
In case anyone else faces the same problem until medoo accepts and addresses this issue, here's a Database class wrapper which inherits Medoo so uses all the functions exactly the same. 

```
<?php
namespace App\Helper;
use Medoo\Medoo;

class Database extends Medoo{
  public function __construct($config){
    parent::__construct($config['database']);
  }

  protected function selectContext($table, &$map, $join, &$columns = null, $where = null, $column_fn = null)
  {
    preg_match('/(?<table>[a-zA-Z0-9_]+)\s*\((?<alias>[a-zA-Z0-9_]+)\)/i', $table, $table_match);

    if (isset($table_match[ 'table' ], $table_match[ 'alias' ]))
    {
      $table = $this->tableQuote($table_match[ 'table' ]);

      $table_query = $table . ' AS ' . $this->tableQuote($table_match[ 'alias' ]);
    }
    else
    {
      $table = $this->tableQuote($table);

      $table_query = $table;
    }

    $join_key = is_array($join) ? array_keys($join) : null;

    if (
      isset($join_key[ 0 ]) &&
      strpos($join_key[ 0 ], '[') === 0
    )
    {
      $table_join = [];

      $join_array = [
        '>' => 'LEFT',
        '<' => 'RIGHT',
        '<>' => 'FULL',
        '><' => 'INNER'
      ];

      foreach($join as $sub_table => $relation)
      {
        preg_match('/(\[(?<join>\<\>?|\>\<?)\])?(?<table>[a-zA-Z0-9_]+)\s?(\((?<alias>[a-zA-Z0-9_]+)\))?/', $sub_table, $match);

        if ($match[ 'join' ] !== '' && $match[ 'table' ] !== '')
        {
          if (is_string($relation))
          {
            $relation = 'USING ("' . $relation . '")';
          }

          if (is_array($relation))
          {
            // For ['column1', 'column2']
            if (isset($relation[ 0 ]))
            {
              $relation = 'USING ("' . implode($relation, '", "') . '")';
            }
            else
            {
              $joins = [];

              foreach ($relation as $key => $value)
              {
                $joins[] = (
                  strpos($key, '.') > 0 ?
                    // For ['tableB.column' => 'column']
                    $this->columnQuote($key) :

                    // For ['column1' => 'column2']
                    $table . '."' . $key . '"'
                ) .
                ' = ' .
                (
                  $this->isRaw($value)?
                  "'".$value->value."'" :
                  $this->tableQuote(isset($match[ 'alias' ]) ? $match[ 'alias' ] : $match[ 'table' ]) . '."' . $value . '"'
                );
              }

              $relation = 'ON ' . implode($joins, ' AND ');
            }
          }

          $table_name = $this->tableQuote($match[ 'table' ]) . ' ';

          if (isset($match[ 'alias' ]))
          {
            $table_name .= 'AS ' . $this->tableQuote($match[ 'alias' ]) . ' ';
          }

          $table_join[] = $join_array[ $match[ 'join' ] ] . ' JOIN ' . $table_name . $relation;
        }
      }

      $table_query .= ' ' . implode($table_join, ' ');
    }
    else
    {
      if (is_null($columns))
      {
        if (
          !is_null($where) ||
          (is_array($join) && isset($column_fn))
        )
        {
          $where = $join;
          $columns = null;
        }
        else
        {
          $where = null;
          $columns = $join;
        }
      }
      else
      {
        $where = $columns;
        $columns = $join;
      }
    }

    if (isset($column_fn))
    {
      if ($column_fn === 1)
      {
        $column = '1';

        if (is_null($where))
        {
          $where = $columns;
        }
      }
      elseif ($raw = $this->buildRaw($column_fn, $map))
      {
        $column = $raw;
      }
      else
      {
        if (empty($columns) || $this->isRaw($columns))
        {
          $columns = '*';
          $where = $join;
        }

        $column = $column_fn . '(' . $this->columnPush($columns, $map) . ')';
      }
    }
    else
    {
      $column = $this->columnPush($columns, $map);
    }

    return 'SELECT ' . $column . ' FROM ' . $table_query . $this->whereClause($where, $map);
  }
}
?>

```

**Comment by sourabhbajaj** [comment]
@catfan If you'd consider accepting my pull request on this, I would love to contribute this.

**Comment by oeortiz** [comment]
return  $this->db->select("usuario_has_materia", 
        [            
            "[>]usuario" => ['usuario_id' => 'id'],
            "[>]materia" => ["materia_id" => "id"],
        ],[
            "usuario.nombre",
            "materia.nombre",
        ],[
            "usuario.id"=>$id
        ]);
some one knows why no retrive both columns?

**Comment by catfan** [comment]
@oeortiz Because the returned data from database are one-dimensions array, the data with same column name will be overridden.

**Comment by Pesche007** [comment]
Hi guys
Any news on that? 
Joining tables with static values in ON clause would be appreciated. 
Thanks
