### ISSUE TITLE
Unable to pass data into transaction

### ISSUE THREAD

**Issue by callumb** [catfan/Medoo#753]
I am unable to pass data into a transaction function closure. 

Whats the best way to do this? Don't want to use things like Globals etc Variable before contains an array then going into the function gives NULL on that variable when you try and use it. Passing any kind of argument does nothing. Documentation really isn't clear on this.

**Comment by catfan** [comment]
You can use `use` keyword for closure function call.

http://php.net/manual/en/functions.anonymous.php

Or variable scope

http://php.net/manual/en/language.variables.scope.php

Up to your project.
