### ISSUE TITLE
query through mycat1.6.5 always return empty array

### ISSUE THREAD

**Issue by chenwei99999** [catfan/Medoo#755]
such as:
```php
 $database->select("account", [
    "user_name",
    "email"
], [
    "user_id" => 100
]);
```
always return empty array,but user_id = 100 record is really exist.Query the MySQL log, SQL has the execution.use PDO is no problem.  Can you understand?My Englist is poor.

**Comment by klodha** [comment]
I am facing similar issue, though its not happening 100% time, but out of 100 hit it 80 times. 

Find any solution?
