### ISSUE TITLE
Insert not working

### ISSUE THREAD

**Issue by snake302** [catfan/Medoo#758]
Yes, I have the same problem again.

Using last version from composer. Insert just not working, null error. Just nothing happens.

this is output `NULL INSERT INTO `users` (`username`, `full_name`, `img`, `is_private`) VALUES ('123', '345', '567', '97957')array(0) { } It works!`

```
$base = $this->conection();
		$base->debug()->insert("users", [
		"username" => '123',
		"full_name" => '345',
		"img" => '567',
		"is_private" => '97957',
		]);

```

**Comment by catfan** [comment]
It is no problem for the query output.

What's your `$database->error()` output?
