### ISSUE TITLE
action function for sql transaction

### ISSUE THREAD

**Issue by sylvain-schneider** [catfan/Medoo#763]
Hi,
I don't see how to pass parameters to transaction with action ?
Should I change the callback function to pass an array like this ? :

`public function action($actions, $parameters)`
(l1458)

and pass my array or is there a simpler method ?

**Comment by catfan** [comment]
You can use `use` keyword to inherit the variables.

http://php.net/manual/en/functions.anonymous.php

**Comment by sylvain-schneider** [comment]
oh, yes, thank you !
