### ISSUE TITLE
how to connect oracle  thank?

### ISSUE THREAD

**Issue by chenbaicheng** [catfan/Medoo#765]
$database = new Medoo([
	'database_type' => 'oracle',
	'database_name' => 'gxpt_zjsb',
	'server' => '19.14.7.60',
	'username' => 'gxpt_zjsb',
	'password' => 'oracle2018',
]);
 It's not work .

**Comment by dfanica** [comment]
try `oci8` instead of `oracle`

**Comment by chenbaicheng** [comment]
thanks @dfanica

**Comment by catfan** [comment]
The option of `'database_type' => 'oracle'` is correct. You may check out the `dsn` string or the error output.

**Comment by chenbaicheng** [comment]
@catfan   thanks  ， i think  oracle is not friendly  to user
