### ISSUE TITLE
Missing information in Documentation - Compound WHERE - Space missing

### ISSUE THREAD

**Issue by adarshmadrecha** [catfan/Medoo#771]
The documentation states adding a comment if we are using `OR` multiple times 

> ```
> // assign a comment for each AND and OR key name. The comment content can be everything.
> $database->select("account", '*', [
> 	"AND #Actually, this comment feature can be used on every AND and OR relativity condition" => [
> 		"OR #the first condition" => [
> 			"user_name" => "foo",
> 			"email" => "foo@bar.com"
> 		],
> 		"OR #the second condition" => [
> 			"user_name" => "bar",
> 			"email" => "bar@foo.com"
> 		]
> 	]
> ]);
> // SELECT * FROM "account"
> // WHERE (
> // 	(
> // 		"user_name" = 'foo' OR "email" = 'foo@bar.com'
> // 	)
> // 	AND
> // 	(
> // 		"user_name" = 'bar' OR "email" = 'bar@foo.com'
> // 	)
> // )
> ```

But the documentation does not states that there has to be `space` between `AND` and `#Some Comment`.  If the code is `AND#Some Comment` then it does not create expected SQL. The code should be `AND #Some Comment`.

I am not sure if this is the expected behaviour of the library or error in documentation.

To reproduce this error here is my code
```

$tasks = $db->select(
    // table name
    'task',
    // table join
    [
      '[><]client' => [
        // task => client
        'officeid' => 'officeid',
        'clientid' => 'clientno'
      ],
      '[><]taskteam' => [
        // task => taskteam
        'officeid' => 'officeid',
        'taskno' => 'taskid'
      ]
    ],
    // columns
    [
      'taskno',
      // Many other columns
    ],
    // where clause
    [
      // Default Values
      'task.officeid' => $_SESSION['offid'],
      'taskstatus' => ['G', 'S'],
      'taskteam.staffmob' => $_SESSION['mobno'],
      // User Values
      'AND #Some Comment' => [
        'OR #task ' => [
          'taskname[~]' => $_GET['tasksearch'],
          'taskno[~]' => $_GET['tasksearch'],
        ],
        'OR #client ' => [
          'fname[~]' => $_GET['clientsearch'],
          'lname[~]' => $_GET['clientsearch'],
          'cname[~]' => $_GET['clientsearch'],
          'clientid[~]' => $_GET['clientsearch'],
        ],      

      ],

      // GROUP BY
      'GROUP' => ['task.taskno'],
    ]
  );
```
This generates below WHERE Clause

```

WHERE 
`task`.`officeid` = 'DEMO' AND 
`taskstatus` IN ('G', 'S') AND 
`taskteam`.`staffmob` = '99999' AND 
(
 ( 
   (`taskname` LIKE '%%') OR 
   (`taskno` LIKE '%%')
 ) 
 AND 
 (
  (`fname` LIKE '%kesh%') OR 
  (`lname` LIKE '%kesh%') OR 
  (`cname` LIKE '%kesh%') OR 
  (`clientid` LIKE '%kesh%')
 )
) 

GROUP BY `task`.`taskno` 
```

If the code is changed to remove the space 
```
      'AND#Some Comment' => [
```
It generates below WHERE Clause

```
WHERE 
`task`.`officeid` = 'DEMO' AND 
`taskstatus` IN ('G', 'S') AND 
`taskteam`.`staffmob` = '99999' AND 
`AND` IN (Array, Array) 

GROUP BY `task`.`taskno`
```

**Comment by iranalves85** [comment]
Thank You. I wasted hours thinking whats wrong with my code. Save me a lot time.

**Comment by catfan** [comment]
Added it.
