### ISSUE TITLE
数据库查询，表中字段大小比较

### ISSUE THREAD

**Issue by lt0501** [catfan/Medoo#777]
字段比较
"OR" => [
                "count_send[<]" => "count",
                        "count" => 0
                           ],
`count_send` < 'count' OR `count` = 0
暂不支持？

**Comment by catfan** [comment]
Please read our documentation before opening new issues.

https://medoo.in/api/where on **Columns Relationship** section.

**Comment by lt0501** [comment]
solved,Columns Relationship.thank you very much.

**Comment by lt0501** [comment]
solved,columns relationsgip v1.5.7.thank you very much.
