### ISSUE TITLE
Unexpected data when mysql query is run

### ISSUE THREAD

**Issue by bhullar89** [catfan/Medoo#780]
I am calling below query from my table to get distinct values
`$data['data'] =  $this->dbconn->query("SELECT DISTINCT area_name FROM actions")->fetchAll();`

The $data display below data
```
{
  "data": [
    {
      "0": "",
      "area_name": ""
    },
    {
      "0": "101",
      "area_name": "101"
    },
    {
      "0": "Floor 3",
      "area_name": "Floor 3"
    },
    {
      "0": "Floor 1",
      "area_name": "Floor 1"
    },
    {
      "0": "Floor 4",
      "area_name": "Floor 4"
    }
  ]
}

Why are there two entries in data array??
Am i doing something wrong ? or its a bug ?
```

**Comment by bhullar89** [comment]
Using below , resolves the issues
$medoo->select('actions', ['area_name' => Medoo::raw('DISTINCT(area_name)')])

**Comment by anaggh** [comment]
Add this to option `PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,`
