### ISSUE TITLE
MySQL String Comparison int

### ISSUE THREAD

**Issue by Thinklong** [catfan/Medoo#781]
```php
$database->update('account', [
    'email' => 'foo@bar.com',
    'age' => 25,
    'lang' => ['en', 'fr', 'jp', 'cn']
],
'user_name' => 0);
```

In MySQL, "'user_name' = 0 is true", but we should know that it should not be true, how to avoid this in meedo

**Comment by catfan** [comment]
Read documentation about `WHERE` condition: https://medoo.in/api/where
