### ISSUE TITLE
First column values is bigger then second colum values NOT work properly

### ISSUE THREAD

**Issue by FirestarterUA** [catfan/Medoo#786]
Medoo Query like:
`			$links = $this->db->debug()->select("links", "*", [$isBot."[<]" => "limit_".$isBot, "ORDER" => ["created_at" => "ASC"], "LIMIT" => 100]);
`
$isBot - is string.

Generate an sql query like:
`SELECT * FROM "links" WHERE "yandex" < 'limit_yandex' ORDER BY "created_at" ASC LIMIT 100`

But must:
`SELECT * FROM "links" WHERE "yandex" < "limit_yandex" ORDER BY "created_at" ASC LIMIT 100`

Quotes are not properly working

**Comment by catfan** [comment]
If `limit_yandex` is column, you should use
```php
[
	$isBot . "[<]limit_" . $isBot,
	"ORDER" => ["created_at" => "ASC"],
	"LIMIT" => 100
]
```
https://medoo.in/api/where Columns Relationship section
