### ISSUE TITLE
Why not throw an exception?

### ISSUE THREAD

**Issue by DobeLee** [catfan/Medoo#798]
i try to set a incorrect field.
```php
$result = $db->insert($this->table, $data);
var_dump($result); // PDOStatement {...}
var_dump($db->id()); // 0
// id or result both is not FALSE !
```
so, I can only judge this way.
```php
if ($db->error()[0] != '0000') {
    throw new \Exception($db->error()[2]);
}
```
I even 'if' the code wherever use medoo, can't handle it at a time ?
thanks.

**Comment by catfan** [comment]
`$result` is a PDOStatement object. You can call its `rowCount()` to check out the error.

```php
$result = $db->insert($this->table, $data);

if ($result->rowCount() > 0)
{
    // Do something
}
```

**Comment by WrongWay** [comment]
I extended `Medoo ` with a class of mine that checks if there are errors after `Medoo::exec()` and throws an exception.
