### ISSUE TITLE
cant use table.*  

### ISSUE THREAD

**Issue by wufengwuyu13** [catfan/Medoo#799]
**Describe the bug**

$columns  = array('c.*','ci.name(city_name)');
$join = array('[>]city(ci)'=>['c.id'=>'parentid']);
$where = array('c.name'=>'Australia');
$data = $medoo->select('country(c)',$columns,$join,$where);

'*' was replaced. are there any other solutions? 

**Information**
- Version of Medoo newest:
- Type of Database mysql:
- System linux

**Comment by getvivekv** [comment]
@wufengwuyu13  Have you found a solution?
