### ISSUE TITLE
Full Text fails with Condition

### ISSUE THREAD

**Issue by prkwcz** [catfan/Medoo#800]
Hi, 

Full Text Sarching fails when trying to combine it with other conditions.
I guess that *MATCH* is in those cases interpreted as a normal column.

As an Example:

`$database->debug()->select('test', 'cont', ['AND' => ['MATCH' => ['columns' => ['Col1', 'Col2'], 'keyword' => 'key', 'mode' => 'boolean'], 'COL3' => 'A']]);`

should create something like this:

`SELECT cont FROM test WHERE MATCH (Col1, Col2) AGAINST ('key' IN BOOLEAN MODE) AND COL3 = 'A'`

but actually this is the compiled result:

`SELECT cont FROM test WHERE (MATCH IN (Array, 'key', 'boolean') AND COL3 = 'A') `

Would be great if this could be corrected.

**Comment by catfan** [comment]
The `MATCH` should not inside the `AND` keyword. It is being alone like `ORDER`, `LIMIT`.

```php
$database->debug()->select(
	'test',
	'cont',
	[
		'MATCH' => [
			'columns' => ['Col1', 'Col2'],
			'keyword' => 'key',
			'mode' => 'boolean'
		],
		'COL3' => 'A'
	]
);

// SELECT `cont` FROM `test` WHERE `COL3` = 'A' AND MATCH (`Col1`, `Col2`) AGAINST ('key' IN BOOLEAN MODE)
```
