### ISSUE TITLE
Could not find driver

### ISSUE THREAD

**Issue by ImPossiblee** [catfan/Medoo#801]
Fatal error: Uncaught Exception: could not find driver in C:\xampp\htdocs\vendor\catfan\medoo\src\Medoo.php:240 Stack trace: #0 C:\xampp\htdocs\config\Database.php(72): Medoo\Medoo->__construct(Array) #1 C:\xampp\htdocs\index.php(197): Database('1', NULL) #2 {main} thrown in C:\xampp\htdocs\vendor\catfan\medoo\src\Medoo.php on line 240

i cant connect the website to database

**Comment by catfan** [comment]
It's telling you did not install the PDO driver.

Read __PHP PDO Driver Installation__ section from https://medoo.in/api/new

**Comment by ImPossiblee** [comment]
i cant download it there and i think the error is from database i cant
connect the website to database ............

Catfan <notifications@github.com>, 20 Kas 2018 Sal, 16:02 tarihinde şunu
yazdı:

**Comment by Fespinola1** [comment]
lograron solucionarlo colegas?
