### ISSUE TITLE
Action() function can't support for transfer external parameter into it

### ISSUE THREAD

**Issue by cw1427** [catfan/Medoo#803]
**Describe the bug**
Action() function can't support for transfer external parameter into it.
from the source, we could know it only accept the db instance but can't accept the other parameters
	public function action($actions)
	{
		if (is_callable($actions))
		{
			$this->pdo->beginTransaction();

			try {
				$result = $actions($this);

				if ($result === false)
				{
					$this->pdo->rollBack();
				}
				else
				{
					$this->pdo->commit();
				}
			}
			catch (Exception $e) {
				$this->pdo->rollBack();

				throw $e;
			}

			return $result;
		}

		return false;
	}

**Information**
- Version of Medoo:
- Type of Database (MySQL, MSSQL, SQLite...):
- System (Liunx\Windows\Mac):

**Detail Code**
The detail code causes the problem.

**Expected output**
A clear and concise description of what output you expected.

**Comment by catfan** [comment]
You can use `use` keyword for closure function call.

http://php.net/manual/en/functions.anonymous.php

Or variable scope

http://php.net/manual/en/language.variables.scope.php

Up to your project.
