### ISSUE TITLE
When using MySQL query, all integer data became a string

### ISSUE THREAD

**Issue by cooooler** [catfan/Medoo#807]
**Describe the bug**

**Information**
- Version of Medoo: 1.6
- Type of Database (MySQL, MSSQL, SQLite...):MYSQL
- System (Liunx\Windows\Mac):ALL

**Detail Code**
When I use Medoo to query, all the data is a string. For example, the integer data of id will be converted into a string. Why is this?

**Expected output**
A clear and concise description of what output you expected.

**Comment by catfan** [comment]
This is the basic feature of PDO that fetching data from database as string without converting.

If you need to convert the data as you needed, you can use **Data Type Declaration** from here https://medoo.in/api/select

Or you can use `PDO::ATTR_STRINGIFY_FETCHES` (http://php.net/manual/en/pdo.setattribute.php) for your initialization, but this is what I don't recommended.

**Comment by AGuyCoding** [comment]
via **Data Type Declaration**, is there a solution for the type **DECIMAL** also?
i have a column with type **DECIMAL**, a value is **4.53**, but it returns as a string currently
