### ISSUE TITLE
Workerman daemon mode cannot work

### ISSUE THREAD

**Issue by 252589288** [catfan/Medoo#809]
使用medoo1.6.1作为项目的数据库连接层，当结合workerman框架并以守护模式运行时发现数据库连接不能用。如果是正常启动是可以运行的。
workerman 版本3.5.8

----Translated from Google
Use medoo1.6.1 as the database connection layer of the project. When combined with the Workerman framework and running in daemon mode, it is found that the database connection cannot be used. If it is a normal startup it can be run.
Workerman version 3.5.8

**Comment by catfan** [comment]
Sorry, I don't know Workerman framework.

If you want to use Medoo with other frameworks and persistent connection, you may check out https://medoo.in/api/collaboration or `PDO::ATTR_PERSISTENT` http://php.net/manual/en/pdo.connections.php option for initialization
