### ISSUE TITLE
Select using Like 

### ISSUE THREAD

**Issue by tecnicaz** [catfan/Medoo#81]
First of all congratulation on medoo!
I got stuck in the following query
SELECT \* FROM table WHERE ( name LIKE 'foo%' AND address LIKE '%bar' ) 
how to do it with Medoo
Excuse me if this is already answered or addressed some pace else, I just couldn't find it
thank you in advance
Best Regards

**Comment by pwwiur** [comment]
if you mean that "text%" does not working you should fix the ~ operator section in data_implode method

fix these lines:
`if ($operator == '~' || $operator == '!~'){
							if ($type != 'array'){
								$value = array($value);
							}
							$like_clauses = array();
							foreach ($value as $item){
								$item = strval($item);
								if (preg_match('/^(?!(%|\[|_])).+(?<!(%|\]|_))$/', $item)){
									$item = '%' . $item . '%';
								}
	                            elseif(substr($item, -1) == "_"){
	                                $item = $item . '%';
	                            }
	                            
								$like_clauses[] = $column . ($operator === '!~' ? ' NOT' : '') . ' LIKE ' . $this->fn_quote($key, $item);
							}
							$wheres[] = implode(' OR ', $like_clauses);
						}`
