### ISSUE TITLE
Wrong Composer installation instructions in docs

### ISSUE THREAD

**Issue by crtl** [catfan/Medoo#818]
**Describe the bug**

Installation instructions in the docs contain a typo.

**Information**
- https://medoo.in/api/new
- At **Composer Installation**

The instruction says `composer require catfan/Medoo` but should be `catfan/medoo`.
The `M` must/should be lowercase.

**Comment by catfan** [comment]
This is not a typo, it is a composer deprecation warning.

Fixed on 4accb8b345af868b072354b40039fe92096de26f
