### ISSUE TITLE
Google Cloud SQL (Google App Engine)

### ISSUE THREAD

**Issue by janhar** [catfan/Medoo#82]
Is there any plan to support Google Cloud SQL?

**Comment by RideLikeTheWind** [comment]
Sorry just saw this reply - thank you!

**Comment by RideLikeTheWind** [comment]
Hmmm I had a go using the cloudsql method and using my instance:db and root with pass '' on localhost it came back with a file not found error from MySQL, which to me says it can. At the time I had not setup a user, nor did I have a IPv4 address. Any ideas?

**Comment by catfan** [comment]
It's possible to do that on next version 524ce57ec3dc07f86499f139e6e1918d80037578.
