### ISSUE TITLE
SUM table alias alias is wrong

### ISSUE THREAD

**Issue by deawx** [catfan/Medoo#820]
`$totalsale = $db->SUM("order_header", "order_total(a)", [
	"AND" => [
		"branch_code" => "FRKH001",
		"order_status" => 0,
		"end_date[<>]" => ['2018-12-01', '2019-01-11'],
	],
]);
echo $db->last();`

Result
`SELECT SUM(`order_total` AS `a`) FROM `order_header` WHERE (`branch_code` = 'FRKH001' AND `order_status` = 0 AND (`end_date` BETWEEN '2018-12-01' AND '2019-01-11'))`

Thank For Help.

**Comment by catfan** [comment]
The `sum()` will return the value of total number. Why you need to use alias for that?

**Comment by deawx** [comment]
Some cases of my work. I have to set the variable In order to match the work of the customer.
Now, I solved the problem by using $db->query 

Thankz catfan.
Medoo is the best.

**Comment by catfan** [comment]
@deawx You may consider using raw object for this case.

https://medoo.in/api/raw

The first example code provided how to use with `sum()` for `select()` just right.

**Comment by deawx** [comment]
Thank you very much catfan.
