### ISSUE TITLE
raw problem with CONCAT

### ISSUE THREAD

**Issue by osk11** [catfan/Medoo#823]
hi! 
There is a problem with RAW when running with CONCAT check my query

$users->select(['idUser','fullName'=>Medoo::raw('CONCAT(<'name'>,<'middle'>,<'last'>)')],$where);

this runs correctly and brings information but:

$users->select(['idUser','fullName'=>Medoo::raw('CONCAT(<'name'>," ",<'middle'>," ",<'last'>)')],$where);

this fails when I try to separate the columns with spaces

**Comment by catfan** [comment]
That's PHP string quote problem. You may check out your quote identifier.

And there is no need to quote for column name, `CONCAT(<name>,<middle>,<last>)` is enough.
