### ISSUE TITLE
Multi Join not working

### ISSUE THREAD

**Issue by ZeeshanSultan** [catfan/Medoo#826]
**Describe the bug**
The given medoo query returns an empty array 

**Information**
- Version of Medoo: 1.6.1
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Linux

**Detail Code**

//SQL Query
$data="SELECT  o.order_id, o.total_cost, o.total_discount, o.payment_method, o.shipping_address, o.stats, p.en_name, p.price as product_price,u.en_unit AS unit, op.quant, op.price AS order_price FROM farmtoho_web.order o LEFT JOIN order_products op ON o.order_id = op.order_id
            LEFT JOIN products p ON p.prd_id = op.prduct_id
            LEFT JOIN units u ON p.unit_id = u.unit_id 
            WHERE o.order_id=$order_id";

//Equivalent Query
$data = $database->select("order(o)", ["[>]order_products(op)" => "order_id", "[>]products(p)" =>  ["prduct_id" => "prd_id"] ],	["o.order_id","o.total_cost","o.total_discount","o.payment_method","o.shipping_address","o.stats","op.quant","op.price"],
	['order_id' =>  $order_id ]);

**Expected output**
Array ( [0] => Array ( [0] => 10 [order_id] => 10 [1] => 670 [total_cost] => 670 [2] => 0 [total_discount] => 0 [3] => Not Specified [payment_method] => Not Specified [4] => REDACTED [shipping_address] => REDACTED [5] => Delivered [stats] => Delivered [6] => Mango white chaunsa [en_name] => Mango white chaunsa [7] => 270 [product_price] => 270 [8] => Kg [unit] => Kg [9] => 2 [quant] => 2 [10] => 0 [order_price] => 0 ) [1] => Array ( [0] => 10 [order_id] => 10 [1] => 670 [total_cost] => 670 [2] => 0 [total_discount] => 0 [3] => Not Specified [payment_method] => Not Specified [4] => REDACTED [shipping_address] => REDACTED [5] => Delivered [stats] => Delivered [6] => Mango Sindhri [en_name] => Mango Sindhri [7] => 150 [product_price] => 150 [8] => Kg [unit] => Kg [9] => 2 [quant] => 2 [10] => 0 [order_price] => 0 ) [2] => Array ( [0] => 10 [order_id] => 10 [1] => 670 [total_cost] => 670 [2] => 0 [total_discount] => 0 [3] => Not Specified [payment_method] => Not Specified [4] => REDACTED [shipping_address] => REDACTED [5] => Delivered [stats] => Delivered [6] => Peas [en_name] => Peas [7] => 50 [product_price] => 50 [8] => Kg [unit] => Kg [9] => 1 [quant] => 1 [10] => 0 [order_price] => 0 ) )

**Comment by catfan** [comment]
```php
$data = $database->select("order(o)", [
	"[>]order_products(op)" => "order_id",
	"[>]products(p)" => ["prduct_id" => "prd_id"]
], [
	"o.order_id",
	"o.total_cost",
	"o.total_discount",
	"o.payment_method",
	"o.shipping_address",
	"o.stats",
	"op.quant",
	"op.price"
], [
	'order_id' => $order_id // <--- Where the column 'order_id' come from?
]);
```

In your case `'order_id' => $order_id` should be `'o.order_id' => $order_id`.

**Comment by ZeeshanSultan** [comment]
Thanks worked like a charm 💯
