### ISSUE TITLE
JavaScript code can be inserted and executed when printed out.

### ISSUE THREAD

**Issue by siteantipas** [catfan/Medoo#827]
**Bug Description**
Security flaw

**Information**
-` $db->insert()`

I noticed JavaScript can be inserted and executed when printed out. Which means Medoo does not use` htmlentities()` function to prevent against such.

**Comment by godigi** [comment]
It's not the job of a database wrapper to handle this. In your application, you should focus on sanitizing input and escaping the output yourself.

**Comment by skylarmt** [comment]
What if I wanted to store JavaScript in a database?  I wouldn't want it to come out mangled.

**Comment by catfan** [comment]
The prevention of XSS injection or filtering other unexpected data is up to the project itself, not the framework.

You may check out and convert the user input before inserting into database, or filter it before outputting to client.

**Comment by siteantipas** [comment]
Okay, that's true. I understand now.
