### ISSUE TITLE
[where between <> or ><] type is text ,the result is error in sqlite and mysql

### ISSUE THREAD

**Issue by withu2018** [catfan/Medoo#829]
**Describe the bug**

**Information**
- Newest of Medoo:
- Type of Database (MySQL, SQLite):
- System (Windows):

use [where between <> or ><], type is text(Numbers exist in text columns) ,the result is error in sqlite and mysql

**Comment by catfan** [comment]
Sorry, I'm not really sure I can understand what's your mean.

Would you like to provide more details?

`<>` and `><` should only be available for number and datetime.

https://medoo.in/api/where

**Comment by withu2018** [comment]
thank you.
but,Can you add conversion function?
```
$database->select("account", "user_name", [
	"[int]age[<>]" => [200, 500]
]);

```

SQL:
`select * from account where CAST(column as int) between 200 and 500`

**Comment by catfan** [comment]
There is no need to do that. If the column data are all number, you should set it as Integer, not text.
