### ISSUE TITLE
Medoo can't connect to postgres server

### ISSUE THREAD

**Issue by dawuwu** [catfan/Medoo#834]
**Describe the bug**

**Information**
- Version of Medoo: 1.6.1
- Type of Database (MySQL, MSSQL, SQLite...): Postgres
- System (Liunx\Windows\Mac): Windows

When using the medoo standard configuration to connect to a pgsql server I get the error: 
"Incorrect connection options"

When changing the same config to a mysql server it works.
Also when passing a pdo object to the pdo parameter of medoo it also works to connect to the pgsql server.

The config is 100% correct, no typo or something like that.

**Comment by catfan** [comment]
Would you like to post your config (initialization) code here?

**Comment by dawuwu** [comment]
$database = new Medoo([
	'database_type' => 'PostgreSQL',
	'database_name' => 'dbname',
	'server' => 'localhost',
	'username' => 'username',
	'password' => 'password']);

**Comment by catfan** [comment]
The `database_type` should be `pgsql`, not `PostgreSQL`.

**Comment by dawuwu** [comment]
oh thank you, I thought I need to use the value of the left column on the PHP_PDO Extension list
