### ISSUE TITLE
BETWEEN keyword support

### ISSUE THREAD

**Issue by ZeeshanSultan** [catfan/Medoo#836]
**Describe the bug**

**Information**
- Version of Medoo:  1.6.1
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Windows

**Detail Code**

Medoo Query:
`$database->select("discount_offers", "*", Medoo::raw('WHERE ("'.$date.'" between start_date AND end_date) AND status = 1'));`

My desired SQL Query :
`SELECT * FROM discount_offers WHERE ("2019-05-09" BETWEEN start_date AND end_date) AND status = 1`

**Expected output**
This Medoo Query generates the desired query as verified by debug but No output is returned from Medoo. If we run the generated query directly on MySQL it returns output as expected

**Comment by catfan** [comment]
https://medoo.in/api/where

`[><]` and `[<>]` is also available for datetime
