### ISSUE TITLE
Problem about using custom query

### ISSUE THREAD

**Issue by programmexwz** [catfan/Medoo#839]
我在使用medoo的过程中遇到一个问题，但是我无法自己解决，使用 ` $database->pdo->setAttribute(***) ` 我无法创建mysql的event定时任务，想知道是否是我自己用错了，请您看到后务必回复我一下，下面直接上截图。
![github-medoo-1](https://user-images.githubusercontent.com/39935705/58009586-5d3e1e00-7b21-11e9-9472-004c6f9f1b38.png)
![github-medoo-2](https://user-images.githubusercontent.com/39935705/58009600-629b6880-7b21-11e9-883c-958eb2975ce3.png)

再次感谢。

**Comment by catfan** [comment]
I don't know why you use `query()` like this. Using `query()` to execute custom query without quotation from pdo object is not the way we recommended.

Please read our documentation about how to create custom query and consider using quotation syntax  instead.

https://medoo.in/api/query

**Comment by programmexwz** [comment]
Thank you very much for your answer. I am probably a bit confused. Maybe the method used is wrong. I will try other methods again later, thank you again for your answer.

**Comment by programmexwz** [comment]
@catfan Sorry, I am bothered, I still want to ask a question.

When I use `PDO->query`, I can create event scheduling tasks. 
When I use `medoo->query`, I can't create event scheduling tasks.

Please see the screenshot below.

1. Use PDO
![pdo1](https://user-images.githubusercontent.com/39935705/58075619-b6b65380-7bda-11e9-9bae-0cd79c6d8aa3.png)
2.Use Medoo
![pdo2](https://user-images.githubusercontent.com/39935705/58075649-ccc41400-7bda-11e9-9c8a-eaaa72c4a040.png)
![log](https://user-images.githubusercontent.com/39935705/58075654-d188c800-7bda-11e9-919c-f01b069ad573.png)

Results of two executions
![result](https://user-images.githubusercontent.com/39935705/58075715-f5e4a480-7bda-11e9-9b17-d99d63137385.png)

Looking forward to your reply!

**Comment by catfan** [comment]
Did you really read the documentation and the link I replied above? Especially the quotation warning for custom query.

There is nothing I can help if you still using like this way.

**Comment by programmexwz** [comment]
@catfan 
I am very sorry, I have learned the lesson.
But I can't create it using the following method, but also use `debug()` to print it out. Maybe I still don't know how to write it. Please give me some help.
thank you very much.
Medoo SQL
```php
$order_number = 'O'.date('YmdHis').rand(100000, 999999);

$database->debug()->query('CREATE DEFINER = <root>@<localhost> EVENT <' . $order_number . '> ON SCHEDULE AT : dateTime ON COMPLETION NOT PRESERVE ENABLE DO call closeTrade(: order);', [
    ': dateTime' => date('Y-m-d H:i:s', strtotime("+1 day")),
    ': order' => $order_number
]);
```

Print result
```sql

CREATE DEFINER = `root`@`localhost` EVENT `O20190523101243432968` ON SCHEDULE AT '2019-05-24 10:12:43' ON COMPLETION NOT PRESERVE ENABLE DO call closeTrade('O20190523101243432968');
```

Looking forward to your reply.😊😊

**Comment by programmexwz** [comment]
@catfan 
After trying N times, I finally succeeded. I used the following method.
```php

$order_number = 'O'.date('YmdHis').rand(100000, 999999);

$my_db->query("CREATE DEFINER = <root>@<localhost> EVENT <$order_number> ON SCHEDULE AT :dateTime ON COMPLETION NOT PRESERVE ENABLE DO call closeTrade(:order);", [
    ':dateTime' => date('Y-m-d H:i:s', strtotime("+1 day")),
    ':order' => $order_number
]);
```
`：variable `  No spaces can be used in the middle.

I am very sorry, this is the problem caused by my mistake and I am very grateful for your answer.😊😊

**Comment by catfan** [comment]
@programmexwz Congratulations on your success. Additionally, there is no need for the last `;`.
