### ISSUE TITLE
Suggest a change: implode($stack, ';')

### ISSUE THREAD

**Issue by tianyiw2013** [catfan/Medoo#841]
**implode** is used in many places in medoo，The method of use is as follows: `implode($stack, ';')`、`implode($outer_conjunctor . ' ', $stack)`、`implode($joins, ' AND ')` etc.

PHP Manual：
`implode ( string $glue , array $pieces ) : string`

It is suggested to change to the usage specified in the PHP manual.

[Medoo.zip](https://github.com/catfan/Medoo/files/3250610/Medoo.zip)

**Comment by tianyiw2013** [comment]
see https://www.php.net/manual/en/function.implode.php

**Comment by tianyiw2013** [comment]
![微信图片_20190604131201](https://user-images.githubusercontent.com/4644588/58852761-5d661e00-86ca-11e9-9072-28589adc8b10.png)
vscode problem hints ↑

**Comment by catfan** [comment]
Great, that's will be fixed.

**Comment by tianyiw2013** [comment]
thanks.good job.
