### ISSUE TITLE
"Query + IN" without quotes. How?

### ISSUE THREAD

**Issue by ermaxinc** [catfan/Medoo#842]
> $ids = "1,5,8";
> $data =  $db->debug()->query(
>         "SELECT * FROM items WHERE 'group' IN (:ids)", [
>             ":ids" => $ids
>         ]
>     )->fetchAll();

SQL:
`SELECT * FROM items WHERE 'group' IN ('1,5,8') <-- with quotes '1,5,8'`

Need SQL:
`SELECT * FROM items WHERE 'group' IN (1,5,8)`

**HOW?**

**Comment by Babasile** [comment]
![image](https://user-images.githubusercontent.com/18406066/59541130-4c09e680-8f00-11e9-8a83-a91a87eab10f.png)

It put quotes because $ids is a string.

**Comment by abdul-alim** [comment]
You have defined `$ids` as string, which is considered a single value. Try passing it as an array.

Alternatively, you can do something like this. 
```
$ids = array(1,5,8);
$database->select("items", "*", [
    "group" => $ids
]);
```
// Generated SQL
`SELECT * FROM items WHERE group IN (1, 5, 8)`

**Comment by blessedjasonmwanza** [comment]
@ermaxinc ..  Well, as explained above, your $ids is a string. convert it to an array like;
$ids = "1,5,8";
 $ids = explode(",", $ids)

**Opinion** :: Also for easy code readability, try not to mix SQL normal statements into Medoo's
