### ISSUE TITLE
QUERY + RAW (PDO::quote() expects parameter 1 to be string)

### ISSUE THREAD

**Issue by ermaxinc** [catfan/Medoo#843]
**Describe the bug**
I try use **$db->query()** with **Medoo::raw()**

**Information**
- Version of Medoo: 1.6.1
- Type of Database : MySQL
- System : Windows

**Detail Code**

Try **without** **RAW**

> 		$data = $db->debug()->query("
> 					SELECT <id>, <group> FROM `items` WHERE `group` IN (:groups);
> 				", [
> 				":groups" => implode(",", [1,2,3])
> 			]
> 		)->fetchAll(PDO::FETCH_ASSOC);

> SELECT `id`, `group` FROM `items` WHERE `group` **IN ('1,2,3')** 

All ok, but **IN** with **'** (quotes)

Now try **with** **RAW**

> 		$data = $db->debug()->query("
> 					SELECT <id>, <group> FROM `items` WHERE `group` IN (:groups);
> 				", [
> 				":groups" =>  \Medoo\Medoo::raw(implode(",", [1,2,3])) 
> 			]
> 		)->fetchAll(PDO::FETCH_ASSOC);

> **PDO::quote() expects parameter 1 to be string, object given in** 

**Expected output**

Need
> SELECT `id`, `group` FROM `items` WHERE `group` **IN (1,2,3)** 
**IN** without **'** (quotes)

**Comment by catfan** [comment]
It's unable to bind array as placeholder. The PDO didn't support for this.

But for your case, it's completely possible using Medoo `select()` to handle this.

Medoo's select has a special function to deal with `IN (xxx, xxx)`.
