### ISSUE TITLE
CockroachDB: Relation does not exist

### ISSUE THREAD

**Issue by tobiasmuehl** [catfan/Medoo#845]
**Describe the bug**
Generated SELECT and INSERT queries always fail with `relation "<table name>" does not exist`. 

**Information**
- Version of Medoo: 1.6.1 - 53a02b300d673f716cb06bf0e24fd774ec53939f
- Type of Database (MySQL, MSSQL, SQLite...): cockroachDB (pgsql driver)
- System (Liunx\Windows\Mac): Linux

**Detail Code**

```php
// proof that the connection works
print_r($db->query('SELECT 1;')->fetchAll());

// Array
// (
//     [0] => Array
//        (
//            [?column?] => 1
//            [0] => 1
//        )
//
// )

$result = $db->query('suggestions', 'suggestion', ['keyword' => 'test']);
print_r($result);
// Array
// (
// )

print_r($db->error());
// (
//     [0] => 00000
//     [1] => 7
//     [2] => ERROR:  relation "suggestions" does not exist
// LINE 1: SELECT "suggestion" FROM "suggestions" WHERE "keyword" = $1
//                                  ^
// )
```

**Expected output**

```php
$result = $db->query('suggestions', 'suggestion', ['keyword' => 'test']);
print_r($result);
// Array
// (
//  [0] => 'foo',
//  [1] => 'bar'
// )
```

Outruled DB problems, same query with the [simplon](https://github.com/fightbulc/simplon_postgres) library returns rows.

**Comment by catfan** [comment]
You should know what `query()` parameter is. https://medoo.in/api/query

In your case, you may use `select()` not `query()`.

https://medoo.in/api/select

**Comment by tobiasmuehl** [comment]
Pretty sure that's just a typo and I used `select`, but don't have access to CockroachDB anymore so not an issue for me personally

**Comment by catfan** [comment]
What's your connection option?

**Comment by tobiasmuehl** [comment]
`pgsql`. But I'm fine to leave this issue closed because the database server is already gone regardless.

**Comment by catfan** [comment]
@tobiasmuehl I'm not sure how CockroachDB works as PostgreSQL. But it may work with if CockroachDB can execute PostgreSQL's queries.
