### ISSUE TITLE
WHERE  clause with ORDER BY & LIMIT don't work !

### ISSUE THREAD

**Issue by jogratna** [catfan/Medoo#846]
**Describe the bug**
simple where clause with order by and limit don't work. There is serious bug in the code.
**Information**
- Version of Medoo: 1.6.1
- Type of Database (MySQL):
- System (Linux):

**Detail Code**
$transacts=$_dbObj->debug()->select("tbltransactions","fldrate",
[ "AND" => [
"flduid" => $uid, 
"fldstock_id" => $data["fldstock_id"], 
"fldtype" => 1
]],[ 
"LIMIT" => [0,1],
"ORDER" => [
"flddate" => "DESC"
]
]
);

gives this output;

SELECT `fldrate` FROM `tbltransactions` WHERE (`flduid` = 1 AND `fldstock_id` = 1 AND `fldtype` = 1)

**Expected output**

SELECT `fldrate` FROM `tbltransactions` WHERE (`flduid` = 1 AND `fldstock_id` = 1 AND `fldtype` = 1) ORDER BY 'flddate' DESC LIMIT 0,1

**Comment by catfan** [comment]
Just check out the documentation seriously https://medoo.in/api/select. The conditions and `LIMIT/ORDER` are together in the same array.

```php
[
	"AND" => [
		"flduid" => $uid,
		"fldstock_id" => $data["fldstock_id"],
		"fldtype" => 1
	],
	"LIMIT" => [0,1],
	"ORDER" => ["flddate" => "DESC"]
]
```
