### ISSUE TITLE
Reconnecting

### ISSUE THREAD

**Issue by skyzonemc** [catfan/Medoo#847]
I use Medoo in a plugin for PocketMine. Medoo is only beeing used when there are players online. If a player joins when there weren't any players for some time, Medoo looses connection and the server crashes. How can I check if Medoo is still connected and reconnect?

**Comment by catfan** [comment]
You can use PDO get attribute method for connection status `$database->pdo->getAttribute(PDO::ATTR_CONNECTION_STATUS);` or just check out the `$database->info()`.

**Comment by skyzonemc** [comment]
@catfan and how to reconnect? Should I just create a new medoo object?

**Comment by catfan** [comment]
Yes, recreating a new Medoo instance will be well done. Just up to your mechanism.
