### ISSUE TITLE
Support for Tarantool? 

### ISSUE THREAD

**Issue by zilveer** [catfan/Medoo#848]
Hi,
It would be awesome if you guys can add support for Tarantool.io which is a blazing fast database both disc and memory based.
It also supports SQL syntaxes which I want (if possible) you guys to implement in this project.

Heads up and keep up the good work !

Regards

**Comment by catfan** [comment]
I don't know about it. However if this product supported using PDO and executing SQL query, it can use with Medoo without additional implement. If not, there is nothing can do to for this.

**Comment by zilveer** [comment]
There is not PDO instead there is a package called PHP client for Tarantool which is used to connect to Tarantool and can execute SQL queries.
@catfan would you mind to think about it? It would be appreciated.

Tarantool is blazing fast and has both in memory storage and in disk storage .

Here is the link to PHP client for Tarantool just in case you change your mind.

Regards

**Comment by catfan** [comment]
@zilveer Sorry, I don't understand what's your mean called `support` for this with Medoo. Medoo is only and always a PDO-based framework for connecting and manipulating SQL database.

Calling us to support for this, is calling the project to be reconstructed and be recreated. That's not make sense.

**Comment by zilveer** [comment]
Thanks for your reply but I don't think that it needs to be in the way you describe, once you see that Tarantool works in the same way SQL behaves you will then understand that it wouldn't need any refactoring.

Regards
