### ISSUE TITLE
v1.7 get method bug error

### ISSUE THREAD

**Issue by webgoto** [catfan/Medoo#850]
in Medoo.php
public function get

1579: $this->dataMap($data[ 0 ], $columns, $column_map, $result, true);

Required parameter missing

**Comment by catfan** [comment]
Thank, this fixed on b2d8327f5fe800b9646f683dfc7a1d6b496a370f in emergency.

**Comment by webgoto** [comment]
Thank you for your quick response.
However, is this bug different from #851?

**Comment by catfan** [comment]
@webgoto Sorry for the inconvenience, this is another problem. Will fix it soon. This is really embarrassing for the new release.

**Comment by webgoto** [comment]
Not at all. Thank you for developing and updating this very useful library.
