### ISSUE TITLE
AMPHP Implementation?

### ISSUE THREAD

**Issue by MattiaBLX** [catfan/Medoo#852]
Hi! Will you implement async with amphp using https://github.com/amphp/mysql and https://github.com/amphp/postgres?

**Comment by catfan** [comment]
If this project is using PDO for MySQL, just configure the correct DSN connection option for this will be OK. There is nothing additional implement needed.

**Comment by jmfederico** [comment]
I am confused on how this can be done (if at all).

I am in need of non-blocking SQL queries, which is not possible with Medoo right now as far as I can tell.

I am using https://github.com/amphp/postgres, but the development experience is not on par :(

Any insights on how this can be achieved, if at all, would be much appreciated.
