### ISSUE TITLE
Hi, the 'rand' return array count How to modify?

### ISSUE THREAD

**Issue by d1y** [catfan/Medoo#853]
```php
  $vd = letSQL()->rand('videos','*');
  dd($vd)

```

the Not mentioned in the documentation
Can I customize the length of the array?
🧐 Can only be used $db->query(RAW) ?

**Comment by d1y** [comment]
The above code returns all the data in my table.
I did not add where
I make it random, but just display random 10 rows of data
👀

**Comment by catfan** [comment]
The `rand()` is support `where` condition. Just add `LIMIT` to control it.

https://medoo.in/api/rand

**Comment by d1y** [comment]
> The `rand()` is support `where` condition. Just add `LIMIT` to control it.
> 
> https://medoo.in/api/rand

This seems to be repeated🧐

**Comment by lnermif** [comment]
> > 该`rand()`是支持`where`条件。只需添加`LIMIT`即可控制它。
> > https://medoo.in/api/rand
> 
> 这似乎是重复的
I wrote it.
 `$this->medoo->rand('copy_of_fave_img',['id'],['LIMIT'=>1])`

**Comment by lnermif** [comment]
> > 该`rand()`是支持`where`条件。只需添加`LIMIT`即可控制它。
> > https://medoo.in/api/rand
> 
> 这似乎是重复的

`$this->medoo->rand('test_table',['id'],['LIMIT'=>1])`
