### ISSUE TITLE
how to use lower function in medoo

### ISSUE THREAD

**Issue by wenger67** [catfan/Medoo#854]
mysql :

selelct * from people where lower(name) = 'john';

medoo:

medoo->select('people', '*', 
[ name => 'john']);

???

while i want to convert column name into lowercase then compare with 'john'

**Comment by catfan** [comment]
Just use raw object https://medoo.in/api/raw

**Comment by IonutPopescuRO** [comment]
@catfan I also need to use lower:
`			"AND" => [
				"lang" => $lang,
				"id" => $id,//an array
				"name[~]" => $string
			],`
How I'm supposed to do this? I need to use lower for name, I do not want to use it Medoo::raw('WHERE...')

**Comment by catfan** [comment]
@IonutPopescuRO lowering the column name is equal to lower the variable.

So, just:
```php
"name[~]" => strtolower($string)
```

Any also, using `LIKE` condition is case insensitive.

**Comment by IonutPopescuRO** [comment]
@catfan I know how to use strtolower, but name it is still the same in database... i can' use "LOWER(name)[~]"
