### ISSUE TITLE
API Documentation for Create and Update has disappeared

### ISSUE THREAD

**Issue by systemdev-overrideitsolutions** [catfan/Medoo#856]
The documentation for table creation and deletion has disappeared. I used that documentation the other day but it's no longer there.

https://medoo.in/api/create

This link is now empty.

![image](https://user-images.githubusercontent.com/51228595/61953700-5d421a80-afb7-11e9-9992-140d432d6155.png)

**Comment by catfan** [comment]
Sorry, we are just updating the system hour ago, and it's available now.
