### ISSUE TITLE
Fatal error on get method

### ISSUE THREAD

**Issue by facuonline** [catfan/Medoo#857]
I think the reason behind this bug is that the methods get($table, $columns, $where) and get($table, $join, $columns, $where) are exchanged, causing a fatal **ArgumentCountError** exception.

- Version of Medoo: 1.7
- Type of Database: MySQL

**Detail Code**
Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Medoo\Medoo::dataMap(), 5 passed in ...\vendor\catfan\medoo\src\Medoo.php on line 1581 and exactly 6 expected in ...\vendor\catfan\medoo\src\Medoo.php:1169
Stack trace:
#0 ...\vendor\catfan\medoo\src\Medoo.php(1581): Medoo\Medoo->dataMap(Array, Array, Array, Array, true)

**Expected output**
According to documentation and previous usage should have returned an array with specified fields in second argument.

**Comment by catfan** [comment]
You may need to upgrade to v1.7.2. That's fixed this problem.

**Comment by facuonline** [comment]
1.7.2 solved this problem. On a version check I discovered the version in use was actually 1.7.x-dev

Closing the issue
