### ISSUE TITLE
Help needed, problems with sqlite

### ISSUE THREAD

**Issue by pwFoo** [catfan/Medoo#860]
I try to use Medoo with sqlite and have some problems.

```
require_once('vendor/medoo.php');
$db = new Medoo\Medoo([
    'database_type' => 'sqlite',
    'database_file' => ':memory:',
]);

$db->create("users", array(
    'id' => array(
        "INT",
		"NOT NULL",
		"AUTO_INCREMENT",
		"PRIMARY KEY",
    ),
    'name' => array(
        "VARCHAR(30)",
		"NOT NULL",
    )
));

$res = $db->insert('users', array(
    'name' => "Andre",
));

print_r($res);
```

1) If I try to need in memory sqlite database with more than one php script maybe database_file need to be `:memory::?cache=shared` or `mode=memory`?
2) How to output tables like `show tables`?
3) Why is my output empty? I created a table, inserted a new row and tried to select it?

**Comment by pwFoo** [comment]
Medoo 1.7.2
Linux
php-fpm 7.3.6

**Comment by pwFoo** [comment]
With debug() / log() I just see the query, but not the error / return value of the executed query?

**Comment by pwFoo** [comment]
@catfan 
Also tested sqlite db as file, but it is just an empty file, also if I create a table and insert a row.

**Comment by pwFoo** [comment]
Checked file permissions and code... DB file is empty.
No error with create table or insert a row, but still empty file.

Tested with plain sqlite works fine.
So looks like a bug

Anyone have the same problems?

**Comment by catfan** [comment]
It's because the SQLite create table option is different.

There is no `varchar` type for SQLite. Just using TEXT instead.
Just use `INTEGER` for `INT`.
The row with `INTEGER PRIMARY KEY` will be auto-increased.

For your case, the CREATE statement should be:
```php
$database->create("users", [
	'id' => [
		"INTEGER",
		"PRIMARY KEY",
	],
	'name' => [
		"TEXT",
		"NOT NULL",
	]
])
```

**Comment by catfan** [comment]
Read more from: https://www.sqlite.org/lang_createtable.html

**Comment by pwFoo** [comment]
Thanks! Should be my problem.
I moved to an orm some days ago, but I'll check it. 👍
