### ISSUE TITLE
How to remove the numbers in the results?

### ISSUE THREAD

**Issue by cherimo** [catfan/Medoo#863]
Hey,

I am using the advanced query to input my query, something like this:
`$db->query("SELECT <p.event_title>, <p.event_begin> FROM <tickets> AS e INNER JOIN <party> AS p ON <e.event_id> = <p.id> WHERE <e.ticket_member> = ".$userId."")->fetchAll();`

The results are:

`[{  
         "event_title":"Workshops",
         "0":"Workshops",
         "event_begin":"1575354000",
         "1":"1575354000"
      },
      {  
         "event_title":"Workshops",
         "0":"Workshops",
         "event_begin":"1575354000",
         "1":"1575354000"
      },
      {  
         "event_title":"Workshops",
         "0":"Workshops",
         "event_begin":"1575354000",
         "1":"1575354000"
      }]`

How can i remove the 0s and 1s keys?

**Comment by catfan** [comment]
Check out here: #139
