### ISSUE TITLE
Syntax SQL vs Medoo

### ISSUE THREAD

**Issue by Philippe-M** [catfan/Medoo#868]
Hello, in php function I use the same sql query for several context that evolves according to the parameters passed to the function.

For the moment I have not found how to transpose this request with the medoo syntax. Is it possible or is it better to keep the sql syntax?

```
  public function getStatsDetailFamille($bpcord='', $bpaadd='', $tsccod='', $rep='', $itmref, $annee, $tsicod2, $moisDeb, $moisFin) {
    $query = "SELECT ";
    $query .= " SUM(sinvoiced.netpri*sinvoiced.qty * (case when sinvoicev.invtyp = 1 then 1 else -1 end)) AS netpri, sinvoiced.itmref, sinvoiced.tsicod2";
    $query .= " FROM sinvoicev";
    $query .= " INNER JOIN sinvoiced ON sinvoicev.num = sinvoiced.num";
    $query .= " WHERE ";
    if(!empty($bpcord)) {
      $query .= "  sinvoicev.bpcinv = '".$bpcord."' AND";
    }
    if(!empty($bpaadd)) {
      $query .= "  sinvoicev.bpaadd = '".$bpaadd."' AND";
    }
    if(!empty($tsccod)) {
      $query .= "  sinvoicev.tsccod = '".$tsccod."' AND";
    }
    if(!empty($rep)) {
      $query .= "  sinvoicev.rep1 IN ('".$rep."') AND";
    }
    if(!empty($tsicod2)) {
      $query .= "  sinvoiced.tsicod2 = '".$tsicod2."' AND";
    }
    if(!empty($moisDeb)) {
      $query .= "  MONTH(sinvoicev.invdat) BETWEEN ".$moisDeb." AND ".$moisFin." AND";
    }
    $query .= "  sinvoiced.itmref = '".$itmref."' AND";
    $query .= "  YEAR(sinvoicev.invdat) = '".$annee."'";
    $query .= " GROUP BY sinvoiced.itmref";
    $query .= " ORDER BY sinvoiced.itmref";

    $stat = $this->database->query($query)->fetchAll(PDO::FETCH_ASSOC);

    return $stat;
  }
```

**Comment by facuonline** [comment]
I have not tried to achieve this myself but you can totally make JOINS, multiple ANDS, GROUP BY and ORDER BY.

[SELECT Syntax](https://medoo.in/api/select)
[WHERE Syntax](https://medoo.in/api/where)

**Comment by Philippe-M** [comment]
The problem is not the JOIN or ORDER, I have already made requests with the syntax Medoo but the php conditions of my WHERE. This query serves me in many cases, they are handled by if and turns on or off WHERE clauses.

My idea is to have a single syntax for my requests at the level of my php code to simplify the reading.

Blows my question is: is it possible, with the syntax Medoo, to reproduce the different if?

**Comment by catfan** [comment]
The situation of your query is having too much SQL calculation for it. That's mean, the database will execute the calculate function for each row for getting the result while the SQL is querying in real-time. The query is become complex and low performance.

Although it's possible, this is not a good idea for that.

Perhaps you can consider reconstruct the database, like adding a new column to save the calculated or formated value while inserting/updating the row. That's can simplify the query and increase the performance.

Medoo's syntax can't 100% cover all SQL complex query cases. It's only targeting for most common usage.

Additionally, Medoo `query()` is supported quoting syntax for preventing injection and quotation problem. That's will make the custom query more readable and easier for binding value. 

https://medoo.in/api/query
