### ISSUE TITLE
Where, how to use find_in_set()？

### ISSUE THREAD

**Issue by Sgenmi** [catfan/Medoo#870]
select uid,name where uid in (10,20,30) and find_in_set('1', type)

**Comment by ShuiPingYang** [comment]
@Sgenmi 请问怎么再select里面使用呢？尝试了好几种方式都不行，不想整条语句都用raw。

**Comment by ShuiPingYang** [comment]
@Sgenmi 我自己解决了。提了pr，https://github.com/catfan/Medoo/pull/909
