### ISSUE TITLE
发现缺陷：select('db1.tb1',null,'*')无法实现！

### ISSUE THREAD

**Issue by davidWeiZhou** [catfan/Medoo#872]
数据库迁移，同一服务器：127.0.0.1，两个数据库db1,db2,从db1的tb1查询数据，插入到db2的tb2表，字段名不完全一样，查询时写：select('db1.tb1',null,'*')，把数据库名带着走，居然不行。

**Comment by davidWeiZhou** [comment]
1.6版本中，不能用三参数的select($table, $columns, $where)函数，只能写四参数的函数select($table, $join, $columns, $where)，是强制我写四参数吗？php不像python，php的函数参数都是按顺序来的，而python可以实现按需要传入参数，你只要把参数的名写对就行。

**Comment by davidWeiZhou** [comment]
同一服务器，我建了两实例，每个实例对应一个数据库，进行迁移，因为都有两个表：article, article_sub，所以，不能用单独的sql语句去插入实现，只能用php写程序来实现，但是，我发现，medoo不能跨库。

**Comment by davidWeiZhou** [comment]
还有一个不人性化的地方，字段必须写成数组，能写字符串吗？比如直接写：select('表','字段1,字段2,字段3,...')，这样不是更人性化，更方便合理呢，你觉得呢？

**Comment by davidWeiZhou** [comment]
join查询单独查询单独命名吧，不要和select一起写了，四个参数合并到三个参数，肯定增加了程序的复杂性。现有的php可没有这么聪明，现有的php，哪怕是php8.0都没有做到像python那样，任意参数乱序传入，要是哪一天php做到了，就可以select函数，三个参数，四个参数合在一起写了。

**Comment by catfan** [comment]
Please abide by our issue template while opening new issue for bug report or feature request.

GitHub issue is not the suitable place for complaining project design.

Read our official documentation to learn more.
https://medoo.in
