### ISSUE TITLE
I don't sort sql select in medoo

### ISSUE THREAD

**Issue by pusand** [catfan/Medoo#873]
I encountered a problem

 $values = '5,2,4';
    $result = $database->select('movie','*',[
        "OR" => [
            "id" => explode(',',$values),
            ]
    ]);

output 2,4,5 !!
but i need output 5,4,2 don't sort

help me. !!

**Comment by catfan** [comment]
You need to use order by customized order.

Read Order Condition section from https://medoo.in/api/where

```php
"ORDER" => [
	"id" => ["5", "2", "4"]
]
```

**Comment by pusand** [comment]
Thank you very much
