### ISSUE TITLE
Enhance order to return random entries

### ISSUE THREAD

**Issue by bedengler** [catfan/Medoo#876]
I didn't find a possibility to do random orders (ORDER BY RAND() ). 
So I had to enhance the source code (from line 888). I added the following lines:
`elseif ($ORDER == "RAND()")
				{
					$where_clause .= ' ORDER BY ' . $ORDER;	
				}
				`

So if you set ['ORDER' => "RAND()"] the resulting query orders randomly...

You may add this feature to the official source. Or is there another possibility to sort randomly?

**Comment by catfan** [comment]
There is an official method just called `rand()` https://medoo.in/api/rand.
