### ISSUE TITLE
Medoo is having issues with table names containing hyphens (minus sign “-”)

### ISSUE THREAD

**Issue by lanyizi** [catfan/Medoo#877]
When containing hyphens (`-`), sometimes table names cannot be properly quoted by the `tableQuote($table)` method because they (table names) are not even being matched by the previous `preg_match()`.

**Information**
- Version of Medoo: 1.72 (But I've looked at the code and looks like 1.73 still have this issue)
- Type of Database: MySQL
- System: Linux

**Detail Code**
The following code
```
$qqs = $database->select('nss-avatars', [
    '[<]nss-players' => 'qq'
], [
    'qq',
], [
    'ORDER' => [
        'nss-avatars.lastUpdate' => 'ASC'
    ],
    'LIMIT' => $count
]);
```
Produces
```
SELECT `qq` FROM "nss-avatars" 
RIGHT JOIN `nss` USING (`qq`) 
ORDER BY "nss-avatars".`lastUpdate` ASC 
LIMIT 2
```

**Expected output**
```
SELECT `qq` FROM "nss-avatars" 
RIGHT JOIN `nss-players` USING (`qq`) 
ORDER BY "nss-avatars".`lastUpdate` ASC 
LIMIT 2
```

At [line 1062 of Medoo.php](https://github.com/catfan/Medoo/blob/113519d8032044a1d7b0852740e8f8d210b4dee2/src/Medoo.php#L1062), I see there is a `preg_match()` matching table name with `[a-zA-Z0-9_]+`.
By adding a hyphen there (`[a-zA-Z0-9_-]+`), it will output a correct table name in the join statement.
But I'm not sure how many else places need to be updated, and I'm also unsure if this would bring any side effects. Otherwise I could already make a pull request.

**Comment by chasedig** [comment]
I remember having this issue a while back. I hope this bug gets fixed, but I solved it by just using underscores.

**Comment by assbach** [comment]
Oh thank you, this had me digging for errors for hours now. I hate using underscores but it works now... this issue is still present as of today (2020-01-22, v 1.7.8)

**Comment by assbach** [comment]
just realized it's not only table-names but also column-names with "-" that cause problems.
