### ISSUE TITLE
Hey still me, about debug ()-> select () bug call boolean member function fetchAll ()

### ISSUE THREAD

**Issue by hyyyp** [catfan/Medoo#886]
<img width="815" alt="QQ20191217-140137@2x" src="https://user-images.githubusercontent.com/6407577/70969015-cc8ae900-20d5-11ea-83a6-7f624690f0c7.png">
<img width="1163" alt="QQ20191217-140153@2x" src="https://user-images.githubusercontent.com/6407577/70969016-cd237f80-20d5-11ea-8ad8-fe851cb9754f.png">

**Comment by catfan** [comment]
OK. Thanks for feedback and it fixed on 3539f02.

However, please just post the code and message directly instead of posting image next time.
