### ISSUE TITLE
cannot get prefix from the object to use in query function

### ISSUE THREAD

**Issue by SnirSofer** [catfan/Medoo#887]
im trying to get the prefix name from the object, but the object are protected, so i cannot do it.
i need it to run custom query, i need something like that:

$db -> query('TRUNCATE '.$db -> prefix.'sessions');
any solution?

**Comment by catfan** [comment]
You can use quotation syntax `<table.column>` for the query, and Medoo will handle the prefix and quotation automatically.

https://medoo.in/api/query

**Comment by SnirSofer** [comment]
> You can use quotation syntax `<table.column>` for the query, and Medoo will handle the prefix and quotation automatically.
> 
> https://medoo.in/api/query

but its truncate..
so i need to do something like this?

$db -> query('TRUNCATE <sessions>');
