### ISSUE TITLE
Question about 'date'-Fields?

### ISSUE THREAD

**Issue by omexlu** [catfan/Medoo#889]
Good evening,

I have a problem with the following query, I only want to change data sets that are not today.

This works (dateLastSubstract[<]):

> // execute action
>           $updatePharmacyCapacityCronjob = $db->update('pharmacy', [
>                                                                     "capacity[-]" => $getPharmacyDataCapacityCronjob['dosageTotal'],
>                                                                     "dateLastSubstract" => date("Y-m-d H:i:S")
>                                                                    ], [
>                                                                      "dateLastSubstract[<]" => Medoo::raw("DATE(CURDATE())")
>                                                                    ]);

That doesn't work (dateLastSubstract[!]:

> // execute action
>           $updatePharmacyCapacityCronjob = $db->update('pharmacy', [
>                                                                     "capacity[-]" => $getPharmacyDataCapacityCronjob['dosageTotal'],
>                                                                     "dateLastSubstract" => date("Y-m-d H:i:S")
>                                                                    ], [
>                                                                      "dateLastSubstract[!]" => Medoo::raw("DATE(CURDATE())")
>                                                                    ]);

Maybe you can give me some advice how I could solve this better or if there might even be a bug in the library:

Thanks in advance.

**Comment by catfan** [comment]
Maybe you can use 
```php
'dateLastSubstract[><]' => [date('Y-m-d', strtotime('-1 day')), date('Y-m-d', strtotime('+1 day'))]
// WHERE (`dateLastSubstract` NOT BETWEEN '2020-01-08' AND '2020-01-10')
```
Or
```php
[
    "dateLastSubstract[>]" => Medoo::raw("DATE(CURDATE())"),
    "dateLastSubstract[<]" => Medoo::raw("DATE(CURDATE())")
]
```

**Comment by omexlu** [comment]
Thanks, I have solved the problem as follows:
```
$updatePharmacyCapacityCronjob = $db->update('pharmacy', [
                                                                   "capacity[-]" => $getPharmacyDataCapacityCronjob['dosageTotal'],
                                                                   "dateLastSubstract" => date("Y-m-d H:i:s")
                                                                   ], [
                                                                       "AND" => [
                                                                                "dateLastSubstract[<]" => Medoo::raw("DATE(CURDATE())"),
                                                                                "id" => $getPharmacyDataCapacityCronjob['id']
                                                                                ]
                                                                   ]);
```
