### ISSUE TITLE
BUG on show $db->last();  wrong semicolon

### ISSUE THREAD

**Issue by deawx** [catfan/Medoo#890]
myquery

`$findpoi = $db->select("website","*",[
    "vl_id"=>$_POST['vlid']
]);
echo $db->last();
`

this show wrong point semicolon
SELECT * FROM `website` WHERE `vl_id` = '1;'

**Comment by catfan** [comment]
You may check out the value of `$_POST['vlid']`.

Is it `1;` or `1`?
