### ISSUE TITLE
where RAW

### ISSUE THREAD

**Issue by Sgenmi** [catfan/Medoo#891]
$where=[
    1=>\Medoo\Medoo::raw('MOD(<id>,2)')
]
Version: 1.7.8
line: 643
code:
is_int($key) && 

**is_int($key) &&  !is_object($value) &&**

**Comment by catfan** [comment]
Would you provide more detailed information what the problem is?

If you just using raw object as where parameter, there is no need to put it into array.

```php
$data = $database->select('account', [
    'user_id',
    'email'
], Medoo::raw('WHERE LENGTH(<user_name>) > 5')
);
```
