### ISSUE TITLE
Medoo::buildRaw preg_replace_callback invalid regexp

### ISSUE THREAD

**Issue by dmachehin** [catfan/Medoo#892]
`Medoo::buildRaw` has bad regexp `/((FROM|TABLE|INTO|UPDATE)\s*)?\<([a-zA-Z0-9_\.]+)\>/i`

For example query
```sql
INSERT INTO test ('TEXT FROM <.> TEXT')
```
Generate error `Incorrect column name "." in file /vendor/catfan/medoo/src/Medoo.php at line 521 `

Why do this change? (where is using this table name syntax `<table_name>`?)

Suggests fixed:
 1. Delete this replace
 2. Make this preg_replace optional
 3. Fix regexp in column name capture (for example `([a-zA-Z0-9_\.]+)` replace to `([a-z][a-zA-Z0-9_\.]*)`) ..... 
But bug is still exists after fix (partial fixed only)
 4. Fix regexp by add first `^[a-z\s]*`
Replace to: `/^[a-z\s]*((FROM|TABLE|INTO|UPDATE)\s*)?\<([a-zA-Z0-9_\.]+)\>/i`

**Comment by catfan** [comment]
Thanks. I fixed this on e03bc3d.

It will not match if the quotation syntax is inside ``abc <column> abc`` or `"abc <column> abc"`.

And it also not match `<.>`.

However, it should use placeholder for data in query sentence instead of quoting data by hand.

**Comment by BrainStormDevel** [comment]
Hello, this fix broken MariaDB compatibility.
I have update composer but still use my repo, because this fix broken my code. This is my query to test the issue:

$db->query("SELECT <table1.id>, table22.a_table2 FROM <table1>
		LEFT JOIN (
			SELECT CONCAT('[', GROUP_CONCAT(JSON_OBJECT('lid', <table2.lid>) ORDER BY <table2.id>, <table2.lid>),']') as a_table2, <table2.id>, <table2.lid>
			FROM <table2>
			WHERE <table2.pid> = 1
			GROUP BY <table2.id>
		  ) table22 ON <table1.id> = table22.id")->fetchAll();

**Comment by catfan** [comment]
@BrainStormDevel Change your single quote to double quote for

```SQL
SELECT CONCAT("[", GROUP_CONCAT(JSON_OBJECT("lid", <table2.lid>) ORDER BY <table2.id>, <table2.lid>),"]")
```

I will test more for the regex for complex case. But this may fix your case from now.

**Comment by omexlu** [comment]
Hello,

I also have a problem with the RAW function in the current version:
https://github.com/catfan/Medoo/issues/912

Can anyone here help me? Looks like a bug.
