### ISSUE TITLE
Method buildRaw doesn't eval <> tag on JOIN

### ISSUE THREAD

**Issue by BrainStormDevel** [catfan/Medoo#894]
Already fixed on my repo, just change this on line 447:

$query = preg_replace_callback(
			'/((FROM|TABLE|INTO|UPDATE)\s*)?\<([a-zA-Z0-9_\.]+)\>/i',

With:

$query = preg_replace_callback(
			'/((FROM|JOIN|TABLE|INTO|UPDATE)\s*)?\<([a-zA-Z0-9_\.]+)\>/i',

Example Query:

$db->query("SELECT * FROM <table_1> LEFT JOIN <table_2 > ON <table_1.id> = <table_2.id>")->fetchAll();

**Comment by catfan** [comment]
Thanks, this fixed on 3abdbb8.
