### ISSUE TITLE
How to add schema parameters on PostgreSQL

### ISSUE THREAD

**Issue by DuanWen** [catfan/Medoo#899]
楼主您好，请问new Medoo()的时候， postgresql 如何添加“模式”参数？我阅读了源码，好像是没有类似“模式”的参数

--------------Translated by Google
Hello, how do you add "mode" parameters to PostgreSQL during new Medoo ()? I read the source code and it seems that there are no parameters like "mode".

**Comment by DuanWen** [comment]
@catfan 请教一下，希望有时间能指点一下，多谢

**Comment by catfan** [comment]
You can execute command to set schema on initialization.

https://medoo.in/api/new

```php
$database = new Medoo([
	'database_type' => 'postgrsql',
	'database_name' => 'name',
	'server' => 'localhost',
	'username' => 'your_username',
	'password' => 'your_password',

	'command' => [
		'SET search_path TO account_schema'
	]
])
```
