### ISSUE TITLE
$database->id() returns NULL

### ISSUE THREAD

**Issue by Dibbyo456** [catfan/Medoo#902]
**Describe the bug**

`$database->id()` returns `NULL` even after a successful `insert()`

**Information**
- Version of Medoo: **1.7.10**
- Type of Database: **MariaDB**
- System: **Windows 10 (64 bit)**

**Detail Code**

```php
$database = new Medoo\Medoo([
    'database_type' => 'mysql',
    'database_name' => 'dbname',
    'server'        => 'localhost',
    'username'      => 'root',
    'password'      => ''
]);

$query = $database->insert('table_copy', [
    'id'           => 59093903,
    'api_response' => serialize(str_repeat('test', 5))
]);

// Here the lastInsertId() returns NULL which is incorrect.
var_dump($database->id());

// returns "0" (string) which is also incorrect.
var_dump($database->pdo->lastInsertId());

// However rowCount() returns 1 (int) which is correct.
var_dump($query->rowCount());
```

**Comment by catfan** [comment]
The `id()` or `lastInsertId()` from PDO, is for returning the auto-increase id last inserted. The id of non-key or not auto-increase column will not be return.

You may need to know how database engine works.
