### ISSUE TITLE
How to manually open and close a connection?

### ISSUE THREAD

**Issue by jenokizm** [catfan/Medoo#904]
For example, I want to write a delay function before some bot answers to a user, but at the same time so as not to block an unnecessary connection.

```
use Medoo\Medoo;

$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => 'testdb',
    'server' => 'localhost',
    'username' => 'root',
    'password' => ''
]);

function sleepMy()
{
    $database->close();
    sleep(3);
    $database->reopen();
}
```
how to do it?

**Comment by mrqaidi** [comment]
i need this too  i need to close mysql when i have long  php execute

**Comment by LikeNeko** [comment]
> 我也需要这个，当我长时间执行php时，我需要关闭mysql

$database->pdo=null;

**Comment by catfan** [comment]
Destructing the `$database->pdo` or the Medoo object is the right way to close the connection.
