### ISSUE TITLE
Adjust over 'group by array' for functions as MONTH(), DAY(), etc

### ISSUE THREAD

**Issue by Oscarato** [catfan/Medoo#907]
**Describe the bug**
In array group, medoo show the next error: "Object of class Medoo\\Raw could not be converted to string"
        $filter['GROUP']    =  [
            Medoo::raw('MONTH(d.start)')
        ];

I fixed on file Medoo.php on line 878:

foreach ($GROUP as $column => $value)
{
    if ($raw = $this->buildRaw($value, $map))
    {
        $stack[] = $raw;
    }else{
        $stack[] = $this->columnQuote($value);
    }
}

I don't have write permissions

**Information**
- Version of Medoo: 1.7
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx\Windows\Mac):Windows\Linux

**Detail Code**
        $filter['GROUP']    =  [
            Medoo::raw('MONTH(d.start)')
        ];

**Expected output**
Data array

**Comment by catfan** [comment]
Just use with raw object directly.
```php
$where['GROUP'] => Medoo::raw('MONTH(d.start)')
```
