### ISSUE TITLE
There is a problem. I don't know what caused it.

### ISSUE THREAD

**Issue by dyl8023** [catfan/Medoo#908]
There are some errors, prompt the following information, please tell me how to solve it?

`
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [14] unable to open database file in /www/wwwroot/api.muxiaoguo.cn/public/sqlite/Medoo-1.6/Medoo.php:321 Stack trace: #0 /www/wwwroot/api.muxiaoguo.cn/view/api/mail/index.php(29): Medoo\Medoo->__construct(Array) #1 /www/wwwroot/api.muxiaoguo.cn/view/api/mail/index.php(8): infoAction() #2 /www/wwwroot/api.muxiaoguo.cn/app/Http/Controller/IndexController.php(109): require('/www/wwwroot/ap...') #3 /www/wwwroot/api.muxiaoguo.cn/app/Core/route/Route.php(201): indexController->api() #4 /www/wwwroot/api.muxiaoguo.cn/app/Core/route/Route.php(159): Route::impController('IndexController...') #5 /www/wwwroot/api.muxiaoguo.cn/app/Core/route/Route.php(65): Route::ifimp('/api/{apiVal}', 'IndexController...', NULL) #6 /www/wwwroot/api.muxiaoguo.cn/app/Core/route/Route.php(30): Route::get('/api/{apiVal}', 'IndexController...', NULL) #7 /www/wwwroot/api.muxiaoguo.cn/route/web.php(19): Route::any('/api/{apiVal}', 'IndexController...') #8 /www/wwwroot/api.muxiaoguo.cn/app/init.php(24): req in /www/wwwroot/api.muxiaoguo.cn/public/sqlite/Medoo-1.6/Medoo.php on line 321`

**Comment by catfan** [comment]
The message is telling you that `unable to open database file in xxx`. That's mean your configuration for `new Medoo()` is with error.

**Comment by dyl8023** [comment]
> The message is telling you that `unable to open database file in xxx`. That's mean your configuration for `new Medoo()` is with error.

Thank you. I've taken care of it.
