### ISSUE TITLE
get() return the first row of the result,error find in mssql and oracle

### ISSUE THREAD

**Issue by inspurhua** [catfan/Medoo#91]
we use "select top 1 xxxx from yyy" at mssql and sybase,but medoo default use limit 1;
we use "select xxx from yyy where rownum=1",but medoo default use limit 1;

**Comment by superdeeid** [comment]
I confirm this error when using ONLY medoo msSQL settings using v1.4.5.

For now, i use directly the query() method since meddo doesnt parse the correct query when used with MsSQL.

**Comment by njxqlus** [comment]
Same in Oracle. `LIMIT 1`  was added to simple select sql: 
```
get('USER_TABLE', ['USER_SETTINGS'], [
    'USER_LOGIN' => $userID,
]);
```
