### ISSUE TITLE
Problem with RAW in actual Version

### ISSUE THREAD

**Issue by omexlu** [catfan/Medoo#912]
Hello,

Today I wanted to make an update to the latest version, the following code has always worked, but now it doesn't work anymore:
`$getEntrys = $db->select($tableName, "*", Medoo::raw("WHERE <weekday> = '1' AND <status> = '1' ORDER BY <sequence> ASC"));`

I think this is due to the following change:
https://github.com/catfan/Medoo/compare/v1.7.9...master

What can I do here?

Thanks in advance.

**Comment by omexlu** [comment]
Debug showing this 
SELECT * FROM `weightsTracker` WHERE `weekday` = '1' AND = '1' ORDER BY `sequence` ASC

Second <status> is missing, don't know why.
Maybe a Bug.

**Comment by omexlu** [comment]
Hello,

I also have a problem with the RAW function in the current version:
https://github.com/catfan/Medoo/issues/912

Can anyone here help me? Looks like a bug.

**Comment by catfan** [comment]
If you need to set value for the raw string, use placeholder for prepared statement. Don't set it with hand-write quotation.

```php
$database->debug()->select(
    "weightsTracker",
    "*",
    Medoo::raw("WHERE <weekday> = :weekday AND <status> = :status ORDER BY <sequence> ASC", [
        ":weekday" => 1,
        ":status" => 1
    ])
);

// SELECT * FROM `weightsTracker` WHERE `weekday` = 1 AND `status` = 1 ORDER BY `sequence` ASC
```

Additionally, this query can be built by pure Medoo's where syntax. No need to use raw object.

**Comment by omexlu** [comment]
Hello,

In my case i need to use the raw-methode, but this code worked in v1.7.6:
`$getEntrys = $db->select($tableName, "*", Medoo::raw("WHERE <weekday> = '1' AND <status> = '1' ORDER BY <sequence> ASC"));`

If i do the same code in the actual version the second '< status >' don't appear in the query i get this on debug:
`SELECT * FROM weightsTrackerWHEREweekday= '1' AND = '1' ORDER BYsequence ASC`

I do not understand why this status-field disappear in the query.

And also '1' is not only a number, there can be strings on it, because of that i need the single-quotes.

**Comment by catfan** [comment]
@omexlu Don't use this way, that's not correctly in fact, and it fixed on latest version.

If you want to be a string value for the placeholder, just assign it as string.
```php
$database->debug()->select(
    "weightsTracker",
    "*",
    Medoo::raw("WHERE <weekday> = :weekday AND <status> = :status ORDER BY <sequence> ASC", [
        ":weekday" => "1",
        ":status" => "1"
    ])
);
```

**Comment by omexlu** [comment]
@catfan

Thanks for your help.

I use it in a function:
`function getEntrys($tableName, $additionalStatement)
  {
      global $db;

      if ($additionalStatement == '0') {
          $getEntrys = $db->select($tableName, "*");
      } else {
          $getEntrys = $db->select($tableName, "*", Medoo::raw($additionalStatement));
      }

      return $getEntrys;
  }`

`getEntrys('weightsTracker', "WHERE <weekday> = '" . $getDataForCurrentDate[0] . "' AND <status> = '1' ORDER BY <sequence> ASC")`

I'm not sure how I'm gonna make this work with your example above.

In the old version it worked without problems.

**Comment by catfan** [comment]
Just use the WHERE syntax as possible. https://medoo.in/api/where

This is the main feature of Medoo.

**Comment by omexlu** [comment]
I already looked at it, but I need a loop of the whole table and the WHERE should also be dynamic so I can call it in the function.

Worked great in the old version, the only problem now is that 'status' somehow disappears (see above), don't know why.

If I quote < status > by hand 'status' in the query it works again.

**Comment by catfan** [comment]
I told that don't use it like this way. It's **incorrect** and has a bug. This is what it fixed on latest version.

**Comment by omexlu** [comment]
hm okay I understand, but I'm not that skilled in programming and I just started.

Could you maybe help me how to use this in a function where I can enter the parameters dynamically?

Function:
` function getEntrys($tableName, $additionalStatement)
{
global $db;

  if ($additionalStatement == '0') {
      $getEntrys = $db->select($tableName, "*");
  } else {
      $getEntrys = $db->select($tableName, "*", Medoo::raw($additionalStatement));
  }

  return $getEntrys;
} `

Call somehow like that:
`getEntrys('weightsTracker', "WHERE <weekday> = :param1 AND <status> = :param2 ORDER BY <sequence> ASC")`

Now I only have to get the param dynamically into the function if there is only one param, two, 3 or 4.

What is the best way to do this, if the problem is solved it will work :)

Thanks for your help, I am a noob :D

**Comment by catfan** [comment]
I'm not sure what this function want.

It's easy to add parameter dynamically with WHERE syntax just like using the array in PHP.

```php
$where = [
        "weekday" => "1",
        "ORDER" => ["sequence" => "ASC"]
];

if ($shouldCheckStatus == true) {
        $where["status"] = "1";
}

$database->select("table", "*", $where);
```

I don't know why you still keep using raw object like this. It's advanced feature and should use it for special proposal.

I told you the correct raw string syntax with placeholder. The thing you need to think is how to build the correct raw string and call with placeholder's value. This is the basic PHP knowledge you should learn by yourself. I can't teach it here.
