### ISSUE TITLE
[Having => [count(tbl2.id) => 0]] is converted in 'having count = 0'

### ISSUE THREAD

**Issue by Fluit** [catfan/Medoo#916]
**Describe the bug**
When i use 
`['HAVING' => [count(tbl2.id) = 0]` 
and where tbl2 is a joined table with a table tbl1, then is this is converted in the PDO-select statement as "HAVING count = 0" in stead of "HAVING count(tbl2.id) = 0" like I'm suspecting.

**Information**
- Version of Medoo: 1.7.10
- Type of Database (MySQL, MSSQL, SQLite...): mySQL
- System (Liunx\Windows\Mac): Windows 10

**Detail Code**
```
$join = '[>]tbl2';
$where = [
            'AND' => $condition,
            'ORDER' => [
                $sort => $order
            ],
            'LIMIT' => [$offset, $rows],
            'GROUP' => ['tbl1.id'],
            'HAVING' => [count(tbl2.id) => 0]
        ];

$result['rows'] = $this->Db->select('tbl1', $join, $columns, $where);
```

sql-string output:
```
SELECT tbl1.id, tbl1.col2,  count(tbl2.id) AS count
FROM tbl1 LEFT JOIN tbl2 ON tbl1.tbl2_id = tbl2.id 
GROUP BY tbl1.id 
HAVING count = 0
ORDER BY tbl1.id ASC
```

**Expected output**
```
SELECT tbl1.id, tbl1.col2 count(tbl2.id) AS count
FROM tbl1 LEFT JOIN tbl2 ON tbl1.tbl2_id = tbl2.id 
GROUP BY tbl1.id
HAVING count(tbl2.id) = 0 
ORDER BY tbl1.id ASC
```

**Comment by catfan** [comment]
If you want to use SQL built-in function, you need to use raw object.

```php
"HAVING" => Medoo::raw("COUNT(tbl2.id) = 0")
```
