### ISSUE TITLE
Encoding error when returning json with Chinese text

### ISSUE THREAD

**Issue by shadowfish07** [catfan/Medoo#917]
**Describe the bug**
When I use `select` to get json with Chinese text from my database,it has some encoding error so that the result is hard to use,just like this:
```
{"rcode":"00000","id":"1","title":"shadow\u7684\u5546\u5e97","value":"{\"gold\": 200, \"title\": \"\u793a\u4f8b\u5546\u54c1\", \"descripsion\": \"\u8fd9\u662f\u4e00\u4e2a\u793a\u4f8b\u5546\u54c1\"}","creater":"1","reg_time":null}
```
The unicode character in the title field is usually converted automatically, but the `/"` is a big problem!
Then I tried to use `mysqli` to get the same text and it returns exactly the right result,which has no unicode chars at all.

**Information**
- Version of Medoo:1.7.10
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx\Windows\Mac):Windows

**Detail Code**
```
    $data = $db->select('shop_series', '*', [
        'id' => $shopid
    ])[0];
echo json_encode($result);
```

**Expected output**
```
{
    "rcode": "00000",
    "id": "1",
    "title": "shadow的商店",
    "value": "{"gold": 200, "title": "示例商品", "descripsion": "这是一个示例商品"}",
    "creater": "1",
    "reg_time": null
}

```

**Comment by praine** [comment]
This is not a medoo issue, it's a JSON_ENCODE issue. You need to use the JSON_UNESCAPED_UNICODE flag in your json_encode statement.

More info here: https://www.php.net/manual/en/json.constants.php
