### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by osmelgarejo** [catfan/Medoo#919]
Hola, como puedo controlar el timeout de mi conexion a sql server?

$db = new Medoo([
    
    'database_type' => 'mysql',
    'database_name' => 'portal',
    'server' => '192.168.10.4',
    'username' => 'desarrollador',
    'password' => '12345'
   
        ]);

Encontré esta funcion pero nosé como adaptar a mi cadena de conexión.

PDO::ATTR_TIMEOUT => 5

**Comment by catfan** [comment]
Just set it on `option` for the connection. https://medoo.in/api/new

```php
$database = new Medoo([

	'database_type' => 'mysql',
	'database_name' => 'name',
	// ....

	'option' => [
		PDO::ATTR_TIMEOUT => 5
	]
]);
```

**Comment by osmelgarejo** [comment]
> Solo configúralo `option`para la conexión. https://medoo.in/api/new
> 
> ```
> $ database = new  Medoo ([ 'database_type' => 'mysql' ,
> 	 'database_name' => 'name' ,
> 	 // .... 'option' => [
> 		 PDO :: ATTR_TIMEOUT => 5 
> 	]
> ]);
> 
> 	
> 
> 	
> ```

Gracias
