### ISSUE TITLE
CONCAT cannot connect English characters

### ISSUE THREAD

**Issue by youngda** [catfan/Medoo#920]
$database->select('table', [
        'create_time'=>Medoo::raw('CONCAT(123456,<key>)')
    ], []

The above can work。result: 123456key_result.

$database->select('table', [
        'create_time'=>Medoo::raw('CONCAT(abcdef,<key>)')
    ], []

English characters are not working

**Comment by catfan** [comment]
CONCAT() need to quote the string.

```php
CONCAT("abcdef", "foo")
```
