### ISSUE TITLE
Creating an SQLite DB with password, How do I password protect SQLite database using Medoo?

### ISSUE THREAD

**Issue by blessedjasonmwanza** [catfan/Medoo#921]
Currently I cannot seem to find a way of how one can create an SQLite DB having its data encrypted with a password. Is there a work around this? And if not, is it possible that it can be implemented?
@catfan

**Comment by catfan** [comment]
Medoo connection is based on PDO, and there is no official support SQLite connection with password.

https://www.php.net/manual/en/ref.pdo-sqlite.connection.php

SQLite is design for simple database operation. If you want a secure and encrypted database, MySQL or other advanced database will be the better choice.
