### ISSUE TITLE
Nombre de campo con espacio

### ISSUE THREAD

**Issue by osmelgarejo** [catfan/Medoo#924]
Estoy tratando de insertar datos utilizando campos con espacios pero no me permite insertar, alguna idea?

tabla de la base de datos con los campos con espacios:
![image](https://user-images.githubusercontent.com/46031708/91589218-5eb2e480-e927-11ea-9588-0dbf3fbbc9c7.png)

mi codigo php:
![image](https://user-images.githubusercontent.com/46031708/91589491-c79a5c80-e927-11ea-8b83-f4eb398de68b.png)

el error que me da: 
![image](https://user-images.githubusercontent.com/46031708/91589764-4c857600-e928-11ea-9fc8-261f696c61cb.png)

**Comment by catfan** [comment]
The column name character should be with `A-Z a-z`, `0-9` and underscore `_` only.

**Comment by osmelgarejo** [comment]
El problema es que no se pueden cambiar las estructuras de los campos y tablas de la base de datos :(
