### ISSUE TITLE
Allow ['column' => [value, NULL]] as short syntax for column = value OR column IS NULL

### ISSUE THREAD

**Issue by levu42** [catfan/Medoo#927]
I have to check for a column being either a specific value or NULL. The current way to do it I found is:

> ['OR' => ['AND #1' => ['column' => 42], 'AND #2' => ['column' => null]]]

But it would be so much nicer to just write

> ['column' => [42, null]]

This code currently gives you

> column IN (42, null)

which at least in MariaDB doesn't work. My suggestion is to change the IN() generation code in a way that the SQL generated becomes

> column IN (42) OR column IS NULL

**Comment by catfan** [comment]
This will be confusing.

Think about:
- If the first condition is not a value but array. `["column" => [42, 43, 44, 45....]]`
- If we want the NOT null condition `["column[!]" => null]`

It's no need to combine, and will be conflict for the general usage. `["column" => [value1, value2...]]`
