### ISSUE TITLE
The documentation about using LIMIT in MSSQL or Oracle is incorrect

### ISSUE THREAD

**Issue by littlephone** [catfan/Medoo#929]
The documentation states that LIMIT clause should be used with GROUP BY. But after I studied the source code,  ORDER BY should be used instead 

**Information**
- Version of Medoo: 1.7
- Type of Database (MySQL, MSSQL, SQLite...): MSSQL
- System (Liunx\Windows\Mac):  

**Detail Code**
`// For Oracle and MSSQL database, you also need to use with GROUP by together ` 
`'GROUP' => 'location' `

**Expected output**
`// For Oracle and MSSQL database, you also need to use with ORDER by together ` 
`'ORDER' => 'location' `

**Comment by catfan** [comment]
It's doc error.

We also improved this without using ORDER BY for MSSQL dae9fa22cbc38f3d6e3344582226ca2f9f3fa14d.
