### ISSUE TITLE
unbuffered query

### ISSUE THREAD

**Issue by targor** [catfan/Medoo#932]
Since i could not find anything in the documentation, i now try to open an issue...

My question is, how can i create a unbuffered query? because i want to load a large blob file from the database, but i always get memory allocation issues.

I there the possibility to do this or do i neet to use the raw functions?

**Comment by catfan** [comment]
You can try the (https://medoo.in/api/select) Traverse Fetch With Callback that v2.0 added.

Also, you need to check the memory setting for your PHP and Nginx.
