### ISSUE TITLE
[fix] Warning:  preg_match(): Compilation failed: unmatched closing parenthesis at offset 58

### ISSUE THREAD

**Issue by yanalexandrov1987** [catfan/Medoo#933]
Hi, I call the **select** method.

```
$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => 'name',
    'server' => 'localhost',
    'username' => 'your_username',
    'password' => 'your_password'
]);
$data = $database->select( 'commentmeta', '*' );
```

The error occurs in the line with **preg_match**.

```
protected function selectContext( $table, &$map, $join, &$columns = null, $where = null, $column_fn = null ) {
 preg_match( '/( ?<table>[a-zA-Z0-9_]+ )\s*\( ( ?<alias>[a-zA-Z0-9_]+ )\ )/i', $table, $table_match );
```

$table param have string `commentmeta`

And an error appears Warning: preg_match(): Compilation failed: unmatched closing parenthesis at offset 58
Tell me what the problem is. and how to solve it?

**Comment by catfan** [comment]
Did you change the code format of source code?

**Comment by yanalexandrov1987** [comment]
> Did you change the code format of source code?

I'm sorry, I didn't understand you.

**Comment by catfan** [comment]
We tested it and there is no problem for using `$database->select("table", "*");`.

But I found the code you post above is not the same as source code.
https://github.com/catfan/Medoo/blob/2d675f73e23f63bbaeb9a8aa33318659a3d3c32f/src/Medoo.php#L993

It seem your Medoo code has changed. Why there is a blank space from the regex? And that absolutely not work with error.
