### ISSUE TITLE
Is it possible to get an associative array?

### ISSUE THREAD

**Issue by yanalexandrov1987** [catfan/Medoo#936]
Hello, I have table like this:

`ID | name   | value
-------------------
1  | First      | Last
2  | Second | Next`

Can I get data like this?
`Array
(
    [First] =>Last
    [Second] => Next
)`

I use `$db->select( $this->table,  [ "name" => [ "value" ] ] );` but output:

` Array
(
    [First] => Array
        (
            [value] => Last
        )
    [Second] => Array
        (
            [value] => Next
        )
)`

**Comment by superdeeid** [comment]
Yes you can... With version 1.7.10.
look at 'Index Mapping' in the doc -> [https://medoo.in/api/select](select)
