### ISSUE TITLE
join alias table is wrong 

### ISSUE THREAD

**Issue by deawx** [catfan/Medoo#942]
Medoo Version 1.7.10
This my code
`$r = $db->select("item(a)", [
            "[>]customer(b)" => ["customer_id" => "id"]
        ], [
            "a.id",
            "b.company_name"
        ], [
            "a.id" => 437565
        ]);`
i debug is show
`SELECT `a`.`id`,`b`.`company_name` FROM `item` AS `a` LEFT JOIN `customer` AS `b` ON `**item**`.`customer_id` = `b`.`id` WHERE `a`.`id` = 437565`
 
i think Should be is 
`ON `**a**`.`customer_id` = `b`.`id``

Thank you catfan

**Comment by catfan** [comment]
This has been fixed on cac5738.
