### ISSUE TITLE
HAVING + GROUP BY

### ISSUE THREAD

**Issue by NazgulTuga** [catfan/Medoo#944]
When you create a SELECT with the "where" parameters with "HAVING" and "GROUP" the class outputs
GROUP BY field_name HAVING field_name>0 HAVING field_name>0

Function: **whereClause**
CHANGE THIS LINE: if (isset($where[ 'HAVING' ]))
CHANGE TO THIS: 

	**if (!isset($where[ 'GROUP' ]) && isset($where[ 'HAVING' ]))**
	{
		if ($raw = $this->buildRaw($where[ 'HAVING' ], $map))
		{
			$where_clause .= ' HAVING ' . $raw;
		}
		else
		{
			$where_clause .= ' HAVING ' . $this->dataImplode($where[ 'HAVING' ], $map, ' AND');
		}
	}

**Comment by catfan** [comment]
How do you output two `HAVING`?

The `if (isset($where[ 'HAVING' ]))` is inside `if (isset($where['GROUP']))`. It will be only executed once.

**Comment by kakenbok** [comment]
I also would like to have a having clause without specifying group by.
