### ISSUE TITLE
ORDER doesnt work

### ISSUE THREAD

**Issue by Aldione** [catfan/Medoo#947]
Hi,

im trying to use order by, i want to use this select:

Select * from tarea where cod_tarea = $row order by estado;

```
$tarea_data = $database->select("tarea","*",['cod_tarea' => $row], ["order" => "estado"]);
$tarea_data = $database->select("tarea","*",['cod_tarea' => $row, "order" => "estado"]);
```
doesnt work

**Comment by catfan** [comment]
The keyword `order` should be upper case.

```php
$tarea_data = $database->select("tarea","*",[
    "cod_tarea" => $row,
    "ORDER" => "estado"
]);
```

**Comment by Aldione** [comment]
i didnt with ORDER but doesnt work :/

estado is a ENUM, but i try with another column and doesnt work anyway :/

**Comment by catfan** [comment]
@Aldione What's your output `$database->debug()->select("tarea"....`?
