### ISSUE TITLE
Fatal error: Uncaught Error: Cannot unset string offsets in vendor/catfan/medoo/src/Medoo.php:1599 Stack trace: #0 [internal function]: Medoo\Medoo->get('article', Array, 'where domain='c...') #1

### ISSUE THREAD

**Issue by juejixiaohaipi** [catfan/Medoo#950]
if ($where === null)
		{
			$column = $join;
			unset($columns[ 'LIMIT' ]);

**Comment by catfan** [comment]
Would you please provide more information about the issue?

What's the code you are calling?

It seems you are providing a string as the 3rd parameter.

**Comment by catfan** [comment]
This issue is closed due to no response.
