### ISSUE TITLE
InvalidArgumentException: Incorrect table name "information_schema.tables"

### ISSUE THREAD

**Issue by dydx-git** [catfan/Medoo#951]
**Describe the bug**
Calling methods with 'information_schema.tables' as the table name gives the following error:
> InvalidArgumentException: Incorrect table name "information_schema.tables"

**Information**
- Version of Medoo: v1.7.10
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Windows

**Detail Code**
```
$this->database->debug()->select(
            'information_schema.tables',
            'UPDATE_TIME',
            [
                'TABLE_SCHEMA' => DatabaseConnector::$databaseName,
                'TABLE_NAME' => 'design'
            ]
);
```

**Expected output**
Expected it to translate to this query:
`SELECT UPDATE_TIME 
FROM   information_schema.tables WHERE  
TABLE_SCHEMA = 'your_dbname'   AND TABLE_NAME = 'your_tablename'`

**Comment by catfan** [comment]
You cannot select table from schema directly. Just simply change `information_schema.tables` to `tables` instead.

**Comment by LethalIndustry** [comment]
What happend if my MSSQL DB contains a few schemas like cat.employee, fun.tickets and i have to make joins?

I'm trying this but not korking

$db->select("fun.boletos(b)", [
        "[>]cat.empleados(e)" => ["idempleado" => "id"]
    ], [
        "b.id",
        "e.nombre"
    ],[
        "e.id[<=]" => 20
    ]);
