### ISSUE TITLE
xy[!] => xyz is not working in the way its supposed to

### ISSUE THREAD

**Issue by Siposattila** [catfan/Medoo#952]
**Describe the bug**
The bug is that I cant check whether the action is dislike or not action[!] => "dislike" just simply doesn't work or idk. I even checked for errors there was none.

**Information**
- Version of Medoo: Version 1.7.10
- Type of Database (MySQL)
- System Linux

**Detail Code**
`$rows = $db->select("notif",
"*",
[
  "to" => $email,
  "action[!]" => "dislike",
  "action[!]" => "block"
]);`

**Expected output**
A clear and concise description of what output you expected.
`SELECT * FROM notif WHERE to = "email@email.com" AND action != "dislike" AND action != "block"`

**Comment by catfan** [comment]
If you want to assign value to the same column, you can just simply combine value together with array.

```php
"action[!]" => ["dislike", "block"]
```

**Comment by Siposattila** [comment]
Thank you! I was dumb...
