### ISSUE TITLE
Cannot unset string offsets error from get() with $where as string.

### ISSUE THREAD

**Issue by juejixiaohaipi** [catfan/Medoo#957]
**Describe the bug**

**Information**
- Version of Medoo:
- Type of Database (MySQL, MSSQL, SQLite...):
- System (Liunx\Windows\Mac):

**Detail Code**
The detail code causes the problem.

**Expected output**
A clear and concise description of what output you expected.

**Comment by juejixiaohaipi** [comment]
public function get($table, $join = null, $columns = null, $where = null)
	{
		$map = [];
		$result = [];
		$column_map = [];
		$current_stack = [];

		if ($where === null)
		{
			$column = $join;
			unset($columns[ 'LIMIT' ]);
		}
		else
		{
			$column = $columns;
			unset($where[ 'LIMIT' ]);
		}

		$is_single = (is_string($column) && $column !== '*');

		$query = $this->exec($this->selectContext($table, $map, $join, $columns, $where) . ' LIMIT 1', $map);

		if (!$this->statement)
		{
			return false;
		}

		$data = $query->fetchAll(PDO::FETCH_ASSOC);

		if (isset($data[ 0 ]))
		{
			if ($column === '*')
			{
				return $data[ 0 ];
			}

			$this->columnMap($columns, $column_map, true);

			$this->dataMap($data[ 0 ], $columns, $column_map, $current_stack, true, $result);

			if ($is_single)
			{
				return $result[ 0 ][ $column_map[ $column ][ 0 ] ];
			}

			return $result[ 0 ];
		}
	}
public function get($table, $join = null, $columns = null, $where = null)
	{
		$map = [];
		$result = [];
		$column_map = [];
		$current_stack = [];

		if ($where === null)
		{
			$column = $join;
			unset($columns[ 'LIMIT' ]);
		}
		else
		{
			$column = $columns;
			unset($where[ 'LIMIT' ]);
		}

		$is_single = (is_string($column) && $column !== '*');

		$query = $this->exec($this->selectContext($table, $map, $join, $columns, $where) . ' LIMIT 1', $map);

		if (!$this->statement)
		{
			return false;
		}

		$data = $query->fetchAll(PDO::FETCH_ASSOC);

		if (isset($data[ 0 ]))
		{
			if ($column === '*')
			{
				return $data[ 0 ];
			}

			$this->columnMap($columns, $column_map, true);

			$this->dataMap($data[ 0 ], $columns, $column_map, $current_stack, true, $result);

			if ($is_single)
			{
				return $result[ 0 ][ $column_map[ $column ][ 0 ] ];
			}

			return $result[ 0 ];
		}
	}

**Comment by juejixiaohaipi** [comment]
fot the function get,the row `unset($columns[ 'LIMIT' ]);`may bring error.if there none limit

**Comment by juejixiaohaipi** [comment]
at the row 1599

**Comment by juejixiaohaipi** [comment]
this is my code to use the function get`get("article",['content'],"where domain='js-version' and is_del =0");`

**Comment by catfan** [comment]
The $where parameter should be array not string.

**Comment by juejixiaohaipi** [comment]
ok,thank you.i used the very old version.
