### ISSUE TITLE
Bug: Medoo::raw() Table name not evaluated

### ISSUE THREAD

**Issue by BrainStormDevel** [catfan/Medoo#958]
I have problem when using raw method to select. The <tablename.column1> and <tablename.column2> inside this query are not evaluated as tables.

**Information**
- Version of Medoo: Version: 1.7.10
- Type of Database (MySQL, MSSQL, SQLite...): MariaDB 10.4.18
- System (Liunx\Windows\Mac): Centos 7

**Detail Code**
$db->debug()->select('tablename',
		[
			'test' => Medoo::raw("CONCAT_WS('_',<tablename.column1>, DATE_FORMAT(<tablename.column2>, '%Y-%m-%d'), 'fixedtext')"),
		]);

**Expected output**
SELECT CONCAT_WS('_',`tablename`.`column1`, DATE_FORMAT(`tablename`.`column2`, '%Y-%m-%d'), 'fixedtest') AS `test` FROM `tablename`

**Comment by catfan** [comment]
Fixed it on 73f9220.
