### ISSUE TITLE
Undefined index issue during debugging

### ISSUE THREAD

**Issue by emresudo** [catfan/Medoo#962]
**Describe the bug**
The variables $ options ['database_name'] and $ options ['server'] on lines 215 and 216 in the constructor function give the following error when a connection is made with PDO.
This is nothing more than a minor and annoying situation.

**Information**
- Version of Medoo: 2.0.0
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx\Windows\Mac): Docker OpenLiteSpeed Container in Windows

**Detail Code**
```php
$dsn = new PDO($connectionString, $config['username'], $config['password']);
return new Medoo(
    [
        'pdo' => $dsn,
        'type' => $config['database_type'] // or 'database_type'
    ]
);
```

**Expected output**
Notice:  Undefined index: database_name in /var/www/vhosts/localhost/html/vendor/catfan/medoo/src/Medoo.php on line 215
Notice:  Undefined index: server in /var/www/vhosts/localhost/html/vendor/catfan/medoo/src/Medoo.php on line 216

**Comment by catfan** [comment]
Thanks for the feedback. It fixed on 46fc104.
