### ISSUE TITLE
Setting up Medoo did not work as it should

### ISSUE THREAD

**Issue by DaveMLG** [catfan/Medoo#965]
Hello, so I tried to connect Medoo to my database but it did not work at all. I used the official instructions on the official site, but this part did not work for me

```
$database = new Medoo([
	// [required]
	'type' => 'mysql',
	'host' => 'localhost',
	'database' => 'name',
	'username' => 'your_username',
	'password' => 'your_password',
```

I have been looking for a solution on the internet and have found out that writing it like this worked

```
// Connect the database.
$database = new Medoo([
    'database_type' => 'mysql',
    'database_name' => 'name',
    'server' => 'localhost',
    'username' => 'your_username',
    'password' => 'your_password'

]);
```

**Comment by catfan** [comment]
What version are you using? This is the new setting for v2.0.

https://medoo.in/api/whatsnew

**Comment by catfan** [comment]
@DaveMLG Is your problem resolved?
