### ISSUE TITLE
Using raw object within BETWEEN

### ISSUE THREAD

**Issue by xiasha11** [catfan/Medoo#967]
**Describe the bug**

**Information**
- Version of Medoo:1.7.10
- Type of Database (MySQL, MSSQL, SQLite...):oracle11g
- System (Liunx\Windows\Mac):linux

**Detail Code**
$today = "2021/05/19";
$database->get('reporttata_user', '*',
[
	'date[<>]' => [$database::raw('to_date(:today, \'YYYY-MM-DD\')', [':today' => $today]),$database::raw('to_date(:today, \'YYYY-MM-DD\')', [':today' => $today])]
	]
);

**Expected output**
Array to string conversion in Medoo.php on line 372

**Comment by catfan** [comment]
If you need to use the raw query, just assign it as a raw object alone.

https://medoo.in/api/select

```php
'date[<>]' => Medoo::raw("ON to_date(:today, 'YYYY-MM-DD')", [':today' => $today])
```

**Comment by xiasha11** [comment]
> 如果需要使用原始查询，只需将其单独分配为原始对象即可。
> 
> https://medoo.in/api/select
> 
> ```
> 'date [<>]' => Medoo ::原始（“ ON to_date（：today，'YYYY-MM-DD'）”，[ '：today' => $今天]）
> ```

but between need two days

**Comment by catfan** [comment]
Just use the raw object with two parameters.

```php
'date' => Medoo::raw("BETWEEN to_date(:today1, 'YYYY-MM-DD') AND to_date(:today2, 'YYYY-MM-DD')",  [
    ':today1' => $today1,
    ':today2' => $today2
])
```

**Comment by xiasha11** [comment]
> Just use the raw object with two parameters.
> 
> ```
> 'date' => Medoo::raw("BETWEEN to_date(:today1, 'YYYY-MM-DD') AND to_date(:today2, 'YYYY-MM-DD')",  [
>     ':today1' => $today1,
>     ':today2' => $today2
> ])
> ```

但这样的话所有的sql 条件只能写在Medoo::raw里面了，不友好，后期拼接也麻烦

**Comment by xiasha11** [comment]
谢谢

**Comment by xiasha11** [comment]
> Just use the raw object with two parameters.
> 
> ```
> 'date' => Medoo::raw("BETWEEN to_date(:today1, 'YYYY-MM-DD') AND to_date(:today2, 'YYYY-MM-DD')",  [
>     ':today1' => $today1,
>     ':today2' => $today2
> ])
> ```

**Comment by xiasha11** [comment]
> 只需使用带有两个参数的原始对象即可。
> 
> ```
> 'date' => Medoo ::原始（“ BETWEEN to_date（：today1，'YYYY-MM-DD'）AND to_date（：today2，'YYYY-MM-DD'）”，[
>      '：today1' => $ today1，
>      '：today2' => $ today2 
> ]）
> ```

？？？？

**Comment by catfan** [comment]
Sorry, the previous answer is wrong.

We make the `BETWEEN` supports raw object on c33fdf8.

Can use it like this:
```php
"birthday[<>]" => [
    Medoo::raw("to_date(:from, 'YYYY-MM-DD')", [":from" => '2015/05/15']),
    Medoo::raw("to_date(:to, 'YYYY-MM-DD')", [":to" => '2025/05/15'])
]
```
```SQL
"birthday" BETWEEN to_date('2015/05/15', 'YYYY-MM-DD') AND to_date('2025/05/15', 'YYYY-MM-DD')
```

Also, for your case, we recommend just use the PHP `date_format()` to convert the date string. It will be faster.
```php
date_format(date_create("2015-05-15"), "Y-m-d")
```
