### ISSUE TITLE
Unable insert LOB data into Oracle database

### ISSUE THREAD

**Issue by xiasha11** [catfan/Medoo#970]
**Describe the bug**

**Information**
- Version of Medoo:1.7.10
- Type of Database (MySQL, MSSQL, SQLite...):oracle11g
- System (Liunx\Windows\Mac): windows

**Detail Code**
$database->insert("account", [
	"big_clob" => $big_clob    // clob类型字段

]);

**Expected output**
big_clob 无法插入,其他普通字段可以

**Comment by catfan** [comment]
We have improved insert and update LOBs for the Oracle database on e16ad3e.
