### ISSUE TITLE
sqlite order error.hope to fix this bug

### ISSUE THREAD

**Issue by wenhainan** [catfan/Medoo#974]
**Information**
- v1.6
- SQLite
- Windows

**Describe the Problem**
A clear and concise description of what the problem is.

**Detail Code**
ORDER did not work
     `   $data = db()->select('log','*',[
            "ORDER" => [
                'id'=>'desc'
            ],
            'LIMIT' => [$start, $pageSize]
        ]);
`

**Comment by catfan** [comment]
You should use `DESC` not `desc`.

```php
[
    "ORDER" => ['id' => 'DESC'],
    "LIMIT" => [$start, $pageSize]
]
```

**Comment by wenhainan** [comment]
got it
it does work .thanks very much


倚楼听风雨，淡看江湖路
On 5/31/2021 21:34，Angel ***@***.***> wrote：

You should use DESC not desc.

[
    "ORDER" => ['id' => 'DESC'],
    "LIMIT" => [$start, $pageSize]
]
