### ISSUE TITLE
Undefined array key "server" SQLite

### ISSUE THREAD

**Issue by vishalv26** [catfan/Medoo#978]
**Information**
- Version of Medoo: Latest
- Type of Database (MySQL, MSSQL, SQLite...): Sqlite
- System (Liunx\Windows\Mac): Linux

**Describe the Problem**
Undefined array key "server" in /heaven/php/vendor/catfan/medoo/src/Medoo.php on line 220

**Detail Code**
`$db = new Medoo([
    'type' => 'sqlite',
    'database' => __DIR__ . '/../../db/db.db'
]);`

**Expected output**
Should connect

**Comment by catfan** [comment]
This have been fixed on c68fbea65eab014ca954ff2550183854be998c97 with v2.1.0.
