### ISSUE TITLE
oracle error set 

### ISSUE THREAD

**Issue by xiasha11** [catfan/Medoo#980]
**Information**
- Version of Medoo:2.10
- Type of Database (MySQL, MSSQL, SQLite...):oracle11g
- System (Liunx\Windows\Mac):

**Describe the Problem**
oracle error set  not use

**Detail Code**
$database = new Medoo([
	// [required]
	'type' => 'oracle',
	'host' => 'localhost',
	'database' => 'name',
	'username' => 'your_username',
	'password' => 'your_password',
        'error' =>  PDO::ERRMODE_EXCEPTION
]);

**Expected output**
report undefined class constant 'errmode_exception' in  .......

**Comment by catfan** [comment]
Please make sure to set the error option as `PDO::ERRMODE_EXCEPTION` correctly.

The value of `PDO::ERRMODE_EXCEPTION` is upper case.

And try using `use PDO;` namespace statement for referring to the PDO constant.
