### ISSUE TITLE
Uncaught InvalidArgumentException: Incorrect column name: t. in Medoo.php on line 732

### ISSUE THREAD

**Issue by mkiriejevas** [catfan/Medoo#981]
**Information**
- Version of Medoo: 2.1.0
- Type of Database (MySQL, MSSQL, SQLite...): MySQL 8
- System (Liunx\Windows\Mac): Centos 7.9

**Describe the Problem**
Uncaught InvalidArgumentException: Incorrect column name: t. in Medoo.php on line 732

**Detail Code**
$db->insert("test",["t"=>"debug me"]);

**Expected output**
Column name of one letter is a valid name in MySQL, so the statement shall succeed.

**Comment by catfan** [comment]
Thanks for the feedback.

This fixed on bc17bcc.
