### ISSUE TITLE
Single-character table join aliases raises incorrectly raises InvalidArgumentException

### ISSUE THREAD

**Issue by usrbinsam** [catfan/Medoo#983]
**Information**
- Version of Medoo: 2.1.0
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Linux

**Describe the Problem**
Joining with a table with a single-character alias raises an InvalidArgumentException with an error message stating "Incorrect column name".

**Detail Code**
```php
        $rows = $this->db->select(
            "reports",
            [

                "[<]class (c)" => ["class" => "id"],
            ],
            [
                "c.name(className)",
            ],
            $where
        );
```

`Uncaught InvalidArgumentException: Incorrect column name: c.name. in /app/vendor/catfan/medoo/src/Medoo.php: 732`

**Expected output**
Single character aliases are valid SQL. This should not raise an error.

A simple workaround is just to use more than 1 character.

**Comment by catfan** [comment]
Thanks for the feedback.

This fixed on bc17bcc.
