### ISSUE TITLE
Can we add support for Couchbase N1QL / Elasticsearch ESQL? 

### ISSUE THREAD

**Issue by gautam-jha** [catfan/Medoo#985]
I am using Medoo for other databases like pgsql and oracle, 
but also i had other requirements to connect and run query quieres for `couchbase/elasticsearch`.

Couchbase SDK and extension installation isn't easy in any environment so i choose to work with its api.

Currently i am using  `php_curl` to call this but not sure if it is a good idea to do this but it is working for me and want to know if we can also extend medoo for this job with restapi calls to couchbase?

I can try my best to extend medoo to support API based databases, but need suggestions.

**Comment by catfan** [comment]
Medoo is a framework for SQL databases. It generates the SQL query for execution.

Couchbase and Elasticsearch is not a SQL database. Everything is different. So it's impossible to support that for Medoo.

**Comment by gautam-jha** [comment]
Yes, It is difficult for Medoo.  and will require special handleing for N1QL queries in  almost every methods. so you suggest should keep both approach saperate?

**Comment by catfan** [comment]
Yes, as I think. There is no need to do that.

You can check out the official project https://github.com/elastic/elasticsearch-php.

**Comment by gautam-jha** [comment]
Thanks @catfan
