### ISSUE TITLE
Array Serialization - appending " [JSON]" to column name produces an exception

### ISSUE THREAD

**Issue by jacklul** [catfan/Medoo#990]
**Information**
- Version of Medoo: 2.1.1
- Type of Database: PostgreSQL
- System (Linux\Windows\Mac): Win

**Describe the Problem**
Per documentation appending " [JSON]" to column name should serialize it as json, however instead exception is thrown.
```
InvalidArgumentException: Incorrect column name: settings [JSON]. in \vendor\catfan\medoo\src\Medoo.php:732
Stack trace:
#0 \vendor\catfan\medoo\src\Medoo.php(1728): Medoo\Medoo->columnQuote('settings [JSON]')
#1 Medoo\Medoo->insert('user', Array)
```

This happens for both "settings [JSON]" and "settings[JSON]".

**Detail Code**

Nothing ordinary, following the documentation. https://medoo.in/api/insert
The array I am trying to insert:
```
Array
(
    [name] => Test
    [username] => test
    [settings [JSON]] => Array
        (
            [test] => 1
        )
)
```

**Expected output**
Everything to work as per documentation.

I am completely confused whenever I'm doing something wrong or this is a bug.

**Comment by victornavarrete** [comment]
Space  in “settings [JSON]” “settings[JSON]”

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: ***@***.***>
Enviado: lunes, 19 de julio de 2021 13:59
Para: ***@***.***>
CC: ***@***.***>
Asunto: [catfan/Medoo] Array Serialization - appending " [JSON]" to column name produces an exception (#990)


Information

  *   Version of Medoo: 2.1.1
  *   Type of Database: PostgreSQL
  *   System (Linux\Windows\Mac): Win

Describe the Problem
Per documentation appending " [JSON]" to column name should serialize it as json, however instead exception is thrown.

InvalidArgumentException: Incorrect column name: settings [JSON]. in \vendor\catfan\medoo\src\Medoo.php:732

Stack trace:

#0 \vendor\catfan\medoo\src\Medoo.php(1728): Medoo\Medoo->columnQuote('settings [JSON]')

#1 Medoo\Medoo->insert('user', Array)

This happens for both "settings [JSON]" and "settings[JSON]".

Detail Code

Nothing ordinary, following the documentation. https://medoo.in/api/insert
The array I am trying to insert:

Array

(

    [name] => Test

    [username] => test

    [settings [JSON]] => Array

        (

            [test] => 1

        )

)

Expected output
Everything to work as per documentation.

I am completely confused whenever I'm doing something wrong or this is a bug.

**Comment by jacklul** [comment]
> Space in “settings [JSON]” “settings[JSON]”

From documentation:
```
$database->insert("account", [
	"user_name" => "foo",
	"email" => "foo@bar.com",
	"age" => 25,
	"lang [JSON]" => ["en", "fr", "jp", "cn"] // => \'["en","fr","jp","cn"]\'
]);
```

I tried without space with the same result.

**Comment by catfan** [comment]
We tested `settings [JSON]` and `settings[JSON]`. Both are no problem.

What's your code is actually called?

**Comment by jacklul** [comment]
Actually found out somewhere deeply in my code " [JSON]" was applied twice...
