### ISSUE TITLE
insert method has logical problem

### ISSUE THREAD

**Issue by amirziaee** [catfan/Medoo#992]
**Information**
- Version of Medoo: 2.1.2
- Type of Database : MySQL

**Describe the Problem**
when I use insert method data is entered twice.
please check your source .

**Detail Code**
`$database = new Medoo([

    'type' => 'mysql',
    'host' => 'localhost',
    'database' => 'databasename',
    'username' => 'username',
    'password' => 'password'
]);
 $data = [
    ['username' => 'foo',
    'userid' => '654654654'],
    ['username' => 'foo1',
    'userid' => '65460000']

 ];
$database->insert('users',  $data);`

![medoo](https://user-images.githubusercontent.com/43443182/128067163-881689f7-a070-4153-a892-2c7ff11f6b8c.JPG)

**Comment by logicalor** [comment]
This looks like correct behaviour on the part of Medoo.  I suspect you need to add a unique index on the `username` and `userid` cols if you don't want duplicate records.

**Comment by catfan** [comment]
We checked and there is no problem.

You may need to check how your code is called.

Use `log()` https://medoo.in/api/debug, or `debugLogging()` https://medoo.in/api/debug to see what queries are executed for the whole project.

**Comment by logicalor** [comment]
In addition to what @catfan wrote above, a unique index on the `username` and `userid` columns would prevent duplicates.

**Comment by amirziaee** [comment]
> In addition to what @catfan wrote above, a unique index on the `username` and `userid` columns would prevent duplicates.

 I know,it's work when use  the unique index but sometimes we wouldn't use unique index.

**Comment by catfan** [comment]
@amirziaee You can use `log()` or `debugLogging()` to see what queries are executed. It seems you called the `insert()` twice.
