### ISSUE TITLE
Allow Raw object as a $where argument in the delete method

### ISSUE THREAD

**Issue by logicalor** [catfan/Medoo#993]
**Information**
- Version of Medoo: 2.1.2
- Type of Database (MySQL, MSSQL, SQLite...): All
- System (Liunx\Windows\Mac): All

**Describe the Problem**
A Medoo `Raw` object can be supplied as the `$where` argument to the `select` and `update` methods, but not to the `delete` method.

**Detail Code**
The issue is because the `delete` method still enforces an `array` type for the `$where` argument.  If this `array` enforcement is removed, then a `Raw` object can be supplied, and the method works fine.

**Expected output**
A result identical to a result generated with a `$where` `array`.

**Comment by catfan** [comment]
Feature merged be00c6e.
