### ISSUE TITLE
How can I select fields from two tables?

### ISSUE THREAD

**Issue by cn-clb** [catfan/Medoo#999]
i have two tables:
table user, field: id,name
table common_set, field:id,org_name   _ps:common_set only one record_

I want generate this sql: 
select user.name,common_set.org_name from user,common where user.id=1 ;

How can I make this sql by get function?

**Comment by blessedjasonmwanza** [comment]
You can use JOIN for this problem. Here is a solution.
```php
$result = $db_instance->get('user', ['[>]common_set' => 'id'], 
['user.name', 'common_set.org_name']);
```
> This is equivalent to the following SQL;
```sql
SELECT `user`.`name`,`common_set`.`org_name` FROM `user` LEFT JOIN `common_set` USING (`id`) LIMIT 1
```

**Comment by cn-clb** [comment]
Thanks! @blessedjasonmwanza
